[SDK-3274] Content changes to ASP.NET Core Wep API Quickstart
auth0/docs pull request #10062
Opened 2022-05-04 10:52 UTC by frederikprijck

2022-05-04 14:53 UTC, evansims approved these changes

2022-05-12 13:53 UTC, stevehobbsdev requested changes

2022-05-12 13:53 UTC, stevehobbsdev commented on articles/quickstart/backend/aspnet-core-webapi/interactive.md
>  ### Obtaining an Access Token
Should be lowercase

```suggestion
### Obtaining an access token
```

2022-05-12 13:53 UTC, stevehobbsdev commented on articles/quickstart/backend/aspnet-core-webapi/interactive.md
> +* `GET /api/private-scoped` is available for authenticated requests containing an Access Token with the `read:messages` scope.
```suggestion
* `GET /api/private-scoped` is available for authenticated requests containing an access token with the `read:messages` scope.
```

2022-05-20 08:31 UTC, stevehobbsdev approved these changes

2022-06-01 21:40 UTC, rkhoriander approved these changes

2022-06-02 07:59 UTC, merged