[SDK-3277] Content changes to Angular Quickstart
auth0/docs pull request #10061
Opened 2022-05-03 13:17 UTC by frederikprijck

A couple of adjustments to the Angular quickstart to be more aligned with the Style Guide.

2022-05-12 13:57 UTC, stevehobbsdev requested changes
👍🏻

2022-05-12 13:57 UTC, stevehobbsdev commented on articles/quickstart/spa/angular/interactive.md
>  ## Register and Configure AuthModule {{{ data-action="code" data-code="app.module.ts#10:13" }}}
Style guide: titles should be sentence case

```suggestion
## Register and configure AuthModule {{{ data-action="code" data-code="app.module.ts#10:13" }}}
```

2022-05-12 13:57 UTC, stevehobbsdev commented on articles/quickstart/spa/angular/interactive.md
>  ## Add Login to Your Application {{{ data-action=code data-code="login-button.ts#11:13" }}}
```suggestion
## Add login to your application {{{ data-action=code data-code="login-button.ts#11:13" }}}
```

2022-05-12 13:57 UTC, stevehobbsdev commented on articles/quickstart/spa/angular/interactive.md
> +The Auth0 Angular SDK provides tools to quickly implement user authentication in an Angular application, such as creating a login button using the `loginWithRedirect()` method from the `AuthService`
```suggestion
The Auth0 Angular SDK provides tools to quickly implement user authentication in an Angular application, such as creating a login button using the `loginWithRedirect()` method from the `AuthService` service class. Executing `loginWithRedirect()` redirects the users to the Auth0 Universal Login page. Upon successful authentication, Auth0 will redirect the users back to the original application.
```

2022-05-12 13:57 UTC, stevehobbsdev commented on articles/quickstart/spa/angular/interactive.md
>  ## Show User Profile Information {{{ data-action=code data-code="user-profile.ts" }}}
Style guide: titles should be sentence case

```suggestion
## Show user profile information {{{ data-action=code data-code="user-profile.ts" }}}
```

2022-05-20 08:31 UTC, stevehobbsdev approved these changes

2022-06-01 21:04 UTC, rkhoriander approved these changes

2022-06-01 21:04 UTC, merged