[SDK-3278] Content changes to JavaScript Quickstart
auth0/docs pull request #10063
Opened 2022-05-04 11:54 UTC by adamjmcgrath

A couple of adjustments to the JavaScript quickstart to be more aligned with the Style Guide.

2022-05-04 14:53 UTC, evansims approved these changes

2022-05-12 13:55 UTC, stevehobbsdev requested changes

2022-05-12 13:55 UTC, stevehobbsdev commented on articles/quickstart/spa/vanillajs/interactive.md
>  ## Handle the Callback from Auth0 {{{ data-action=code data-code="app.js#14:19" }}}
Style guide: titles should be sentence case

```suggestion
## Handle the callback from Auth0 {{{ data-action=code data-code="app.js#14:19" }}}
```

2022-05-12 15:19 UTC, stevehobbsdev approved these changes

2022-06-01 21:03 UTC, rkhoriander approved these changes

2022-06-01 21:04 UTC, merged