[SDK-3215] Added configuring auth0 credentials section
auth0/docs pull request #10066
Opened 2022-05-05 08:21 UTC by poovamraj

- Restructured old section to highlight Web.config file
- Added `Configure the Middleware` as a new section
- Rearranged the file order

2022-05-05 08:56 UTC, frederikprijck requested changes

2022-05-05 08:56 UTC, frederikprijck commented on articles/quickstart/webapp/aspnet-owin/interactive.md
> +## Setup the Project {{{ data-action=code data-code="Web.config#1:7" }}}
I believe Setup the Project sounds like we are helping them set up the entire project, while all were are doing is help them install and configure the middleware.

2022-05-09 10:04 UTC, frederikprijck approved these changes

2022-05-31 17:19 UTC, avanscoy approved these changes
Adding my approval. Needs reviewed by @poovamraj before merge.

2022-05-31 18:37 UTC, frederikprijck commented
@avanscoy As the author of the PR, I think @poovamraj can't approve this PR. Are you okay with that I merge this?

2022-05-31 18:39 UTC, avanscoy commented
Sure. I wanted to make sure the changes I made didn't hurt the content, but as long as it's fine, go for it.

2022-05-31 18:40 UTC, frederikprijck commented
Ooooh that does make sense. Sorry about that, @poovamraj could you let us know if the changes look fine for you regarding that? Feel free to merge if they do!

2022-06-01 08:07 UTC, poovamraj commented
Hey @frederikprijck and @avanscoy, I have checked it out and this is good to go. I am merging this.

2022-06-01 08:07 UTC, merged