[SDK-3135] New Express API Interactive QuickStart
auth0/docs pull request #10071
Opened 2022-05-05 15:17 UTC by adamjmcgrath

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/1299658/166943312-578410f5-128e-479a-b318-cf8f1aa4ac72.png">

2022-05-06 07:31 UTC, frederikprijck approved these changes, later dismissed

2022-05-09 19:14 UTC, frederikprijck reviewed
Should this need a checkpoint section as mentioned in https://oktawiki.atlassian.net/wiki/spaces/DXSDK/pages/2540963444/How+to+Migrate+a+Quickstart+to+the+New+Design#Checkpoints ?

Using a checkpoint is the new way to gather feedback from the user regarding the quickstart.

2022-05-12 12:04 UTC, stevehobbsdev requested changes
LGTM, just left some style guide-related thing

2022-05-12 12:04 UTC, stevehobbsdev commented on articles/quickstart/backend/nodejs/interactive.md
> +The `checkJwt` middleware shown to the right checks if the user's Access Token included in the request is valid. If the token is not valid, the user gets a 401 Authorization error when they try to ac
Style guide (word list): access token should be lowercase

```suggestion
The `checkJwt` middleware shown to the right checks if the user's access token included in the request is valid. If the token is not valid, the user gets a 401 Authorization error when they try to access the endpoints.
```

2022-05-12 12:04 UTC, stevehobbsdev commented on articles/quickstart/backend/nodejs/interactive.md
> +In this configuration, only Access Tokens with the `read:messages` scope can access the endpoint.
Style guide (word list): access token should be lowercase

```suggestion
In this configuration, only access tokens with the `read:messages` scope can access the endpoint.
```

2022-05-12 12:04 UTC, stevehobbsdev commented on articles/quickstart/backend/nodejs/interactive.md
> +* `GET /api/private-scoped` is available for authenticated requests containing an Access Token with the `read:messages` scope.
Style guide (word list): access token should be lowercase

```suggestion
* `GET /api/private-scoped` is available for authenticated requests containing an access token with the `read:messages` scope.
```

2022-05-12 15:19 UTC, stevehobbsdev approved these changes, later dismissed

2022-05-13 11:25 UTC, frederikprijck approved these changes, later dismissed

2022-05-25 15:04 UTC, tr0njavolta requested changes
Some suggestions and style updates.

2022-05-25 15:04 UTC, tr0njavolta commented on articles/quickstart/backend/nodejs/interactive.md
> +If you haven't created an API in your Auth0 dashboard yet, you can use the interactive selector to create a new Auth0 API or select an existing API that represents the project you want to integrate w
```suggestion
If you have not created an API in your Auth0 dashboard yet, use the interactive selector to create a new Auth0 API or select an existing project API.
```

2022-05-25 15:04 UTC, tr0njavolta commented on articles/quickstart/backend/nodejs/interactive.md
> +First install the SDK using npm.
```suggestion
First, install the SDK with `npm`.
```

2022-05-25 15:04 UTC, tr0njavolta commented on articles/quickstart/backend/nodejs/interactive.md
> +The middleware doesn't check if the token has the sufficient scope to access the requested resources.
```suggestion
The middleware does not check if the token has sufficient scope to access the requested resources.
```

2022-05-25 15:04 UTC, tr0njavolta commented on articles/quickstart/backend/nodejs/interactive.md
> +* make sure the token is added as the `Authorization` header
```suggestion
If your application did not start successfully:
```

2022-05-25 15:04 UTC, tr0njavolta commented on articles/quickstart/backend/nodejs/interactive.md
> +* does the token have the correct scopes? You can use [jwt.io](https://jwt.io/) to verify.
```suggestion
* Verify you added the token as the `Authorization` header
* Ensure the token has the correct scopes. Verify with [jwt.io](https://jwt.io/).
```

2022-05-25 15:04 UTC, tr0njavolta commented on articles/quickstart/backend/nodejs/interactive.md
> +
```suggestion
To set up your first API through the Auth0 dashboard, review [our getting started guide](get-started/auth0-overview/set-up-apis).
```

2022-05-25 15:04 UTC, tr0njavolta commented on articles/quickstart/backend/nodejs/interactive.md
> +Every API in Auth0 is configured using an API Identifier that your application code will use as the Audience to validate the access token.
```suggestion
Each Auth0 API uses the API Identifier, which your application needs to validate the access token.
```

2022-05-26 15:47 UTC, tr0njavolta approved these changes

2022-05-26 15:49 UTC, merged