[SDK-3285] Add Python Web App Interactive QuickStart
auth0/docs pull request #10073
Opened 2022-05-06 14:29 UTC by adamjmcgrath

<img width="1481" alt="image" src="https://user-images.githubusercontent.com/1299658/167153508-ca4c2eac-fb42-42cc-9bce-60b974d8c60d.png">

2022-05-09 19:14 UTC, frederikprijck reviewed
Should this need a checkpoint section as mentioned in https://oktawiki.atlassian.net/wiki/spaces/DXSDK/pages/2540963444/How+to+Migrate+a+Quickstart+to+the+New+Design#Checkpoints ?

Using a checkpoint is the new way to gather feedback from the user regarding the quickstart.

2022-05-11 10:44 UTC, adamjmcgrath commented
Ah, yep, good point @frederikprijck - will add one to this (and the other PRs I have open) 👍

2022-05-12 08:10 UTC, frederikprijck approved these changes, later dismissed

2022-05-12 12:02 UTC, stevehobbsdev requested changes

2022-05-12 12:02 UTC, stevehobbsdev commented on articles/quickstart/webapp/python/interactive.md
> +* Make sure the domain and client ID imported correctly.
Style guide (word list): Client ID should be capitalized

```suggestion
* Make sure the domain and Client ID imported correctly.
```

2022-05-12 12:58 UTC, frederikprijck submitted a review, later dismissed

2022-05-12 13:51 UTC, stevehobbsdev submitted a review, later dismissed

2022-05-19 19:10 UTC, tr0njavolta reviewed
Some comments for clarity and style guide. Let me know if these can be integrated and I'll approve.

2022-05-19 19:10 UTC, tr0njavolta commented on articles/quickstart/webapp/python/interactive.md
> +Auth0 allows you to quickly add authentication and gain access to user profile information in your application. This guide demonstrates how to integrate Auth0 with a Python [Flask](https://flask.pall
```suggestion
Auth0 allows you to add authentication and gain access to user profile information in your application. This guide demonstrates how to integrate Auth0 with a Python [Flask](https://flask.palletsprojects.com) application using the [Authlib](https://authlib.org/) SDK.
```

2022-05-19 19:10 UTC, tr0njavolta commented on articles/quickstart/webapp/python/interactive.md
> +Begin by creating a `requirements.txt` file in your project directory:
```suggestion
Create a `requirements.txt` file in your project directory:
```

2022-05-19 19:10 UTC, tr0njavolta commented on articles/quickstart/webapp/python/interactive.md
> +You should now run `pip install -r requirements.txt` from your shell to make these dependencies available to your project.
```suggestion
Run the following command from your shell to enable these dependencies in your project:

```sh
pip install -r requirements.txt
```
```

2022-05-19 19:10 UTC, tr0njavolta commented on articles/quickstart/webapp/python/interactive.md
> +- Generate a suitable string for `APP_SECRET_KEY` using `openssl rand -hex 32` from your shell.
```suggestion
- Generate a string for `APP_SECRET_KEY` using `openssl rand -hex 32` from your shell.
```

2022-05-19 19:10 UTC, tr0njavolta commented on articles/quickstart/webapp/python/interactive.md
> +Now you're ready to start writing your application. Create a `server.py` file in your project directory - this file will hold all of your application logic.
```suggestion
Next, set up your application. Create a `server.py` file in your project directory - this file will contain your application logic.
```

2022-05-19 19:10 UTC, tr0njavolta commented on articles/quickstart/webapp/python/interactive.md
> +Begin by importing all the libraries your application will be making use of.
```suggestion
Import all the libraries your application needs.
```

2022-05-19 19:10 UTC, tr0njavolta commented on articles/quickstart/webapp/python/interactive.md
> +Then load the configuration `.env` file you made in the previous step.
```suggestion
Load the configuration `.env` file you made in the previous step.
```

2022-05-19 19:10 UTC, tr0njavolta commented on articles/quickstart/webapp/python/interactive.md
> +Then configure Authlib to handle your application's authentication with Auth0. You can learn more about the configuration options available for Authlib's OAuth `register()` method from [their documen
```suggestion
Configure Authlib to handle your application's authentication with Auth0. To learn more about the configuration options available for Authlib's OAuth `register()` method from [their documentation.](https://docs.authlib.org/en/latest/client/frameworks.html#using-oauth-2-0-to-log-in)
```

2022-05-19 19:10 UTC, tr0njavolta commented on articles/quickstart/webapp/python/interactive.md
> +For this demonstration, we'll be adding 4 routes for your application: your login, callback, logout and home routes.
```suggestion
In this example, you will add four routes to the application: login, callback, logout, and home.
```

2022-05-19 19:10 UTC, tr0njavolta commented on articles/quickstart/webapp/python/interactive.md
> +When visitors to your app visit the `/login` route, they'll be redirected to Auth0 to begin the authentication flow.
```suggestion
When visitors to your app visit the `/login` route, your application will route them to the Auth0 login page.
```

2022-05-19 19:10 UTC, tr0njavolta commented on articles/quickstart/webapp/python/interactive.md
> +After your users finish logging in with Auth0, they'll be returned to your application at the `/callback` route. This route is responsible for actually saving the session for the user, so when they v
```suggestion
After your users log in with Auth0, your application will route them to the `/callback` route. This route saves the session for the user and bypasses the need for them to login again when they return.
```

2022-05-19 19:10 UTC, tr0njavolta commented on articles/quickstart/webapp/python/interactive.md
> +As you might expect, the `/logout` route handles signing a user out from your application. It will clear the user's session in your app, and briefly redirect to Auth0's logout endpoint to ensure thei
```suggestion
The `/logout` route signs users out from your application. This route clears the user session in your app and redirects to the Auth0 logout endpoint to ensure the session is no longer saved. Then, the application redirects the user to your home route.
```

2022-05-19 19:10 UTC, tr0njavolta commented on articles/quickstart/webapp/python/interactive.md
> +Last but not least, your `/` home route will serve as a place to either render an authenticated user's details, or offer to allow visitors to sign in.
```suggestion
Your `/ ` home route either renders an authenticated user's details or  allows visitors to sign in.
```

2022-05-19 19:10 UTC, tr0njavolta commented on articles/quickstart/webapp/python/interactive.md
> +Create a new sub-directory in your project folder named `templates`, and create `home.html`. You can paste the content from the right into that file.
```suggestion
Next, create the template file used in the home route (during `render_template()` calls).

Create a new sub-directory in your project folder named `templates`, and create `home.html`  in the directory. Paste the content from the right into that file.
```

2022-05-19 19:10 UTC, tr0njavolta commented on articles/quickstart/webapp/python/interactive.md
> +You're ready to run your application! From your project directory, open a shell and use:
```suggestion
To run your application, navigate to the root of your project directory and open a terminal. Run the following command:
```

2022-05-19 19:10 UTC, tr0njavolta commented on articles/quickstart/webapp/python/interactive.md
> +Your application should be running, when you visit [http://localhost:3000](http://localhost:3000) you should see a login button that takes you to Auth0 to login, then back to your application to see
```suggestion
Visit [http://localhost:3000](http://localhost:3000) to verify. You should find a login button routing to Auth0 for login, then back to your application to see your profile information.
```

2022-05-19 19:10 UTC, tr0njavolta commented on articles/quickstart/webapp/python/interactive.md
> +
```suggestion
If your application did not start successfully:
* Verify any errors in the console.
* Verify the domain and Client ID imported correctly.
* Verify your tenant configuration.

```

2022-05-20 10:07 UTC, frederikprijck commented
Thanks @tr0njavolta , I updated the PR to incorporate the suggestions.

2022-05-25 22:04 UTC, tr0njavolta approved these changes

2022-05-26 09:15 UTC, merged