[SDK-3279] Add Django Web App interactive QuickStart
auth0/docs pull request #10076
Opened 2022-05-10 12:35 UTC by adamjmcgrath

<img width="1488" alt="image" src="https://user-images.githubusercontent.com/1299658/167629334-20f26a18-fccb-4845-9c02-c4a28b574d26.png">

2022-05-12 08:09 UTC, frederikprijck requested changes

2022-05-12 08:09 UTC, frederikprijck commented on articles/quickstart/webapp/django/interactive.md
> +  - login
We will need to change these topics to represent django instead of aspnet

2022-05-12 08:09 UTC, frederikprijck commented on articles/quickstart/webapp/django/interactive.md
> +  - login
We will need to change these topics to represent django instead of aspnet

2022-05-12 11:49 UTC, stevehobbsdev reviewed
Left a quick thing, otherwise looks good

2022-05-12 11:49 UTC, stevehobbsdev commented on articles/quickstart/webapp/django/interactive.md
> +## Create application
I think this feels better, but up to you.

```suggestion
## Create an application
```

2022-05-12 15:19 UTC, stevehobbsdev submitted a review, later dismissed

2022-05-19 19:36 UTC, tr0njavolta reviewed
Some comments and style changes. Let me know if these can be integrated and I'll approve

2022-05-19 19:36 UTC, tr0njavolta commented on articles/quickstart/webapp/django/interactive.md
> +Auth0 allows you to quickly add authentication and gain access to user profile information in your application. This guide demonstrates how to integrate Auth0 with a Python [Django](https://www.djang
```suggestion
Auth0 allows you to add authentication and gain access to user profile information in your application. This guide demonstrates how to integrate Auth0 with a Python [Django](https://www.djangoproject.com/) application using the [Authlib](https://authlib.org/) SDK.
```

2022-05-19 19:36 UTC, tr0njavolta commented on articles/quickstart/webapp/django/interactive.md
> +For this integration you'll need few library dependencies, such as Authlib. Go ahead and create a `requirements.txt` file in your project directory, and include the following:
```suggestion
For this integration, you will add several library dependencies, such as Authlib. Create a `requirements.txt` file in your project directory, and include the following:
```

2022-05-19 19:36 UTC, tr0njavolta commented on articles/quickstart/webapp/django/interactive.md
> +You should now run `pip install -r requirements.txt` from your shell to make these dependencies available to your project.
```suggestion
Run the following command from your shell to make these dependencies available:

```sh
pip install -r requirements.txt
```
```

2022-05-19 19:36 UTC, tr0njavolta commented on articles/quickstart/webapp/django/interactive.md
> +If you already have a Django application setup, you can skip to the next step. Otherwise, create your new application project. From your shell, run the following command, and switch to the new projec
```suggestion
If you already have a Django application setup, skip to the next step. For a new application project, run the following command:   
```

2022-05-19 19:36 UTC, tr0njavolta commented on articles/quickstart/webapp/django/interactive.md
> +```
```suggestion
```sh
django-admin startproject webappexample
```

Change to the new project folder:

```sh
cd webappexample 
```

2022-05-19 19:36 UTC, tr0njavolta commented on articles/quickstart/webapp/django/interactive.md
> +Make some minor changes to your `webappexample/settings.py` file to read those `.env` values.
```suggestion
Open the `webappexample/settings.py` file to review the `.env` values.
```

2022-05-19 19:36 UTC, tr0njavolta commented on articles/quickstart/webapp/django/interactive.md
> +Next, find the `TEMPLATES` variable and update the `DIRS` value to add our `TEMPLATE_DIR` string. This tells Django where to look for our template files, once we create them. Keep any other content o
```suggestion
Next, find the `TEMPLATES` variable and update the `DIRS` value to add our `TEMPLATE_DIR` string. This determines the path of the template files, which you will create in a future step.
Keep any other content of this array the same.
```

2022-05-19 19:36 UTC, tr0njavolta commented on articles/quickstart/webapp/django/interactive.md
> +Finally, at the end of this file, add the code to load the Auth0 config.
```suggestion
At the end of this file, add the code to load the Auth0 config.
```

2022-05-19 19:36 UTC, tr0njavolta commented on articles/quickstart/webapp/django/interactive.md
> +Now you're ready to start writing your application. Open the `webappexample/views.py` file in your IDE.
```suggestion
To begin creating your application, open the `webappexample/views.py` file in your IDE.
```

2022-05-19 19:36 UTC, tr0njavolta commented on articles/quickstart/webapp/django/interactive.md
> +Begin by importing all the libraries your application will be making use of.
```suggestion
Import all the libraries your application needs.
```

2022-05-19 19:36 UTC, tr0njavolta commented on articles/quickstart/webapp/django/interactive.md
> +You can learn more about the configuration options available for Authlib's OAuth `register()` method from [their documentation.](https://docs.authlib.org/en/latest/client/frameworks.html#using-oauth-
```suggestion
Learn more about the configuration options available for Authlib's OAuth `register()` method from [their documentation.](https://docs.authlib.org/en/latest/client/frameworks.html#using-oauth-2-0-to-log-in)
```

2022-05-19 19:36 UTC, tr0njavolta commented on articles/quickstart/webapp/django/interactive.md
> +For this demonstration, we'll be adding 4 routes for your application: your login, callback, logout and index routes.
```suggestion
In this example, you will add four routes for your application: the login, callback, logout, and index routes.
```

2022-05-19 19:36 UTC, tr0njavolta commented on articles/quickstart/webapp/django/interactive.md
> +- `index` - Last but not least, your home route will serve as a place to either render an authenticated user's details, or offer to allow visitors to sign in.
```suggestion
- `login` - When visitors to your app visit the `/login` route, they will reach Auth0 to begin the authentication flow.
- `callback` - After your users finish logging in with Auth0, they will return to your application at the `/callback` route. This route saves the session for the user and bypasses the need for them to login again when they return.
- `logout` - +The `/logout` route signs users out from your application. This route clears the user session in your app and redirects to the Auth0 logout endpoint to ensure the session is no longer saved. Then, the application redirects the user to your home route.
- `index` - The home route will render an authenticated user's details or allow visitors to sign in.
```

2022-05-19 19:36 UTC, tr0njavolta commented on articles/quickstart/webapp/django/interactive.md
> +Tell Django how to connect these new routes by replacing the contents of your `webappexample/urls.py` file with the code on the right.
```suggestion
Replace the contents of your `webappexample/urls.py` file with the code on the right to connect to these new routes.
```

2022-05-19 19:36 UTC, tr0njavolta commented on articles/quickstart/webapp/django/interactive.md
> +Now we just need to create a simple template file used in the home page route.
```suggestion
Next, you will create a template file used in the home page route.
```

2022-05-19 19:36 UTC, tr0njavolta commented on articles/quickstart/webapp/django/interactive.md
> +The `index.html` file will contain template code that will show the user's info if they're logged in, or present them with a login button if they're logged out.
```suggestion
The `index.html` file will contain template code to display the user's info if logged in or present them with a login button if logged out. 
```

2022-05-19 19:36 UTC, tr0njavolta commented on articles/quickstart/webapp/django/interactive.md
> +Your application should be running, when you visit [http://localhost:3000](http://localhost:3000) you should see a login button that takes you to Auth0 to login, then back to your application to see
```suggestion
Visit [http://localhost:3000](http://localhost:3000) to verify. You should find a login button routing to Auth0 for login, then back to your application to see your profile information.
```

2022-05-19 19:36 UTC, tr0njavolta commented on articles/quickstart/webapp/django/interactive.md
> +* Make sure your tenant is correctly configured.
```suggestion
If your application did not start successfully:
* Verify any errors in the console.
* Verify the domain and Client ID imported correctly.
* Verify your tenant configuration.
```

2022-05-20 09:59 UTC, frederikprijck commented
Thanks @tr0njavolta, I updated the PR to incorporate the suggestions, thanks!

2022-05-25 15:24 UTC, tr0njavolta approved these changes

2022-06-01 10:30 UTC, frederikprijck approved these changes

2022-06-01 10:30 UTC, merged