Add Ionic (Angular) & Capacitor interactive quickstart
auth0/docs pull request #10086
Opened 2022-05-12 11:08 UTC by stevehobbsdev

![image](https://user-images.githubusercontent.com/766403/168058321-8cacc539-5954-4507-834b-caa9848c2563.png)

2022-05-12 11:48 UTC, frederikprijck approved these changes, later dismissed

2022-05-13 09:54 UTC, stevehobbsdev commented
Similar to Ionic React, I extracted the content from `configure_auth0_interactive` and modified to suit this QS.

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/766403/168259498-8851ae71-4d34-47eb-b635-a08a7f5b6612.png">

2022-05-13 11:19 UTC, frederikprijck approved these changes

2022-05-16 08:27 UTC, frederikprijck requested changes
As mentioned on Slack, we are updating existing files that are used in the old quickstart. Even though that old quickstart shouldn't be used on auth0.com/docs anymoe. It is still used in manage.auth0.com, so we shouldn't touch these files in such a way that they refer to interactive selector or anything that's part of the redesign.

2022-05-16 14:27 UTC, stevehobbsdev commented
Resolved in a58606135

2022-05-20 07:55 UTC, frederikprijck approved these changes, later dismissed

2022-05-26 19:37 UTC, avanscoy approved these changes

2022-05-26 19:37 UTC, merged