[SDK-3291] Add interactive Laravel API QuickStart
auth0/docs pull request #10091
Opened 2022-05-17 11:47 UTC by frederikprijck

![image](https://user-images.githubusercontent.com/2146903/168803808-a3f65c19-f7f6-4060-83b5-1e1cff9b3613.png)

2022-05-17 18:14 UTC, stevehobbsdev requested changes
👍🏻

2022-05-17 18:14 UTC, stevehobbsdev commented on articles/quickstart/backend/laravel/interactive.md
> +# Add authorization to a Laravel application.
```suggestion
# Add authorization to a Laravel application
```

2022-05-17 18:14 UTC, stevehobbsdev commented on articles/quickstart/backend/laravel/interactive.md
> +Every API in Auth0 is configured using an API Identifier that your application code will use as the Audience to validate the access token.
```suggestion
Every API in Auth0 is configured using an API identifier that your application code will use as the audience to validate the access token.
```

2022-05-17 18:14 UTC, stevehobbsdev commented on articles/quickstart/backend/laravel/interactive.md
> +## Create a Laravel Application
```suggestion
## Create a Laravel application
```

2022-05-17 18:14 UTC, stevehobbsdev commented on articles/quickstart/backend/laravel/interactive.md
> +Let's begin by setting up a new Laravel application. Let's open a shell and run the following command — replacing `DIRECTORY_NAME` with a directory name of preference to create and install Laravel wi
```suggestion
Let's begin by setting up a new Laravel application. Open a shell and run the following command — replacing `DIRECTORY_NAME` with a directory name of preference to create and install Laravel within. The directory cannot already exist.
```

2022-05-17 18:14 UTC, stevehobbsdev commented on articles/quickstart/backend/laravel/interactive.md
> +If you are calling the API from a Single-Page Application or a Mobile/Native application, after the authorization flow is completed, you will get an access token. How you get the token and how you ma
```suggestion
If you are calling the API from a single-page application or a mobile/native application, after the authorization flow is completed, you will get an access token. How you get the token and how you make the call to the API will be dependent on the type of application you are developing and the framework you are using. For more information refer to the relevant application quickstarts which contain detailed instructions:
```

2022-05-17 18:14 UTC, stevehobbsdev commented on articles/quickstart/backend/laravel/interactive.md
> +* [Single-Page Applications](/quickstart/spa)
```suggestion
* [Single-page applications](/quickstart/spa)
```

2022-05-17 18:14 UTC, stevehobbsdev commented on articles/quickstart/backend/laravel/interactive.md
> +* [Mobile / Native Application](/quickstart/native)
```suggestion
* [Mobile / native application](/quickstart/native)
```

2022-05-17 18:14 UTC, stevehobbsdev commented on articles/quickstart/backend/laravel/interactive.md
> +Auth0 customers are billed based on the number of Machine to Machine access tokens issued by Auth0. Once your application gets an access token it should keep using it until it expires, to minimize th
```suggestion
Auth0 customers are billed based on the number of machine-to-machine access tokens issued by Auth0. Once your application gets an access token it should keep using it until it expires, to minimize the number of tokens requested.
```

2022-05-20 08:32 UTC, stevehobbsdev approved these changes, later dismissed

2022-05-23 21:50 UTC, evansims approved these changes, later dismissed

2022-05-25 18:49 UTC, avanscoy approved these changes

2022-05-25 18:57 UTC, merged