[SDK-3331] Spring boot Webapp QS migration
auth0/docs pull request #10101
Opened 2022-06-02 15:03 UTC by poovamraj

We have migrated the Spring webapp Quickstart to the interactive version. Added screenshots of the content and code

![image](https://user-images.githubusercontent.com/15910425/171660096-ec770057-0412-4c76-bb15-1d88cb967a66.png)

![image](https://user-images.githubusercontent.com/15910425/171660124-0a772b75-944d-4ba7-973a-23a993a7fc46.png)

2022-06-03 07:38 UTC, frederikprijck requested changes

2022-06-03 07:38 UTC, frederikprijck commented on articles/quickstart/webapp/java-spring-boot/interactive.md
> +## Configure Spring Boot Application
```suggestion
## Configure Spring Boot application
```

2022-06-03 07:38 UTC, frederikprijck commented on articles/quickstart/webapp/java-spring-boot/interactive.md
> +## Add Login to Your Application {{{ data-action=code data-code="SecurityConfig.java" }}}
```suggestion
## Add login to your application {{{ data-action=code data-code="SecurityConfig.java" }}}
```

2022-06-03 07:38 UTC, frederikprijck commented on articles/quickstart/webapp/java-spring-boot/interactive.md
> +## Add Front Page {{{ data-action=code data-code="index.html" }}}
```suggestion
## Add front page {{{ data-action=code data-code="index.html" }}}
```

2022-06-03 07:38 UTC, frederikprijck commented on articles/quickstart/webapp/java-spring-boot/interactive.md
> +## Add Controller {{{ data-action=code data-code="HomeController.java" }}}
```suggestion
## Add controller {{{ data-action=code data-code="HomeController.java" }}}
```

2022-06-03 07:38 UTC, frederikprijck commented on articles/quickstart/webapp/java-spring-boot/interactive.md
> +## Add Logout to Your Application {{{ data-action=code data-code="LogoutHandler.java" }}}
```suggestion
## Add logout to your application {{{ data-action=code data-code="LogoutHandler.java" }}}
```

2022-06-03 07:38 UTC, frederikprijck commented on articles/quickstart/webapp/java-spring-boot/interactive.md
> +## Update your Security Configuration {{{ data-action=code data-code="SecurityConfigWithLogout.java" }}}
```suggestion
## Update your security configuration {{{ data-action=code data-code="SecurityConfigWithLogout.java" }}}
```

2022-06-03 16:10 UTC, tr0njavolta reviewed
Some style updates

2022-06-03 16:10 UTC, tr0njavolta commented on articles/quickstart/webapp/java-spring-boot/interactive.md
> +This tutorial uses [Spring MVC](https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html). If you are using [Spring WebFlux](https://docs.spring.io/spring/docs/current/spring-fr
```suggestion
This tutorial uses [Spring MVC](https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html). If you are using [Spring WebFlux](https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#spring-web-reactive), the steps to add authentication are similar, but some implementation details are different. Refer to the [Spring Boot WebFlux Sample Code](https://github.com/auth0-samples/auth0-spring-boot-login-samples/tree/master/webflux-login) to see how to integrate Auth0 with your Spring Boot WebFlux application.
```

2022-06-03 16:10 UTC, tr0njavolta commented on articles/quickstart/webapp/java-spring-boot/interactive.md
> +The Spring Security 5.4.0 release will include [a fix](https://github.com/spring-projects/spring-security/pull/8357) to validate the issuer claim of the ID token. You should update to this release wh
```suggestion
The Spring Security 5.4.0 release includes [a fix](https://github.com/spring-projects/spring-security/pull/8357) to validate the ID token issuer claim. Upgrade to 5.4.0 or higher when possible.
```

2022-06-03 16:10 UTC, tr0njavolta commented on articles/quickstart/webapp/java-spring-boot/interactive.md
> +Spring Security will use the `issuer-uri` property value to retrieve all the information necessary to enable login and validation of the ID token at runtime.
```suggestion
Spring Security uses the `issuer-uri` property value to retrieve the information necessary to enable login and ID token validation at runtime.
```

2022-06-03 16:10 UTC, tr0njavolta commented on articles/quickstart/webapp/java-spring-boot/interactive.md
> +[Additional property mappings](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2login-boot-property-mappings) are available for further customization, if required.
```suggestion
If you need more property mappings, [review the Spring documentation](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2login-boot-property-mappings) for further customization.
```

2022-06-03 16:10 UTC, tr0njavolta commented on articles/quickstart/webapp/java-spring-boot/interactive.md
> +To enable users to login with Auth0, you will need to extend the [WebSecurityConfigurerAdapter](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/config/annota
```suggestion
To enable user login with Auth0, extend the [WebSecurityConfigurerAdapter](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/config/annotation/web/configuration/WebSecurityConfigurerAdapter.html) class and override the `configure(HttpSecurity http)` method.
```

2022-06-03 16:10 UTC, tr0njavolta commented on articles/quickstart/webapp/java-spring-boot/interactive.md
> +Later in this quickstart we will overwrite this file with `SecurityConfigWithLogout.java` to provide extra configurations to support the Logout feature.
```suggestion
Later in this quickstart, you will overwrite this file with `SecurityConfigWithLogout.java` to provide extra configurations to support the logout feature.
```

2022-06-03 16:10 UTC, tr0njavolta commented on articles/quickstart/webapp/java-spring-boot/interactive.md
> +You can further configure the [HttpSecurity](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/config/annotation/web/builders/HttpSecurity.html) instance to re
```suggestion
You can configure the [HttpSecurity](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/config/annotation/web/builders/HttpSecurity.html) instance to require authentication on all or certain paths. For example, to require authentication on all paths except the home page:
```

2022-06-03 16:10 UTC, tr0njavolta commented on articles/quickstart/webapp/java-spring-boot/interactive.md
> +Spring Security will use the client configuration you defined earlier to handle login when a user visits the `/oauth2/authorization/auth0` path of your application. You can use this to create a login
```suggestion
Spring Security uses the client configuration you defined earlier to handle login when a user visits the `/oauth2/authorization/auth0` path of your application. You can use this to create a login link in your application.
```

2022-06-03 16:10 UTC, tr0njavolta commented on articles/quickstart/webapp/java-spring-boot/interactive.md
> +We show the user attributes in this page when the user is authenticated. The `/logout` link in the template will be later used while implementing the Logout feature.
```suggestion
This page returns the user attributes when the user authentications. You will use the `/logout` link in the template to implement the logout feature.
```

2022-06-03 16:10 UTC, tr0njavolta commented on articles/quickstart/webapp/java-spring-boot/interactive.md
> +We will create a controller to handle the incoming request. This controller will be used to render our `index.html` page. When the user is authenticated, we will setup the attributes user's profile i
```suggestion
Create a controller to handle the incoming request. This controller renders the `index.html` page. When the user authenticates, the application retrieves the users's profile information attributes to render the page.
```

2022-06-03 16:10 UTC, tr0njavolta commented on articles/quickstart/webapp/java-spring-boot/interactive.md
> +When you click the login link, verify that your application redirects you to the [Auth0 Universal Login](https://auth0.com/universal-login) page and that you can now log in or sign up using a usernam
```suggestion
When you click the login link, verify the application redirects you to the [Auth0 Universal Login](https://auth0.com/universal-login) page and that you can now log in or sign up using a username and password or a social provider.
```

2022-06-03 16:10 UTC, tr0njavolta commented on articles/quickstart/webapp/java-spring-boot/interactive.md
> +* you added the login link to redirect to `/oauth2/authorization/auth0`
```suggestion
If your application did not allow login or signup:
* Verify you configured the correct Callback URL
* Verify you added the login link to redirect to `/oauth2/authorization/auth0`
```

2022-06-03 16:10 UTC, tr0njavolta commented on articles/quickstart/webapp/java-spring-boot/interactive.md
> +Now that users can log into your application, they need [a way to log out](https://auth0.com/docs/logout/guides/logout-auth0). By default, when logout is enabled, Spring Security will log the user ou
```suggestion
Now that users can log into your application, they need [a way to log out](https://auth0.com/docs/logout/guides/logout-auth0). By default, Spring Security logs user out of your application and clears the session when you enable logout. To enable successful Auth0 logout, extend the `SecurityContextLogoutHandler` class to redirect users to your [Auth0 logout endpoint](https://auth0.com/docs/api/authentication?javascript#logout) (`https://${account.namespace}/v2/logout`) and then immediately redirect them to your application.
```

2022-06-03 16:10 UTC, tr0njavolta commented on articles/quickstart/webapp/java-spring-boot/interactive.md
> +Next, you need to update your implementation of `WebSecurityConfigurerAdapter` to register your logout handler and specify the request path that should trigger logout (`/logout` in the example below)
```suggestion
Next, update your implementation of `WebSecurityConfigurerAdapter` to register your logout handler and specify the request path that should trigger logout (`/logout` in the example below).
```

2022-06-03 16:10 UTC, tr0njavolta commented on articles/quickstart/webapp/java-spring-boot/interactive.md
> +You can remove the `SecurityConfig.java` and replace it with `SecurityConfigWithLogout.java` or just update the contents from the one file to another.
```suggestion
You can remove the `SecurityConfig.java` and replace it with `SecurityConfigWithLogout.java` or update the contents from the one file to another.
```

2022-06-03 16:10 UTC, tr0njavolta commented on articles/quickstart/webapp/java-spring-boot/interactive.md
> +* you added the Logout link to redirect to `/logout`
```suggestion
If your application did not allow logout:
* Verify you configured the correct logout URL
* Verify you added the logout link to redirect to `/logout`
```

2022-06-03 16:10 UTC, tr0njavolta commented on articles/quickstart/webapp/java-spring-boot/interactive.md
> +# Add Login to your Spring Webapp
```suggestion
# Add login to your Spring Webapp
```

2022-06-06 10:32 UTC, frederikprijck requested changes

2022-06-06 10:32 UTC, frederikprijck commented on articles/quickstart/webapp/java-spring-boot/interactive.md
> +title: Add Login to your Spring Webapp
```suggestion
Add login to your Spring Webapp
```

2022-06-06 10:36 UTC, frederikprijck approved these changes

2022-06-06 16:14 UTC, tr0njavolta approved these changes

2022-06-06 16:58 UTC, merged