[SDK-3828] update ionic react guide for react v2 ga
auth0/docs pull request #10207
Opened 2023-01-19 13:23 UTC by ewanharris

Updates the ionic + react quickstart for the upcoming v2 of react

2023-01-19 13:27 UTC, frederikprijck requested changes

2023-01-19 13:27 UTC, frederikprijck commented on articles/quickstart/native/ionic-react/01-login.md
> +    });
```suggestion
    await logout({
      logoutParams: {
        returnTo: logoutUri,
      },
      async openUrl(url) {
         // Redirect using Capacitor's Browser plugin
        await Browser.open({
          url,
          windowName: "_self"
        });
      }
    });
```

2023-01-19 13:27 UTC, frederikprijck commented on articles/quickstart/native/ionic-react/files/logout-button.md
> +    });
```suggestion
    await logout({
      logoutParams: {
        returnTo: logoutUri
      },
      async openUrl(url) {
         // Redirect using Capacitor's Browser plugin
        await Browser.open({
          url,
          windowName: "_self"
        });
      }
    });
```

2023-01-19 13:31 UTC, frederikprijck submitted a review, later dismissed

2023-01-19 13:38 UTC, ewanharris commented on articles/quickstart/native/ionic-react/interactive.md
> +The `loginWithRedirect` function tells the SDK to initiaze the login flow, using the `Browser.open` function to open the login URL with the platform's system browser component by setting the `openUrl
```suggestion
The `loginWithRedirect` function tells the SDK to initiate the login flow, using the `Browser.open` function to open the login URL with the platform's system browser component by setting the `openUrl` parameter. This provides a way for your user to log in to your application. Users redirect to the login page at Auth0 and do not receive any errors.
```

2023-01-19 13:53 UTC, frederikprijck requested changes

2023-01-19 13:53 UTC, frederikprijck commented on articles/quickstart/native/ionic-react/files/logout-button.md
> +    });
GitHub suggestion went wrong apparantly.

2023-01-23 12:30 UTC, frederikprijck approved these changes

2023-01-23 14:34 UTC, merged