[SDK-3913] Move react beta quickstart to GA
auth0/docs pull request #10206
Opened 2023-01-18 17:44 UTC by ewanharris

Remove the beta react QS and updates the GA content to be ready for 2.0.0 release

2023-01-18 20:02 UTC, frederikprijck requested changes

2023-01-18 20:02 UTC, frederikprijck commented on articles/quickstart/spa/react/01-login.md
> +- `authorizationParams.redirectUri`: The URL to where you'd like to redirect your users after they authenticate with Auth0.
```suggestion
- `authorizationParams.redirect_uri`: The URL to where you'd like to redirect your users after they authenticate with Auth0.
```

2023-01-18 20:02 UTC, frederikprijck commented on articles/quickstart/spa/react/01-login.md
> +Once that's complete, verify that Auth0 redirects you to your application using the value of the `authorizationParams.redirectUri` that you used to configure the `Auth0Provider`.
```suggestion
Once that's complete, verify that Auth0 redirects you to your application using the value of the `authorizationParams.redirect_uri` that you used to configure the `Auth0Provider`.
```

2023-01-18 20:02 UTC, frederikprijck commented on articles/quickstart/spa/react/02-calling-an-api.md
> +      redirectUri: window.location.origin,
```suggestion
      redirect_uri: window.location.origin,
```

2023-01-18 20:02 UTC, frederikprijck commented on articles/quickstart/spa/react/interactive.md
> +- `authorizationParams.redirectUri`: The URL in your application that you would like Auth0 to redirect users to after they have authenticated. This corresponds to the callback URL you set up earlier
```suggestion
- `authorizationParams.redirect_uri`: The URL in your application that you would like Auth0 to redirect users to after they have authenticated. This corresponds to the callback URL you set up earlier in this quickstart. You can also find this value in the Auth0 Dashboard under your Application's Settings in the Callback URLs field. Make sure what you enter in your code matches what you set up earlier or your users will see an error.
```

2023-01-18 20:02 UTC, frederikprijck commented on articles/quickstart/spa/react/interactive.md
> +* Auth0 redirects you to your application using the value of the `authorizationParams.redirectUri` you used to configure the `Auth0Provider`
```suggestion
* Auth0 redirects you to your application using the value of the `authorizationParams.redirect_uri` you used to configure the `Auth0Provider`
```

2023-01-18 20:02 UTC, frederikprijck commented on articles/quickstart/spa/react/interactive.md
> +* you configured the correct `authorizationParams.redirectUri`
```suggestion
* you configured the correct `authorizationParams.redirect_uri`
```

2023-01-18 21:39 UTC, ewanharris commented on articles/quickstart/spa/react/01-login.md
> +- `authorizationParams.redirectUri`: The URL to where you'd like to redirect your users after they authenticate with Auth0.
Doh, thanks for the catch!

2023-01-19 13:35 UTC, frederikprijck approved these changes

2023-01-19 13:48 UTC, merged