Update _get-token.md
auth0/docs pull request #10307
Opened 2023-09-25 17:58 UTC by nick-gagliardi

Fixed incorrect response codes

2023-09-25 18:03 UTC, avanscoy approved these changes, later dismissed

2023-09-26 16:08 UTC, avanscoy submitted a review, later dismissed

2023-09-26 16:15 UTC, frederikprijck requested changes

2023-09-26 16:15 UTC, frederikprijck commented on articles/api/authentication/api-authz/_get-token.md
> +HTTP/1.1 403 BAD REQUEST
403 isnt bad request, should we update that as well ?

2023-09-26 16:15 UTC, frederikprijck commented on articles/api/authentication/api-authz/_get-token.md
> +HTTP/1.1 429 BAD REQUEST
429 isn't bad request, should we update as well ?

2023-09-26 16:15 UTC, frederikprijck commented on articles/api/authentication/api-authz/_get-token.md
> +HTTP/1.1 403 BAD REQUEST
403 isn't bad request, should we update that as well ?

2023-09-27 14:01 UTC, avanscoy approved these changes

2023-09-27 15:06 UTC, frederikprijck approved these changes

2023-09-27 15:55 UTC, merged