Add quickstart for MAUI
auth0/docs pull request #10328
Opened 2023-11-06 14:12 UTC by frederikprijck

Adds a quickstart for MAUI

2023-11-06 16:23 UTC, frederikprijck commented on articles/quickstart/native/maui/01-login.md
> +dotnet add Auth0.OidcClient.MAUI --prerelease
```suggestion
dotnet add package Auth0.OidcClient.MAUI --prerelease
```

2023-11-06 16:23 UTC, frederikprijck commented on articles/quickstart/native/maui/interactive.md
> +dotnet add Auth0.OidcClient.MAUI --prerelease
```suggestion
dotnet add package Auth0.OidcClient.MAUI --prerelease
```

2023-11-14 02:18 UTC, evansims requested changes
Looks great! Suggested a few minor typo fixes and readability tweaks.

2023-11-14 02:18 UTC, evansims commented on articles/quickstart/native/maui/01-login.md
> +The MAUI SDK supports Android, iOS, macOS and Windows. For platform specific configuration, continue reading.
```suggestion
The MAUI SDK supports Android, iOS, macOS, and Windows. Continue reading for platform-specific configuration.
```

2023-11-14 02:18 UTC, evansims commented on articles/quickstart/native/maui/01-login.md
> +In order to use the SDK with Android and Windows, you need some platform specific configuration.
```suggestion
You need some platform-specific configuration to use the SDK with Android and Windows.
```

2023-11-14 02:18 UTC, evansims commented on articles/quickstart/native/maui/01-login.md
> +- Call `Activator.Default.CheckRedirectionActivation()` in the Windows specific App.xaml.cs file.
```suggestion
- Call `Activator.Default.CheckRedirectionActivation()` in the Windows-specific `App.xaml.cs` file.
```

2023-11-14 02:18 UTC, evansims commented on articles/quickstart/native/maui/01-login.md
> +To make sure it can properly reactivate your application after being redirected back go Auth0, you need to do two things:
```suggestion
To make sure it can properly reactivate your application after being redirected back to Auth0, you need to do two things:
```

2023-11-14 02:18 UTC, evansims commented on articles/quickstart/native/maui/interactive.md
> +The MAUI SDK supports Android, iOS, macOS and Windows. For platform specific configuration, continue reading.
```suggestion
The MAUI SDK supports Android, iOS, macOS, and Windows. Continue reading for platform-specific configuration.
```

2023-11-14 02:18 UTC, evansims commented on articles/quickstart/native/maui/interactive.md
> +In order to use the SDK with Android and Windows, you need some platform specific configuration.
```suggestion
You need some platform-specific configuration to use the SDK with Android and Windows.
```

2023-11-14 02:18 UTC, evansims commented on articles/quickstart/native/maui/interactive.md
> +To make sure it can properly reactivate your application after being redirected back go Auth0, you need to do two things:
```suggestion
To make sure it can properly reactivate your application after being redirected back to Auth0, you need to do two things:
```

2023-11-14 02:18 UTC, evansims commented on articles/quickstart/native/maui/interactive.md
> +- Call `Activator.Default.CheckRedirectionActivation()` in the Windows specific App.xaml.cs file.
```suggestion
- Call `Activator.Default.CheckRedirectionActivation()` in the Windows-specific `App.xaml.cs` file.
```

2023-11-14 08:21 UTC, frederikprijck commented
Thanks! I updated the PR to include all the improvements.

2023-11-14 13:12 UTC, evansims approved these changes

2024-01-04 09:25 UTC, merged