[Do Not Merge] WordPress docs updates
auth0/docs pull request #2313
Opened 2016-09-14 20:02 UTC by khorne3

2016-09-14 20:02 UTC, auth0build commented
Can one of the admins verify this patch?

2016-09-15 08:00 UTC, mpaktiti commented on articles/cms/wordpress/configuration.md
> +1. Log in to the [Auth0 dashboard](http://${manage_url}). (If you don't already have an Auth0 account, you can [create one](https://auth0.com).
Hey @khorne3 I think the `http://` should be removed from `(http://${manage_url})`. In the heroku preview at least it is displayed as `http//https://manage.auth0.com`.

2016-09-15 08:04 UTC, mpaktiti commented on articles/cms/wordpress/configuration.md
> +Enable the supported social identity providers you want to allow users to login with. You can configure your own app keys and settings for these connections in the [Auth0 Dashboard](http://${manage_u
@khorne3 Same thing here, the default value of `${manage_url}` should be `https://manage.auth0.com` so the `http://` is not needed. The URL at the live doc navigated at `https://manage.auth0.com/#/connections/social`.

2016-09-15 08:07 UTC, mpaktiti commented on articles/cms/wordpress/installation.md
> +![](/media/articles/cms/wordpress/upload-and-install.png)
@khorne3 Can you add a couple of words at the images alternate text in this doc?

2016-09-15 08:09 UTC, mpaktiti requested changes
Hey, I left a couple of comments on links and missing alt text, when you have some time take a look. Thanks!

2016-09-15 12:51 UTC, khorne3 commented
@mpaktiti Fixed. I'm unsure why GitHub doesn't think I've made the requested changes and marked your suggestions as outdated, though.

2016-09-15 14:54 UTC, mpaktiti approved these changes

2016-09-15 14:54 UTC, merged