Last of image resizing in media/articles and media/auth0-catalog
auth0/docs pull request #2315
Opened 2016-09-14 23:21 UTC by angelaLazar

2016-09-14 23:21 UTC, auth0build commented
Can one of the admins verify this patch?

2016-09-15 08:15 UTC, mpaktiti requested changes
Hey @angelaLazar , I have a couple of comments for fixes. Thanks!

`media/articles/native-platforms/windows-uwp-csharp/lock-widget-screenshot.png`: Shouldn't we crop the bar at the bottom of the image?

`media/articles/overview/overview.png`: I think this one can get a bit smaller. The 900px max width is for the full browser screenshots. The rest should be kept at 750px max. Same for:
- `media/articles/saml/identity-providers/onelogin/user-with-mappings.png`
- `media/articles/saml/identity-providers/onelogin/user-without-mappings.png`

2016-09-15 19:19 UTC, angelaLazar commented
@mpaktiti Thanks, I added your suggestions

2016-09-16 10:31 UTC, mpaktiti approved these changes

2016-09-16 10:31 UTC, merged