List supported algorithms for XML-DSig
auth0/docs pull request #2325
Opened 2016-09-15 21:59 UTC by nicosabena

Useful information when debugging SAML

2016-09-15 21:59 UTC, auth0build commented
Can one of the admins verify this patch?

2016-09-16 11:55 UTC, mpaktiti commented on articles/saml/saml-sp-generic.md
> +# Additional information
This would look better without the h1 header. Just the `## Supported algorithms for signatures` looks fine, so can you please remove this line?

2016-09-16 11:59 UTC, mpaktiti commented on articles/saml/saml-sp-generic.md
> +  * 'http://www.w3.org/2001/10/xml-exc-c14n#'
The URLs should be like this: 
`[Canonical XML (XML-C14N)](http://www.w3.org/2001/10/xml-exc-c14n#)`
`[Canonical XML (XML-C14N) #WithComments](http://www.w3.org/2001/10/xml-exc-c14n#WithComments)`
and so forth

2016-09-16 12:00 UTC, mpaktiti requested changes
Hello @nicosabena ! We need some updates on this, can you please have a look at the comments? Thanks!

2016-09-16 12:10 UTC, nicosabena commented on articles/saml/saml-sp-generic.md
> +  * 'http://www.w3.org/2001/10/xml-exc-c14n#'
These are not really URLs, they are just URIs to identify an algorithm.
They are used directly in XML, like this:

    <CanonicalizationMethod algorithm='http://www.w3.org/2000/09/xmldsig#enveloped-signature' ...

so it doesn't really make sense to format them as URL.

2016-09-16 12:11 UTC, nicosabena commented on articles/saml/saml-sp-generic.md
> +# Additional information
ok.

2016-09-16 13:51 UTC, mpaktiti commented on articles/saml/saml-sp-generic.md
> +  * 'http://www.w3.org/2001/10/xml-exc-c14n#'
ok then!

2016-09-16 13:51 UTC, mpaktiti approved these changes

2016-09-16 13:51 UTC, merged