New Ionic docs
auth0/docs pull request #2330
Opened 2016-09-16 15:58 UTC by lobo

2016-09-16 15:58 UTC, auth0build commented
Can one of the admins verify this patch?

2016-09-19 08:02 UTC, mpaktiti commented on articles/native-platforms/ionic/04-linking-accounts.md
> +To view a user's identities, access the [Users](${uiURL}/#/users) page on the Auth0 dashboard, select a user, and scroll down to `identities`.
@lobo `uiURL` is not used any longer, so i throws `ReferenceError: uiURL is not defined`. Replace it with `manage_url`.

2016-09-19 08:06 UTC, mpaktiti commented on articles/native-platforms/ionic/05-rules.md
> +<%= include('../../_includes/server-platform/_rules-introduction') %>
@lobo Throws `Error: Could not find include ../../_includes/server-platform/_rules-introduction`. There is no such directory.

2016-09-19 08:06 UTC, mpaktiti commented on articles/native-platforms/ionic/05-rules.md
> +<%= include('../../_includes/server-platform/_rules-create-section') %>
@lobo There is no such directory.

2016-09-19 08:06 UTC, mpaktiti commented on articles/native-platforms/ionic/05-rules.md
> +<%= include('../../_includes/server-platform/_rules-test-result-intro', { profilelink: '/docs/quickstart/native/ionic/03-user-profile' }) %>
@lobo There is no such directory.

2016-09-19 08:07 UTC, mpaktiti commented on articles/native-platforms/ionic/06-authorization.md
> +<%= include('../_includes/_authorization-introduction', { ruleslink: '/docs/quickstart/native/ionic/05-rules' }) %>
@lobo Throws `Error: Could not find include ../_includes/_authorization-introduction`. There is no such directory.

2016-09-19 08:07 UTC, mpaktiti commented on articles/native-platforms/ionic/06-authorization.md
> +<%= include('../_includes/_authorization-create-rule') %>_
@lobo There is no such directory.

2016-09-19 08:08 UTC, mpaktiti commented on articles/native-platforms/ionic/08-mfa.md
> +<%= include('../_includes/_mfa-introduction') %>
@lobo Throws `Error: Could not find include ../_includes/_mfa-introduction`. There is no such directory.

2016-09-19 08:08 UTC, mpaktiti commented on articles/native-platforms/ionic/08-mfa.md
> +<%= include('../_includes/_mfa-enable') %>
@lobo There is no such directory.

2016-09-19 08:09 UTC, mpaktiti commented on articles/native-platforms/ionic/08-mfa.md
> +<%= include('../_includes/_mfa-login', { loginlink: '/docs/quickstart/native/ionic/01-login' }) %>
@lobo There is no such directory.

2016-09-19 08:11 UTC, mpaktiti requested changes
Hey @lobo ! Most errors are due to missing files. Please review my comments, apply any changes needed and let me know if you need anything else. Keep in mind that most of the times heroku is not very useful at troubleshooting, I find deploying the site locally much more helpful.

2016-09-19 11:41 UTC, closed without merging