[DO NOT MERGE] Add instructions for checking on allowed modules
auth0/docs pull request #2395
Opened 2016-09-28 17:58 UTC by khorne3

2016-09-28 17:58 UTC, auth0build commented
Can one of the admins verify this patch?

2016-11-09 14:33 UTC, tehsis requested changes

2016-11-09 14:33 UTC, tehsis commented on articles/appliance/webtasks.md
> +curl https://webtask.<a0url>.com=http://example.com/webtask.js
this needs to send an authorization token to it and also use the webtask_url paremeter.
I would recommend to go with wt-cli which is going to be easier to explain.

Instructions to use the CLI are in https://<manage_url>/#/account/webtasks

2016-11-15 16:34 UTC, mpaktiti commented on articles/appliance/webtasks.md
> +wt init --container "YOUR_TENANT_NAME" --url "https://sandbox.it.auth0.com" --token "eyJhbGci..." -p "a``YOUR_TENANT_NAME-default"
@tehsis Not sure if I "translated" this right (I replaced `adcasdfa` with `YOUR_TENANT_NAME`).

Also, I was wondering whether `https://sandbox.it.auth0.com` stays the same for non-US customers. I've seen it as `https://sandbox-eu.it.auth0.com` for EU tenants but I'm not sure if it applies in this case.

2016-11-15 16:35 UTC, mpaktiti commented on articles/appliance/webtasks.md
> +This is the very first command you will run once you install `wt-cli`. It is used to create and update webtask profiles. It also provisions a webtask token if you don't have one already. Each webtask
@tehsis Does this process (`You will receive a verification code...`) stays the same for appliance users or should I remove this?

2016-11-18 10:24 UTC, tehsis requested changes

2016-11-18 10:24 UTC, tehsis commented on articles/appliance/webtasks.md
> +wt init --container "YOUR_TENANT_NAME" --url "https://sandbox.it.auth0.com" --token "eyJhbGci..." -p "a``YOUR_TENANT_NAME-default"
That URL depends on the appliance installation, it should be WEBTASK_URL

2016-11-18 10:24 UTC, tehsis commented on articles/appliance/webtasks.md
> +This is the very first command you will run once you install `wt-cli`. It is used to create and update webtask profiles. It also provisions a webtask token if you don't have one already. Each webtask
No, appliances customers won't do this

2016-11-18 10:24 UTC, tehsis commented on articles/appliance/webtasks.md
> +This is the very first command you will run once you install `wt-cli`. It is used to create and update webtask profiles. It also provisions a webtask token if you don't have one already. Each webtask
You still need to configure the profile (with a name, container and token) this is done by following the instructions on the webtask section on the account settings

2016-11-18 11:54 UTC, merged