[DO NOT MERGE] Add new plan details to sprint.md
auth0/docs pull request #2514
Opened 2016-10-12 23:39 UTC by ClaytonHeath

2016-10-12 23:39 UTC, auth0build commented
Can one of the admins verify this patch?

2016-10-28 19:45 UTC, ntotten requested changes

2016-10-28 19:45 UTC, ntotten commented on articles/onboarding/sprint.md
> +The table below outlines the different benefits delivered by the Customer Success team based on the [support plan](https://auth0.com/docs/support) included with your subscription.
no absolute links to docs. `[support plan](/support)`

2016-10-28 19:45 UTC, ntotten commented on articles/onboarding/sprint.md
> +* Have your subscription account correctly provisioned and setup in our systems (including the [appliance deployment project](https://auth0.com/docs/onboarding/appliance-sprint) in the case of on-pre
No absolute links `[appliance deployment project](/onboarding/appliance-sprint)`

2016-10-28 19:50 UTC, ntotten approved these changes

2016-10-28 19:50 UTC, merged