[DO NOT MERGE] Lock for Android docs v2 updates
auth0/docs pull request #2593
Opened 2016-10-20 17:12 UTC by jeffreylees

2016-10-20 17:12 UTC, auth0build commented
Can one of the admins verify this patch?

2016-10-27 20:24 UTC, hzalaz requested changes

2016-10-27 20:24 UTC, hzalaz commented on articles/libraries/lock-android/index.md
> +If you intend to create your own API and just call Auth0 API via the `com.auth0.android:auth0:1.1.0`, the minimum required API level is also 15+.
`create your own UI` instead of `create your own API`

2016-10-27 20:24 UTC, hzalaz commented on articles/libraries/lock-android/index.md
> +If you intend to create your own API and just call Auth0 API via the `com.auth0.android:auth0:1.1.0`, the minimum required API level is also 15+.
Also, let's mention https://github.com/auth0/Auth0.Android lib instead (we should probably aim to have a custom UI guide)

2016-10-27 20:24 UTC, hzalaz commented on articles/libraries/lock-android/index.md
> +_You can check for the latest version on the repository [Releases](https://github.com/auth0/Lock.Android/releases) tab or in [Maven](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22lock%22%20g%3A%2
Let's add JCenter too, in Android is more common to use it since it's the default repository for gradle

2016-10-28 00:45 UTC, hzalaz approved these changes

2016-10-28 14:39 UTC, merged