[DO NOT MERGE] Authz swift quickstart
auth0/docs pull request #2594
Opened 2016-10-21 04:25 UTC by jhiner

Submitted for comment, this adds the API Authorization quickstart tutorial for iOS Swift.

2016-10-21 04:25 UTC, auth0build commented
Can one of the admins verify this patch?

2016-10-21 04:26 UTC, jhiner commented
cc @cabralmartin @hzalaz

2016-10-21 21:08 UTC, hzalaz requested changes
Also let's aim for Swift 3

2016-10-21 21:08 UTC, hzalaz commented on articles/native-platforms/ios-swift/_includes/_api_authz.md
> +pod "Auth0", :git => 'https://github.com/auth0/Auth0.swift.git'
Let's aim for Swift 3.0 for this so we can use:
```
pod 'Auth0', '~> 1.0'
```

2016-10-21 21:08 UTC, hzalaz commented on articles/native-platforms/ios-swift/_includes/_api_authz.md
> +pod "Auth0", :git => 'https://github.com/auth0/Auth0.swift.git'
Also we can add  instructions about Carthage:

Which is something like :

Add the following to your Cartfile

```
github "auth0/Auth0.swift" ~> 1.0
```

run `carthage bootstrap --platform ios` and add `Auth0.framework` to your application.

2016-10-21 21:08 UTC, hzalaz commented on articles/native-platforms/ios-swift/_includes/_api_authz.md
> +        "response_type":"code",
No need for specify `response_type`, the default is `code` and uses PKCE

2016-10-21 21:08 UTC, hzalaz commented on articles/native-platforms/ios-swift/_includes/_api_authz.md
> +@IBAction func StartAuthentication( sender: AnyObject? ) {
camel case starting with lowercase for methods name, no spaces after `(` and before `)`

2016-10-21 21:08 UTC, hzalaz commented on articles/native-platforms/ios-swift/_includes/_api_authz.md
> +    let params: [String: String] = [
Since all of them are `String` lose the type

2016-10-21 21:08 UTC, hzalaz commented on articles/native-platforms/ios-swift/_includes/_api_authz.md
> +        .start(authCallback);
I'd rather have this

```swift
Auth0
    .webAuth()
    .parameters(params)
    .start { result in
     // add callback code here
    }
```

2016-10-24 18:38 UTC, jhiner commented on articles/native-platforms/ios-swift/_includes/_api_authz.md
> +pod "Auth0", :git => 'https://github.com/auth0/Auth0.swift.git'
Fixed.

2016-10-24 18:38 UTC, jhiner commented on articles/native-platforms/ios-swift/_includes/_api_authz.md
> +@IBAction func StartAuthentication( sender: AnyObject? ) {
Fixed.

2016-10-24 18:38 UTC, jhiner commented on articles/native-platforms/ios-swift/_includes/_api_authz.md
> +    let params: [String: String] = [
Fixed.

2016-10-24 18:38 UTC, jhiner commented on articles/native-platforms/ios-swift/_includes/_api_authz.md
> +        .start(authCallback);
Fixed.

2016-10-24 18:39 UTC, jhiner commented on articles/native-platforms/ios-swift/_includes/_api_authz.md
> +        "response_type":"code",
Fixed.

2016-10-24 19:22 UTC, hzalaz requested changes

2016-10-24 19:22 UTC, hzalaz commented on articles/native-platforms/ios-swift/_includes/_api_authz.md
> +github "auth0/Auth0.swift" "1.0"
Let's use either `"1.0..0"` or `~> 1.0` since `"1.0"` will cause issues

2016-10-24 19:22 UTC, hzalaz commented on articles/native-platforms/ios-swift/_includes/_api_authz.md
> +    .start( { result in
Just a styley thing, you can lose the `()`

2016-10-24 19:22 UTC, hzalaz commented on articles/native-platforms/ios-swift/_includes/_api_authz.md
> +  "authentication": "Bearer {ACCESS_TOKEN}"
I think is `Authorization` the header name

2016-10-24 19:22 UTC, hzalaz commented on articles/native-platforms/ios-swift/_includes/_api_authz.md
> +```swift
This is the swift 3 version of this snippet

```swift
let accessToken = "{ACCESS_TOKEN}"
let headers = [
    "Content-Type": "application/json",
    "Authorization": "Bearer \(accessToken)"
]

let apiUrl = NSURL(string: "https://someapi.com/api")!
var request = URLRequest(url: apiUrl, cachePolicy: .useProtocolCachePolicy, timeoutInterval: 10.0)
request.httpMethod = "POST"
request.allHTTPHeaderFields = headers

let session = URLSession.shared
let dataTask = session.dataTask(with: request) { data, response, error in
    guard error != nil else { return print(error) }
    guard let httpResponse = response as? HTTPURLResponse else { return }
    print(httpResponse)
}
```

2016-10-24 19:29 UTC, jhiner commented on articles/native-platforms/ios-swift/_includes/_api_authz.md
> +  "authentication": "Bearer {ACCESS_TOKEN}"
You are right, it is. I actually copied this snippet from an existing doc which auto-generates the different languages based on a HAR. So I will fix that separately (so it is correct in other docs).  Example: https://auth0.com/docs/api-auth/tutorials/authorization-code-grant#using-the-access-token

2016-10-24 19:37 UTC, jhiner commented on articles/native-platforms/ios-swift/_includes/_api_authz.md
> +    .start( { result in
Fixed

2016-10-24 19:37 UTC, jhiner commented on articles/native-platforms/ios-swift/_includes/_api_authz.md
> +github "auth0/Auth0.swift" "1.0"
Fixed.

2016-10-24 19:39 UTC, hzalaz approved these changes

2016-10-25 19:26 UTC, merged