[DO NOT MERGE] Authz nodejs quickstart
auth0/docs pull request #2595
Opened 2016-10-21 04:28 UTC by jhiner

Submitted for comment, this adds the API Authorization quickstart tutorial for NodeJS.

2016-10-21 04:28 UTC, auth0build commented
Can one of the admins verify this patch?

2016-10-21 04:28 UTC, jhiner commented
cc @cabralmartin

2016-10-24 15:08 UTC, cabralmartin commented
@jhiner reviewed. left small remarks.

2016-10-24 15:08 UTC, cabralmartin requested changes

2016-10-24 15:08 UTC, cabralmartin commented on articles/server-platforms/nodejs/11-api-authorization.md
> +<%= include('../../api-auth/_preview-warning') %>
replace with `_region-support` warning

2016-10-24 15:08 UTC, cabralmartin commented on articles/server-platforms/nodejs/11-api-authorization.md
> +<%= include('../../_includes/_new_app') %>
app type should be regular web app

2016-10-24 15:08 UTC, cabralmartin commented on articles/server-platforms/nodejs/11-api-authorization.md
> +Be sure to register the URL of your app in the Allowed Callback URLs in your Application Settings.
replace app settings with `Client Settings`

2016-10-24 15:08 UTC, cabralmartin commented on articles/server-platforms/nodejs/_includes/_api_authz.md
> +The `audience` parameter should contain your API identifier from the Dashboard. If you don't send this, the runtime will take it from the tenant settings (`tenant.default_audience` or you can set it
`The scope parameter should include one or more` -> `The scope parameter may include one or more`

2016-10-24 15:08 UTC, cabralmartin commented on articles/server-platforms/nodejs/_includes/_api_authz.md
> +The Resource Server (API) should be configured to verify the JWT and any claims contained within it. Because the Resource Server is utilizing the RS256 signature method, tokens are signed using Auth0
maybe `More information can be found in the Quickstarts document for your API` ?

2016-10-24 18:57 UTC, jhiner commented on articles/server-platforms/nodejs/_includes/_api_authz.md
> +The Resource Server (API) should be configured to verify the JWT and any claims contained within it. Because the Resource Server is utilizing the RS256 signature method, tokens are signed using Auth0
Yeah we could link to this: https://auth0.com/docs/quickstart/backend

2016-10-24 18:57 UTC, jhiner commented on articles/server-platforms/nodejs/_includes/_api_authz.md
> +The `audience` parameter should contain your API identifier from the Dashboard. If you don't send this, the runtime will take it from the tenant settings (`tenant.default_audience` or you can set it
Fixed.

2016-10-24 18:58 UTC, jhiner commented on articles/server-platforms/nodejs/11-api-authorization.md
> +Be sure to register the URL of your app in the Allowed Callback URLs in your Application Settings.
Fixed

2016-10-24 20:00 UTC, jhiner commented
@cabralmartin Should be good to go, pending any additional feedback.

2016-10-25 19:25 UTC, merged