Pipeline clients
auth0/docs pull request #2615
Opened 2016-10-24 11:47 UTC by mpaktiti

Fixes https://github.com/auth0/docs/issues/2402

2016-10-24 11:47 UTC, auth0build commented
Can one of the admins verify this patch?

2016-10-25 18:18 UTC, cabralmartin requested changes

2016-10-25 18:18 UTC, cabralmartin commented on articles/clients/index.md
> +An Auth0 **client** maps to your application and allows to use Auth0 for authentication. The term *client* does not imply any particular implementation characteristics. Your application can be a nati
Not sure if we should scope to OAuth only since clients may operate in ways out of that spec.

2016-10-25 18:18 UTC, cabralmartin commented on articles/clients/index.md
> +An Auth0 **client** maps to your application and allows to use Auth0 for authentication. The term *client* does not imply any particular implementation characteristics. Your application can be a nati
`protected resource requests on behalf of the resource owner and with its authorization` speaks of a client trying to reach an API. While we support this authZ scenario, it sounds like clients are no good for authN only, which would be incorrect.

2016-10-25 18:18 UTC, cabralmartin commented on articles/clients/index.md
> +- **Non Interactive Clients**: Used for server to server applications like CLIs, daemons or services running on your backend. Typically you would use this option if you have a service that requires a
I would remove this piece `and you want it to request access tokens in order to do so.`

2016-10-25 18:18 UTC, cabralmartin commented on articles/clients/index.md
> +- [Quick Start](${manage_url}/#/clients/${account.clientId}/quickstart): Lists all available Quick Starts, filtered by your client's type.
is it customary to use this type of links? these will become broken links for non authenticated users and not sure which client will use for the rest.

2016-10-25 18:18 UTC, cabralmartin commented on articles/clients/index.md
> +- **Client Secret**: A base64 encoded string used to sign and validate tokens for authentication flows and to gain access to select Auth0 API endpoints. By default, the value is hidden, so check the
`sign and validate tokens` -> `sign and validate id_tokens`.

2016-10-25 18:18 UTC, cabralmartin commented on articles/clients/index.md
> +- **Client Secret**: A base64 encoded string used to sign and validate tokens for authentication flows and to gain access to select Auth0 API endpoints. By default, the value is hidden, so check the
we should add a note about being super careful about safe keeping the secret

2016-10-25 18:18 UTC, cabralmartin commented on articles/clients/index.md
> +- **First Party Client**: When a First Party client requests authorized against an API with the **Allow Skipping User Consent** flag set, the User Consent dialog will not be shown to the final user.
`client requests authorized against` -> `client requests authorized access against`

2016-10-25 18:18 UTC, cabralmartin commented on articles/clients/index.md
> +- **JWT Expiration (seconds)**: The amount of time (in seconds) before the Auth0 [JWT](/jwt) expires. The default value is `36000`, which maps to 10 hours.
`before the Auth0 id_token expires`

2016-10-25 18:18 UTC, cabralmartin commented on articles/clients/index.md
> +The client type should match your application:
should we extract this as a separate section? (i.e. # Client Types) wdyt? I would also place it before speaking about how to create a client.

2016-10-25 18:18 UTC, cabralmartin commented on articles/clients/index.md
> +Click on the [Settings](${manage_url}/#/clients/${account.clientId}/settings) tab of your client to review the available settings:
Maybe this would be better presented as a separated sub section (i.e. ## Client Settings) wdyt?

2016-10-25 18:18 UTC, cabralmartin commented on articles/clients/index.md
> +::: panel-info Auth0 Rules
Is this necessary in this document?

2016-10-25 18:18 UTC, cabralmartin commented on articles/clients/index.md
> +## Sample Clients
would it make sense to remove these samples from here and direct the user to the [Architecture Scenarios doc](https://auth0.com/docs/architecture-scenarios)? that way we can focus the effort on maintaining scenarios in a single place. wdyt?

2016-10-25 18:18 UTC, cabralmartin commented on articles/clients/index.md
> +## Auditing
should we leave this here? maybe we can point to a much detailed doc where we discuss logs? wdyt?

2016-10-26 07:31 UTC, mpaktiti commented on articles/clients/index.md
> +An Auth0 **client** maps to your application and allows to use Auth0 for authentication. The term *client* does not imply any particular implementation characteristics. Your application can be a nati
Removed the last sentence.

2016-10-26 07:42 UTC, mpaktiti commented on articles/clients/index.md
> +- [Quick Start](${manage_url}/#/clients/${account.clientId}/quickstart): Lists all available Quick Starts, filtered by your client's type.
Yes we use these variables at docs. If the user is not logged in then he is redirected to Lock to login. You can try it from incognito and see the experience. When you login you get the Clients page (there is an error displayed for some seconds at the top of the page but then it goes away on its own).

2016-10-26 07:45 UTC, mpaktiti commented on articles/clients/index.md
> +- **Non Interactive Clients**: Used for server to server applications like CLIs, daemons or services running on your backend. Typically you would use this option if you have a service that requires a
Can you explain why? Is the statement incorrect or you don't like the syntax?

2016-10-26 07:46 UTC, mpaktiti commented on articles/clients/index.md
> +The client type should match your application:
Sure, better this way. I moved it on its own sub-paragraph, before how to configure a client.

2016-10-26 11:30 UTC, mpaktiti commented on articles/clients/index.md
> +- **Client Secret**: A base64 encoded string used to sign and validate tokens for authentication flows and to gain access to select Auth0 API endpoints. By default, the value is hidden, so check the
OK I will add the note. A question about this `sign and validate id_tokens`: this applies even if I used HS256 for my API? Isn't the secret used for HMAC algorithms? I understand that it is not recommended to use HS256 but it is feasible, no?

2016-10-26 11:54 UTC, mpaktiti commented on articles/clients/index.md
> +- **First Party Client**: When a First Party client requests authorized against an API with the **Allow Skipping User Consent** flag set, the User Consent dialog will not be shown to the final user.
Fixed 👍

2016-10-26 11:55 UTC, mpaktiti commented on articles/clients/index.md
> +- **JWT Expiration (seconds)**: The amount of time (in seconds) before the Auth0 [JWT](/jwt) expires. The default value is `36000`, which maps to 10 hours.
This isn't used for the access token as well? When does the access token expire?

2016-10-26 11:57 UTC, mpaktiti commented on articles/clients/index.md
> +::: panel-info Auth0 Rules
I think it should stay. The doc is a generic introduction into Clients and rules are important. There was a whole paragraph here, which was too much, so I removed it and added this panel instead. 

It's the same with the logging info. I can remove the content to another doc, but I should mention it in this one so if anyone is interested can easily find this information.

2016-10-26 11:58 UTC, mpaktiti commented on articles/clients/index.md
> +## Sample Clients
I agree, I don't think it serves any purpose really.

2016-10-26 12:00 UTC, mpaktiti commented on articles/clients/index.md
> +## Auditing
Agreed 👍

2016-10-26 12:50 UTC, mpaktiti commented on articles/clients/index.md
> +Click on the [Settings](${manage_url}/#/clients/${account.clientId}/settings) tab of your client to review the available settings:
Agree 👍

2016-10-26 14:20 UTC, mpaktiti commented on articles/clients/index.md
> +::: panel-info Auth0 Rules
On a second thought I removed it. It is closely related to clients but it seemed out of context.

2016-10-26 21:07 UTC, cabralmartin commented on articles/clients/index.md
> +- **Non Interactive Clients**: Used for server to server applications like CLIs, daemons or services running on your backend. Typically you would use this option if you have a service that requires a
It is correct that a NI will require to request access_tokens in order to access a secured API. But it sounds funny to me how it's phrased; it's like "if I want to access and API AND I want to request access tokens then I will select this client". Maybe talking about access tokens at this point is more of an implementation detail.

2016-10-26 21:08 UTC, cabralmartin commented on articles/clients/index.md
> +- [Quick Start](${manage_url}/#/clients/${account.clientId}/quickstart): Lists all available Quick Starts, filtered by your client's type.
I'm getting this

![image](https://cloud.githubusercontent.com/assets/1980994/19745246/41eb5c14-9ba7-11e6-86eb-2ec554f64808.png)

2016-10-26 21:12 UTC, cabralmartin commented on articles/clients/index.md
> +- **Client Secret**: A base64 encoded string used to sign and validate tokens for authentication flows and to gain access to select Auth0 API endpoints. By default, the value is hidden, so check the
This secret we see in the client settings can serve multiple purposes. One one hand, it's going to be use to sign the `id_tokens` (not `access_tokens`) when the algorithm is HS256. On the other hand, it's also "the client password" and be used on the token endpoint for executing several operations (e.g. client grant exchange, code exchange, etc).

Again, this is different from the API secret. The API secret is used for signing `access_tokens` (if using HS256).

The funny thing about client secrets is that are some client types that have no use for it (i.e. SPA / Native). Further down the line we will be removing them from the dashboard for those app types.

2016-10-26 21:12 UTC, cabralmartin commented on articles/clients/index.md
> +- **JWT Expiration (seconds)**: The amount of time (in seconds) before the Auth0 [JWT](/jwt) expires. The default value is `36000`, which maps to 10 hours.
The `access_token` lifetime is managed under the API settings. I'm thinking we could use a sub section similar to this one in the API doc where we go setting by setting. wdyt?

2016-10-26 21:14 UTC, cabralmartin commented
Addressed comments // cc @mpaktiti

2016-10-27 12:48 UTC, mpaktiti commented on articles/clients/index.md
> +- [Quick Start](${manage_url}/#/clients/${account.clientId}/quickstart): Lists all available Quick Starts, filtered by your client's type.
That's because there is a bug in the heroku review apps. There is a missing `:` so the URL is `https//manage....`. Add this manually and see how it works.

2016-10-27 13:03 UTC, mpaktiti commented on articles/clients/index.md
> +- **Client Secret**: A base64 encoded string used to sign and validate tokens for authentication flows and to gain access to select Auth0 API endpoints. By default, the value is hidden, so check the
Got it, in the API case the Global Client Secret is used for signing, not the Client one. Thanks for clarifying!

2016-10-27 13:05 UTC, mpaktiti commented on articles/clients/index.md
> +- **JWT Expiration (seconds)**: The amount of time (in seconds) before the Auth0 [JWT](/jwt) expires. The default value is `36000`, which maps to 10 hours.
Good idea, I'll make update that doc next.

2016-10-27 13:31 UTC, merged