[DO-NOT-MERGE] Authz android quickstart
auth0/docs pull request #2634
Opened 2016-10-25 19:51 UTC by jhiner

Submitted for review, this is the Android OAuth 2.0 API Quickstart.

2016-10-25 19:51 UTC, auth0build commented
Can one of the admins verify this patch?

2016-10-25 19:51 UTC, jhiner commented
cc @cabralmartin @hzalaz

2016-10-25 20:51 UTC, hzalaz requested changes

2016-10-25 20:51 UTC, hzalaz commented on articles/native-platforms/android/_includes/_api_authz.md
> +            .useCodeGrant(true)
I think this is the default so it's safe to remove it

2016-10-25 20:51 UTC, hzalaz commented on articles/native-platforms/android/_includes/_api_authz.md
> +HttpResponse<String> response = Unirest.get("https://someapi.com/api")
Mention you are using an external lib

2016-10-26 17:55 UTC, jhiner commented on articles/native-platforms/android/_includes/_api_authz.md
> +            .useCodeGrant(true)
fixed.

2016-10-26 17:55 UTC, jhiner commented on articles/native-platforms/android/_includes/_api_authz.md
> +HttpResponse<String> response = Unirest.get("https://someapi.com/api")
fixed.

2016-10-26 18:50 UTC, hzalaz approved these changes

2016-10-27 22:16 UTC, cabralmartin commented
Ship it!

2016-10-28 13:22 UTC, merged