[DO NOT MERGE] Adding documentation on hosted pages
auth0/docs pull request #2674
Opened 2016-10-31 12:38 UTC by jeffreylees

2016-10-31 12:38 UTC, auth0build commented
Can one of the admins verify this patch?

2016-10-31 16:59 UTC, ntotten commented
Make sure to update the sidebar.yml

2016-11-02 16:29 UTC, ntotten commented on articles/hosted-pages/login.md
> +https://'${account.namespace}'/login?client='${account.clientId}'
Extra quotes around ``${account.namespace}'`

2016-11-02 16:30 UTC, ntotten commented on articles/hosted-pages/password-reset.md
> +<img width="500" src="/media/articles/hosted-pages/password_reset.png" />
Shouldn't set widths. Use markdown `![](/media/articles/hosted-pages/password_reset.png)`

2016-11-03 08:01 UTC, mpaktiti requested changes
Hey @jeffreylees the doc needs some edits, please see my comments. Also, all three screenshots are larger that the specs (1260 × 1053), please downsize to 900px wide. Thanks!

2016-11-03 08:01 UTC, mpaktiti commented on articles/hosted-pages/error-pages.md
> +# Error Pages
Can you add description metadata for the doc please?

2016-11-03 08:01 UTC, mpaktiti commented on articles/hosted-pages/guardian.md
> +# Guardian Multifactor Login Page
Can you add description metadata for the doc please?

2016-11-03 08:01 UTC, mpaktiti commented on articles/hosted-pages/guardian.md
> +In your [Auth0 Dashboard](https://manage.auth0.com/#/guardian_mfa_page), you can enable your Hosted Guardian Multifactor Login Page by simply flipping the toggle switch.
Hardcoded value for the dashboard. Use the manage_url variable instead.

2016-11-03 08:01 UTC, mpaktiti commented on articles/hosted-pages/guardian.md
> +![](/media/articles/hosted-pages/guardian.png)
Missing alternate text for the image.

2016-11-03 08:01 UTC, mpaktiti commented on articles/hosted-pages/guardian.md
> +If you want to change some of the options in the Change Password Widget, you may do so _right on this page_, just make your changes and make sure to remember to hit the "save" button. The options hav
Replace `"save"` with `__Save__`.

2016-11-03 08:01 UTC, mpaktiti commented on articles/hosted-pages/index.md
> +You can customize your hosted pages from within your [Auth0 Dashboard](https://manage.auth0.com). See the following pages for specific instructions about each type of hosted page:
Replace hardcoded dashboard URL with variable

2016-11-03 08:01 UTC, mpaktiti commented on articles/hosted-pages/login.md
> +In your [Auth0 Dashboard](https://manage.auth0.com/#/login_page), you can enable your Hosted Login Page by simply flipping the toggle switch.
Replace hardcoded dashboard URL with variable

2016-11-03 08:01 UTC, mpaktiti commented on articles/hosted-pages/login.md
> +![](/media/articles/hosted-pages/login.png)
Missing alternate text for the image.

2016-11-03 08:01 UTC, mpaktiti commented on articles/hosted-pages/login.md
> +If you want to change some of the [configuration options](/libraries/lock/v10/customization) within Lock, you may do so _right on this page_, just make your changes and make sure to remember to hit t
Replace `"save"` with `__save__`

2016-11-03 08:01 UTC, mpaktiti commented on articles/hosted-pages/password-reset.md
> +![](/media/articles/hosted-pages/password_reset.png)
Missing alternate text for the image.

2016-11-03 08:01 UTC, mpaktiti commented on articles/hosted-pages/error-pages.md
> +![](/media/articles/hosted-pages/generic-error-page-settings.png)
Missing alternate text for the image.

2016-11-04 12:18 UTC, merged