Document getting tokens for API v2 using the client credentials flow
auth0/docs pull request #2810
Opened 2016-11-19 00:29 UTC by angelaLazar

https://trello.com/c/hDkOVvwO/20-getting-tokens-for-api-v2-using-the-client-credentials-flow

2016-11-21 09:40 UTC, mpaktiti requested changes
Hey Angela, I left some feedback. In addition to that, the screenshots seem wrong, they do not have the *APIs* menu on the left.

2016-11-21 09:40 UTC, mpaktiti commented on articles/api/management/v2/tokens.md
> +To create a new Non Interactive Client, go to the [Clients section](${manage_url}/#/clients) of the dashboard then click the **CREATE CLIENT** button.
In order for this to work the *Account Settings > Advanced > Enable APIs Section* has to be enabled. If it is not, then I do not see the *APIs* menu on the left and I do not have the *Non Interactive Client* option when I create a new Client. You can check [in this doc](https://auth0.com/docs/apis#how-to-configure-an-api-in-auth0).

2016-11-21 09:40 UTC, mpaktiti commented on articles/api/management/v2/tokens.md
> +![](/media/articles/api/tokens/noninteractive-client.png)
Missing alternate text.

2016-11-21 09:40 UTC, mpaktiti commented on articles/api/management/v2/tokens.md
> +![](/media/articles/api/tokens/navigate-button.png)
Missing alternate text.

2016-11-21 09:40 UTC, mpaktiti commented on articles/api/management/v2/tokens.md
> +![](/media/articles/api/tokens/authorize-noninteractive.png)
Missing alternate text.

2016-11-21 09:40 UTC, mpaktiti commented on articles/api/management/v2/tokens.md
> +![](/media/articles/api/tokens/choose-scopes.png)
Missing alternate text.

2016-11-21 09:40 UTC, mpaktiti commented on articles/api/management/v2/tokens.md
> +![](/media/articles/api/tokens/test-client.png)
Missing alternate text.

2016-11-21 19:51 UTC, angelaLazar commented
@mpaktiti I addressed your comments in the latest commit

2016-11-22 09:56 UTC, mpaktiti approved these changes

2016-11-22 09:56 UTC, merged