link fixed
auth0/docs pull request #3008
Opened 2016-12-15 18:20 UTC by camimonse

before the link was directing to: https://auth0.com/docs/%22https:/manage.auth0.com#/apis

2016-12-15 18:20 UTC, camimonse commented
this refers to #3005

2016-12-15 21:29 UTC, mpaktiti requested changes

2016-12-15 21:29 UTC, mpaktiti commented on articles/server-apis/webapi-owin/00-intro.md
> +In the [APIs section](https://manage.auth0.com/#/apis) of the Auth0 Dashboard, click the **Create API** button. Provide a **Name** and **Identifier** for your API. Be sure to choose the RS256 signing
@camimonse This should be `${manage_url}/#/apis`. We don't hardcode the dashboard URL.

2016-12-20 10:18 UTC, mpaktiti approved these changes

2016-12-20 10:18 UTC, merged