Link fixed
auth0/docs pull request #3010
Opened 2016-12-15 18:35 UTC by camimonse

The link wouldn't work

2016-12-15 18:35 UTC, camimonse commented
this fixes #3009

2016-12-15 21:30 UTC, mpaktiti requested changes

2016-12-15 21:30 UTC, mpaktiti commented on articles/server-apis/webapi-owin/02-authorization.md
> +You will need to define to list of scopes available in your application. In the [APIs section](https://manage.auth0.com/#/apis) of the Auth0 Dashboard, select your API and then go to the __Scopes__ t
Please change this to `${manage_url}/#/apis`. This is the variable we use for the dashboard.

2016-12-20 10:16 UTC, mpaktiti approved these changes

2016-12-20 10:22 UTC, merged