[DO NOT MERGE] Auth0 Xamarin Forms Custom Login - WIP
auth0/docs pull request #3073
Opened 2016-12-21 20:39 UTC by kukicado

Draft of Auth0 Xamarin Forms Custom Login

Need review by @chenkie and still to upload sample.

2016-12-27 13:17 UTC, hzalaz requested changes
Also check the formatting of the code snippets since the margins are off (check heroku's preview deploy)

2016-12-27 13:17 UTC, hzalaz commented on articles/native-platforms/xamarin/02-custom-login.md
> +* `Auth0AccessToken`: the `access_token` that can be used to call the Auth0 APIs. For example, you could use this token to [Link Accounts](/link-accounts).
I'd remove the mention of link accounts and state that the `access_token` can be used with an API if the OAuth 2.0 features are enabled (and supplied an audience during Auth).

2017-01-03 18:28 UTC, kukicado commented
@hzalaz Made updates based on your feedback. Ready for final review.

2017-01-03 19:00 UTC, hzalaz approved these changes

2017-06-02 19:23 UTC, closed without merging