Detail XSRF attack
auth0/docs pull request #3375
Opened 2017-01-27 23:31 UTC by angelaLazar

https://trello.com/c/a7kZX5Vg/701-using-the-state-parameter

2017-01-30 11:29 UTC, mpaktiti requested changes
Add an attach scenario to the article

2017-01-30 11:29 UTC, mpaktiti commented on articles/protocols/oauth2/oauth-state.md
I think this article needs some more work. The purpose of the card is to outline the attach scenario but we only give a definition and info on how to use the param. I think that we need a sub-paragraph describing a simple attack scenario, accompanied by a diagram.

2017-01-30 22:37 UTC, angelaLazar commented on articles/protocols/oauth2/oauth-state.md
@mpaktiti A diagram is a good idea. Do you know what program can I use to create one?

2017-01-31 10:24 UTC, mpaktiti commented on articles/protocols/oauth2/oauth-state.md
Just draw it with whatever suits you best and send it to Julieta from design team. She will make it pretty and send it back to you. Personally sometimes I just draw it on paper and take a photo. Or you could use something like this https://www.draw.io/

2017-03-07 22:29 UTC, angelaLazar commented
@mpaktiti I have added in the diagram from design

2017-03-08 11:53 UTC, merged