Change GET har snippet
auth0/docs pull request #3659
Opened 2017-03-07 20:45 UTC by khorne3

2017-03-08 11:29 UTC, mpaktiti commented on articles/tutorials/calling-an-external-idp-api.md
> +	"method": "POST",
@khorne3 I'm pretty sure this is wrong, and the way it was before was the correct one. The valid way to get an APIv2 token is described here https://auth0.com/docs/api/management/v2/tokens#1-get-a-token

I even tried to get a token with the new way described here but if I don't specify the `audience` param, the token I'm getting is an opaque token, not a JWT, and if I try to use it at the Management APIv2 I get the following error:

![image](https://cloud.githubusercontent.com/assets/11715799/23702243/1617fe0c-0403-11e7-93c4-fa45f8665f4c.png)

Did someone from engineering give this input or can I fix it and merge?

2017-03-08 11:30 UTC, mpaktiti requested changes
The described way to get an APIv2 token does not seem correct.

2017-03-08 16:38 UTC, khorne3 commented on articles/tutorials/calling-an-external-idp-api.md
> +	"method": "POST",
You can fix it and merge; thanks!

2017-03-08 18:56 UTC, khorne3 commented
@mpaktiti Reverted.

2017-03-09 12:37 UTC, mpaktiti commented
@khorne3 I just realized there are more changes required.

The process to get a Management APIv2 Token has changed. You can do it either using client credentials or using the dashboard. All the details are [here](https://auth0.com/docs/api/management/v2/tokens).

I would leave 4 paragraphs/steps:
- __Step 1: Create a Client__ (add some of the info [here](https://auth0.com/docs/api/management/v2/tokens#1-create-and-authorize-a-client))
- __Step 2: Obtain an Auth0 Access Token__ (either [copy it from the dashboard](https://auth0.com/docs/api/management/v2/tokens#2-get-the-token) or [automate the process using client credentials](https://auth0.com/docs/api/management/v2/tokens#automate-the-process)).
- __Step 3: Obtain the User Profile__ (same content as https://auth0-docs-content-pr-3659.herokuapp.com/docs/tutorials/calling-an-external-idp-api#2-obtain-the-user-profile)
- __Step 4: Extract the idP Access Token__ (same content as https://auth0-docs-content-pr-3659.herokuapp.com/docs/tutorials/calling-an-external-idp-api#3-extract-the-idp-access-token)

2017-03-14 18:28 UTC, merged