Add doc on OIDC-Conformant SSO
auth0/docs pull request #3762
Opened 2017-03-22 21:47 UTC by khorne3

2017-03-23 18:22 UTC, khorne3 commented
@mpaktiti Do you mind reviewing this as well?

2017-03-28 11:35 UTC, mpaktiti requested changes
Two comments here:

1. You do not refer to the sample https://github.com/rolodato/oidc-sso-sample I think it should be added (intro text, link to download, how to run, move sample to `auth0-samples`.

2. I think you should change the doc's structure a bit, the intro to be specific. As a first thing in the doc, I would expect to see some theory (similar to What SSO Looks Like paragraph). Then a quick reference to the implementation method (silent authentication), then the prerequisites, then how to implement this, and finally a couple of screenshots (if applicable, I haven't run the sample).

2017-03-28 11:35 UTC, mpaktiti commented on articles/sso/v2/single-page-apps-sso.md
> +  * Passing the `connection` query string parameter when calling the [Authentication API's `/authorize` endpoint](/api/authentication#login).
Update API URL to `/api/authentication##implicit-grant`. It's the same endpoint, but the one I'm referring to is specific to Implicit Grant.

2017-03-28 11:35 UTC, mpaktiti commented on articles/sso/v2/single-page-apps-sso.md
> +* Enable the **Use Auth0 instead of the IdP to do Single Sign On** flag in the [Auth0 Client's settings tab](${manage_url});
I think it's better to replace the URL with sth like `${manage_url}/#/clients/${client.accountId}/settings`.

2017-04-03 14:17 UTC, mpaktiti requested changes
Hey Katie, left some comments here. You can also rename v2 to oidc and then add the document versioning functionality. You can see an example here https://github.com/auth0/docs/pull/3758/files In the p2 docs case we will name the folders legacy (the existing doc), and oidc (the p2 version of the doc, like this one).

2017-04-03 14:17 UTC, mpaktiti commented on articles/sso/v2/single-page-apps-sso.md
> +This article shows you how to implement OIDC-compliant Single Sign On via [Silent Authentication](/api-auth/tutorials/silent-authentication) for your Single Page Applications using [this sample](http
Looks like something is missing here "This process involves"

2017-04-03 14:17 UTC, mpaktiti commented on articles/sso/v2/single-page-apps-sso.md
> +1. Add `http://localhost:3000` and `http://localhost:3000/callback.html` to the Allowed Callback URLs field of your [Auth0 Client Settings](${manage_url}/#/clients/${account.clientId}/settings).
Missing first bullet: Create new Client (and select SPA). You can add it in the same bullet as well, I don't mind, just don't jump directly to Allowed Callback URLs.

I know you have a panel earlier, but I would remove the panel and add one extra bullet: create a client, select SPA, set the OIDC Conformant toggle to true.

2017-04-03 14:17 UTC, mpaktiti commented on articles/sso/v2/single-page-apps-sso.md
> +<div class="alert alert-info">
I think this would look better after the bullets.

2017-04-03 14:17 UTC, mpaktiti commented on articles/sso/v2/single-page-apps-sso.md
> +## Implement SSO on Your SPA
I don't really see why this header is here. It has only one pabel and then it goes into another header `### Get Started with the OIDC-Compliant Single Sign On Sample`. I would add only one header with sth like `Configure the Sample Application`

2017-04-03 14:17 UTC, mpaktiti commented on articles/sso/v2/single-page-apps-sso.md
> +To initiate a silent authentication request, include the `prompt` parameter in your [authorization URL](/api/authentication#implicit-grant) and set it to `none` when redirecting users to the [Authent
Both URLs should be like the first one: /api/authentication#implicit-grant

2017-04-03 14:17 UTC, mpaktiti commented on articles/sso/v2/single-page-apps-sso.md
> +Refer to the [tutorial on using Implict Grants](/api-auth/tutorials/implicit-grant#1-get-the-user-s-authorization) for information on the authorization call's parameters.
Grants -> Grant

2017-04-03 14:17 UTC, mpaktiti commented on articles/sso/v2/single-page-apps-sso.md
> +Regardless of which outcome occurs, the sample app's `postMessage` function sends Auth0's response from the iframe back to the main page, allowing it to act based on the response.
Maybe add the script inline? Your call.

2017-04-03 14:17 UTC, mpaktiti commented on articles/sso/v2/single-page-apps-sso.md
> +## Refresh Expired Access Tokens
I think there is too much duplication of content. Maybe remove this and add somewhere a note/panel with a link to the main silent authentication doc for details?

2017-04-03 14:17 UTC, mpaktiti commented on articles/sso/v2/single-page-apps-sso.md
> +
This is the "legacy" scenario. I think in this p2 case the sample app has only 1 SPA, right?

2017-04-06 02:44 UTC, closed without merging