How to represent multiple APIs using one resource server
auth0/docs pull request #3777
Opened 2017-03-24 19:44 UTC by khorne3

2017-03-24 19:47 UTC, khorne3 commented
@mpaktiti The sample I used to document this uses the implicit flow, but it looks like it can be used w/ any of our grants. As such, I included links to various options for users at the bottom--what do you think?

2017-03-28 10:50 UTC, mpaktiti requested changes
This is good but you don't use the sample at all. I would expect: a short description at the top explaining the scenario (in this scenario we will implement 2 APIs: contacts and calendars, etc), some info on how to run the sample and maybe a screenshot from the SPA, link to download/fork the sample (which should be copied to `auth0-samples` since `auth0-dse` is a private repo https://github.com/auth0/auth0-dse/tree/master/samples/api-auth-implicit

2017-04-03 13:17 UTC, mpaktiti requested changes
Hey, I left some more comments on this.

2017-04-03 13:17 UTC, mpaktiti commented on articles/api-auth/tutorials/use-one-rs-for-apis.md
> +# Represent Multiple APIs as a Single Resource Server
The term `Resource Server` is a bit confusing to some. It's OAuth 2.0 terminology, most people just look for "API". I would change the title to sth like `How to define multiple APIs in Auth0`

2017-04-03 13:17 UTC, mpaktiti commented on articles/api-auth/tutorials/use-one-rs-for-apis.md
> +This article shows you how to use and represent multiple APIs as a single Resource Server in Auth0 using a [sample application you can download](https://github.com/auth0-samples/auth0-api-auth-implic
I'm thinking that we could also add the box the Quickstarts use to download/fork project. Wdyt?

2017-04-03 13:17 UTC, mpaktiti commented on articles/api-auth/tutorials/use-one-rs-for-apis.md
> +If you have multiple APIs, you can treat them as a single Resource Server. Doing this allows you to implement just one authentication flow. You can then control access to the individual APIs by assig
I would rephrase this a bit, to avoid using the "Resource Server" term. Sth like `In most cases, you can [create a single API in the dashboard](/apis) to represent all of your existing APIs. Doing this allows you to implement just one authentication flow. You can then control access to the individual APIs by assigning the appropriate scopes.`

2017-04-03 13:17 UTC, mpaktiti commented on articles/api-auth/tutorials/use-one-rs-for-apis.md
> +In the sample application, we have:
In the sample application you only have the first bullet, the two API js files. The other entries are things involved in this sample application (terms and concepts). 

I would remove this and add a couple of sentences describing the sample: `The sample contains 1 SPA and 2 APIs: contacts and calendar. We will represent the APIs in Auth0 with a single API, which we will name Organizer Service. Then we will configure the scopes .... and see how you can use the Implicit Grant to access these two APIs from the SPA.`

2017-04-03 13:17 UTC, mpaktiti commented on articles/api-auth/tutorials/use-one-rs-for-apis.md
> +At this point, you've:
I would remove this, it looks redundant. Just add something like "add these two scopes and save your changes"

2017-04-03 13:17 UTC, mpaktiti commented on articles/api-auth/tutorials/use-one-rs-for-apis.md
> +:::
I would add in the panel `For a full list refer to [API Authorization](/api-auth)`

2017-04-03 13:17 UTC, mpaktiti commented on articles/api-auth/tutorials/use-one-rs-for-apis.md
> +The app initiates the flow and redirects the browser to Auth0 (specifically to the ``/authorize` endpoint), so the user can authenticate.
One extra char here: specifically to the ``/authorize` endpoint)

2017-04-03 13:17 UTC, mpaktiti commented on articles/api-auth/tutorials/use-one-rs-for-apis.md
> +redirect_uri=http://localhost:3000&
We never created a client in Auth0 for the SPA. You need to add this step and set the callback URL to `http://localhost:3000`

2017-04-03 13:17 UTC, mpaktiti commented on articles/api-auth/tutorials/use-one-rs-for-apis.md
> +For additional information on the call's parameters, refer to the [docs on executing an implementing the Implicit Grant](/api-auth/grant/implicit#1-get-the-user-s-authorization).
The link does not work, you want the doc under tutorials.

2017-04-03 13:17 UTC, mpaktiti commented on articles/api-auth/tutorials/use-one-rs-for-apis.md
> +For additional information on the call's parameters, refer to the [docs on executing an implementing the Implicit Grant](/api-auth/grant/implicit#1-get-the-user-s-authorization).
I would remove this however from the panel and add it as a simple sentence under the `/authorize` script.

2017-04-03 13:17 UTC, mpaktiti commented on articles/api-auth/tutorials/use-one-rs-for-apis.md
> +In the sample application, we have:
Mention also that the sample uses our Lock widget.

2017-04-03 13:17 UTC, mpaktiti commented on articles/api-auth/tutorials/use-one-rs-for-apis.md
> +Lock handles the login process (you can log in with a user that exists in a [Connection](/identityproviders) enabled for your Auth0 Client).
We never created the Client and we didn't enable a connection for it.

2017-04-03 13:17 UTC, mpaktiti commented on articles/api-auth/tutorials/use-one-rs-for-apis.md
> +redirect_uri=http://localhost:3000&
Don't add lots of details/screenshots, brief steps and link to reference docs for details.

2017-04-03 13:17 UTC, mpaktiti commented on articles/api-auth/tutorials/use-one-rs-for-apis.md
> +Next, Auth0 authenticates the user. If this is the first time the user goes through this flow, they will be asked to consent to the scopes that are given to the Client (such as post messages or list
I would replace `(such as post messages or list contacts)` with the real scopes for this sample. A screenshot with the consent window would look nice as well here.

2017-04-03 13:17 UTC, mpaktiti commented on articles/api-auth/tutorials/use-one-rs-for-apis.md
> +If the user consents, Auth0 continues the authentication process, and upon completion, redirects them back to the app with an `access_token` in the hash fragment of the URI. The app can now extract t
`see the `getAccessToken` function located in `index.html` for the sample app` : add inline the script maybe?

2017-04-05 13:32 UTC, mpaktiti approved these changes
Looks good 👍

2017-04-28 12:16 UTC, mpaktiti commented
Hey @khorne3 I'm going to merge this. Before I do so can you please do the following:

- Add a new doc entry for the update feed.

- Add the doc at the api-auth index https://auth0-docs-content-pr-3777.herokuapp.com/docs/api-auth List it as a bullet under `Calling APIs from Client-side Web Apps` since the sample involves a SPA. Add it at the end, after `Protect against replay attacks`.

2017-04-28 17:38 UTC, merged