Add doc on Token Introspection
auth0/docs pull request #3985
Opened 2017-04-25 19:01 UTC by khorne3

2017-04-25 19:22 UTC, jhiner requested changes

2017-04-25 19:22 UTC, jhiner commented on articles/api-auth/token-introspection.md
> +Auth0 supports [OAuth 2.0 Token Introspection](https://tools.ietf.org/html/rfc7662), which allows you to ask Auth0 for details about any access tokens presented to your API. In addition to asking Aut
In addition to asking Auth0 about the *state* of the access token (whether it is active or not)

2017-04-25 19:22 UTC, jhiner commented on articles/api-auth/token-introspection.md
> +3. If the API's `identifier` is `http:`- or `https:`-based (such as `audience=https://example.com/foo`), then Auth0 attempts to fetch the key from the well-known JWK registry of the host (for the pro
in this case it wouldn't be audience=https:, it's referring to the identifier. 

So simply (such as `https://example.com/foo`)

2017-04-25 19:22 UTC, jhiner commented on articles/api-auth/token-introspection.md
> +```har
For some reason this isn't showing up correctly - I don't see the `postData`. 

Also, maybe it's better to add `token` to the list of params above to briefly explain that it is the literal token value.

2017-04-25 19:23 UTC, jhiner commented
Is it possible to add a link to the sidebar under API-auth, Dynamic Client Registration:

https://auth0-docs-content-pr-3985.herokuapp.com/docs/api-auth

2017-04-26 18:46 UTC, khorne3 commented
@jhiner This is ready for (re)review. I added a link to the sidebar, and I changed the second curl snippet (turns out our HAR generator only works with a JSON body right now).

2017-04-27 22:55 UTC, jhiner commented on articles/api-auth/token-introspection.md
> +Auth0 supports [OAuth 2.0 Token Introspection](https://tools.ietf.org/html/rfc7662), which allows you to ask Auth0 for details about any access tokens presented to your API. In addition to asking Aut
One more minor change, like this:
> Auth0 supports [OAuth 2.0 Token Introspection](https://tools.ietf.org/html/rfc7662), which allows a protected resource to query an Authorization Server (Auth0) to find out about the status of an OAuth 2.0 token (whether it is active or not). You can also obtain information such as the token's scopes and the context in which it was issued (such as who issued the token and to whom the token was issued).

2017-04-27 23:11 UTC, jhiner commented on articles/api-auth/token-introspection.md
> +You can use token introspection to request information for **access** and **refresh** tokens.
You can use token introspection to request information for JWT and non-JWT access tokens.

2017-04-28 12:13 UTC, mpaktiti requested changes
Hey I left some comments.

2017-04-28 12:13 UTC, mpaktiti commented on articles/api-auth/token-introspection.md
> +Auth0 supports [OAuth 2.0 Token Introspection](https://tools.ietf.org/html/rfc7662), which allows a protected resource to query an Authorization Server (Auth0) to request the status of an OAuth 2.0 t
If you don't know what token introspection is (I didn't), this intro leaves you with questions.
- In which case would I use this?
- Does using it means that my API doesn't have to [verify the token](https://auth0.com/docs/api-auth/tutorials/verify-access-token)?
- In the case of Auth0, where the access_token is a JWT, what is our recommendation to our customers? Use this or validate the tokens themselves?

In addition to my questions, I would expect something like this in the intro https://tools.ietf.org/html/rfc7662#section-1

2017-04-28 12:13 UTC, mpaktiti commented on articles/api-auth/token-introspection.md
> +If you choose to provide `verificationKey` or `verificationLocation` values, you can provide update your API's Auth0 record by making the appropriate `POST` call to the [Management API](/api/manageme
The endpoint does not list these two attributes: `verificationKey` and `verificationLocation`. Can you update it? Or ask Angela to do it.

2017-04-28 12:13 UTC, mpaktiti commented on articles/api-auth/token-introspection.md
> +		"value": "Bearer ABCD"
Replace `ABCD` with sth like `MGMT_API_ACCESS_TOKEN` and add a note after the har that links to the doc on how to get one.

2017-04-28 12:13 UTC, mpaktiti commented on articles/api-auth/token-introspection.md
> +To use token introspection, make a `POST` call to the [Authorization API](/api/authentication) where the content type is `application/x-www-form-urlencoded` and you've included the following paramete
Replace `Authorization API` with `Authentication API`. Also, shouldn't this PR add the `/oauth/introspect` endpoint to the API doc?

2017-04-28 12:13 UTC, mpaktiti commented on articles/api-auth/token-introspection.md
> +* **Client Assertion**: a JWT signed with your API's private key so that Auth0 can validate its signature using the associated public key.
I'm not clear on what this `Client Assertion` is. Elaborate maybe?

2017-04-28 12:13 UTC, mpaktiti commented on articles/api-auth/token-introspection.md
> +  --header 'authorization: Bearer ABCD' \
Replace `ABCD` with sth like `MGMT_API_ACCESS_TOKEN` and add a note after the har that links to the doc on how to get one.

2017-04-28 12:13 UTC, mpaktiti commented on articles/api-auth/token-introspection.md
> +You can use token introspection to request information for **JWT access** tokens, **non-JWT access** tokens, and **refresh** tokens.
Link to the docs maybe?
- JWT access token -> https://auth0.com/docs/tokens/access-token
- Refresh token -> https://auth0.com/docs/tokens/preview/refresh-token

2017-04-28 12:13 UTC, mpaktiti commented on config/sidebar.yml
> +
Can you also add an entry for this doc at the api-auth index? https://auth0.com/docs/api-auth
Same place, after `Dynamic Client Registration`.

2017-05-04 12:31 UTC, jhiner commented
@khorne3 
To answer your questions from Slack:
> Can you please provide some use cases?
Token introspection is used by Resource Servers to verify the validity of tokens. Note that we need to remove refresh tokens from the end of the doc. We technically support it, but we don't have a way for OAuth clients to call introspection right now. So for now, it's just JWT and non-JWT access tokens. 

The main use case we built introspection for was App Specific Passwords (ASP). In this case, the ASP is a non-JWT token and the API would use token introspection to verify the validity of the token. I am preparing some information to send you about the ASP feature. Perhaps we should roll out token introspection docs alongside ASP (another section along with Dynamic Client Reg and Token Introspection in the sidebar).

In case of access tokens, because we only issue JWTs today, introspection isn't super useful for that. In the future, we will start issuing non-JWT reference tokens (much like the opaque `userinfo` tokens today), and in that case, introspection is the mechanism by which APIs would verify their validity.

> Should the API still verify the token, or are there cases where this isn’t necessary because token introspection provides sufficient info?

Token introspection is a means by which an API can verify a token. 

> If the access token is a JWT, what’s our best practice recommendation: use token introspection or validate the tokens themselves?

It's fine to continue to use existing token validation mechanisms with JWT tokens. As mentioned above, this is more useful for newer features we will roll out in the future (e.g. non-JWT reference tokens).

2017-05-04 18:18 UTC, khorne3 commented
See https://github.com/auth0/docs/pull/4053 for new PR that will include ASP docs.

2017-05-04 18:18 UTC, closed without merging

2017-06-01 13:56 UTC, chenkie commented on articles/api-auth/token-introspection.md
> +Because token instrospection is a means by which an API can verify a token, you do not need to configure any addition verification flows performed by the API. Additionally, for any existing authoriza
typo "addition"