SAML
auth0/docs pull request #4139
Opened 2017-05-16 16:12 UTC by khorne3

2017-05-24 12:14 UTC, mpaktiti requested changes
It took me a couple of hours just for a high level overview of this, great work Katie! 🥇 

Inevitably, there are some things that need fixing, left some comments here.

2017-05-24 12:14 UTC, mpaktiti commented on articles/protocols/saml/saml-configuration/auth0-as-identity-and-service-provider.md
> +::: panel SAML-Compliant Providers
Use panels only to separate long information from the main body of the document. This is quote short so it should be either a note (for extra info) or a warning (for deprecations, security warnings and very important info). In this case a [note](https://github.com/auth0/docs/blob/master/CONTRIBUTING.md#note) should do.

2017-05-24 12:14 UTC, mpaktiti commented on articles/protocols/saml/saml-configuration.md
> +![](https://cdn2.auth0.com/docs/media/articles)/saml/identity-providers/okta/configure-new-connection.png)
This image should be at `/media`, not at CDN.

2017-05-24 12:14 UTC, mpaktiti commented on articles/protocols/saml/saml-configuration/auth0-as-identity-and-service-provider.md
> +
Both links `404`. Looks like the `/troubleshoot` shouldn't be part of the URL?

2017-05-24 12:14 UTC, mpaktiti commented on articles/protocols/saml/saml-configuration.md
> +![](https://cdn2.auth0.com/docs/media/articles)/saml/identity-providers/okta/configure-new-connection.png)
For some reason I cannot see these changes at the heroku app. Is it the same for you or should I get more coffee? https://auth0-docs-content-pr-4139.herokuapp.com/docs/protocols/saml/saml-configuration

2017-05-24 12:14 UTC, mpaktiti commented on articles/protocols/saml/saml-configuration/design-considerations.md
> +  * You can use an Auth0 [rule](/rule) to call an API to retrieve any missing information and dynamically add it to the Auth0 profile (which is then returned to the application). Rules execute after
Gives `404`. The correct one is `/rules`.

2017-05-24 12:14 UTC, mpaktiti commented on articles/protocols/saml/saml-configuration/design-considerations.md
> + * An Auth0 [rule](/rule) that executes on first login that calls an application API to create the user profile in the application;
Gives `404`. The correct one is `/rules`.

2017-05-24 12:14 UTC, mpaktiti commented on articles/protocols/saml/saml-configuration/index.md
> +  url: saml-configuration
https://auth0-docs-content-pr-4139.herokuapp.com/docs/saml-configuration 

redirects me to 

https://auth0-docs-content-pr-4139.herokuapp.com/docs/protocols/saml/saml-configuration

2017-05-24 12:14 UTC, mpaktiti commented on articles/protocols/saml/saml-configuration/index.md
> +![](/media/articles/saml/saml-configuration/saml-case2.png)
As a follow up (not part of this PR or trello card) can you go over all the SAML docs and ask from design (Juli) to update such diagrams as this? They don't look very nice at the moment.

![image](https://cloud.githubusercontent.com/assets/11715799/26401823/575ac952-4090-11e7-8f9d-77b45d0db9a8.png)

2017-05-24 12:14 UTC, mpaktiti commented on articles/protocols/saml/saml-configuration/logout.md
> +::: panel Logout
Pretty short text, replace with `note`.

2017-05-24 12:14 UTC, mpaktiti commented on articles/protocols/saml/saml-configuration/saml-assertions.md
> +* **audience** (string): The audience of the SAML Assertion. Default will be the Issuer on SAMLRequest.
Can you add an empty line between bullets? It looks a bit too much as is https://auth0-docs-content-pr-4139.herokuapp.com/docs/protocols/saml/saml-configuration/saml-assertions#configuration-options I think we should always add an empty line between bullets.

2017-05-24 12:14 UTC, mpaktiti commented on articles/protocols/saml/saml-configuration/saml-assertions.md
> +* **digestAlgorithm**: Digest algorithm to calculate digest of the SAML Assertion or response. default sha1. It could be sha256.
The values should be formatted like that `sha1`, `sha256`, `http://schema.auth0.com`, etc

2017-05-24 12:14 UTC, mpaktiti commented on articles/protocols/saml/saml-configuration/special-configuration-scenarios/idp-initiated-sso.md
> +  ```
set this to ```text

Also, why not use `account.namespace` var instead of `{accountname}`?

2017-05-24 12:14 UTC, mpaktiti commented on articles/protocols/saml/saml-configuration/special-configuration-scenarios/index.md
> +  url: /protocols/saml/saml-configuration/special-configuration-scenarios
I think that the `url` metadata is not needed. Even without it the `index` part is getting ignored. You should cross check though.

2017-05-24 12:14 UTC, mpaktiti commented on articles/protocols/saml/saml-configuration/special-configuration-scenarios/index.md
> +This article assumes that you've already set up a [Connection](/saml-configuration/auth0-as-service-provider) or a [Client](/saml-configuration/auth0-as-identity-provider).
Both `404`

https://auth0-docs-content-pr-4139.herokuapp.com/docs/saml-configuration/auth0-as-service-provider

https://auth0-docs-content-pr-4139.herokuapp.com/docs/saml-configuration/auth0-as-identity-provider

2017-05-24 12:14 UTC, mpaktiti commented on articles/protocols/saml/saml-configuration/special-configuration-scenarios/signing-and-encrypting-saml-requests.md
> +Special Configuration Scenarios: Signing and Encrypting SAML Requests
Missing H1

2017-05-24 12:14 UTC, mpaktiti commented on articles/protocols/saml/saml-configuration/supported-options-and-bindings.md
> +# SAML Bindings and Options
I would update the title to `Supported SAML Bindings and Options`

2017-05-24 12:14 UTC, mpaktiti commented on articles/protocols/saml/saml-configuration/troubleshoot/auth0-as-idp.md
> +# SAML Troubleshooting When Auth0 is the Identity Provider
`When` -> `when`

2017-05-24 12:14 UTC, mpaktiti commented on articles/protocols/saml/saml-configuration/troubleshoot/auth0-as-idp.md
> +## Issue: User Successfully Logs In With the IdP, but a Successful Login Event Does *Not* Show Up in Auth0 Logs
Duplicate issue/content with the first one

2017-05-24 12:14 UTC, mpaktiti commented on articles/protocols/saml/saml-configuration/troubleshoot/auth0-as-idp.md
> +## Issue: User Successfully Logs In With the IdP, but a Successful Login Event Does *Not* Show Up in Auth0 Logs
I would add something shorter for the title, like `Successful Login does not show up in Auth0 logs`. After that the first sentence of this paragraph could be the full one: `The user successfully logs in with the Identity Provider, but a successful login event does not show up in Auth0 logs`.

Also, bear in mind that, according to design, we should minimise our use of italics. This is on my todo list for June, but in the meanwhile try to minimise it's usage, especially in titles.

2017-05-24 12:14 UTC, mpaktiti commented on articles/protocols/saml/saml-configuration/troubleshoot/auth0-as-idp.md
> +* Check to see if the user's Auth0 profile populated correctly:
Same comment as earlier, add an empty line between bullets, the text looks too stuffed.

2017-05-24 12:14 UTC, mpaktiti commented on articles/protocols/saml/saml-configuration/troubleshoot/auth0-as-sp.md
> +# SAML Troubleshooting When Auth0 is the Service Provider
`When` -> `when`

I would also reverse the order of the first two words in this and in the previous doc: `Troubleshooting SAML when Auth0 is the Service Provider`

2017-05-24 12:14 UTC, mpaktiti commented on articles/protocols/saml/saml-configuration/troubleshoot/auth0-as-sp.md
> +## Issue: User Successfully Logs In With the IdP, a Successful Login Event Shows Up in Auth0 Logs, but the User's Profile Attributes are Incorrect
Same comment for length of headers

2017-05-24 12:14 UTC, mpaktiti commented on articles/protocols/saml/saml-configuration/troubleshoot/index.md
> +url: /protocols/saml/saml-configuration/troubleshoot
Same comment as earlier, I think `/index` gets ignored.

2017-05-24 20:20 UTC, khorne3 commented
I forgot to delete the origin saml config doc, which was why the metadata URLs were all weird. I fixed them, so you shouldn't see any more unexpected behavior.

2017-05-25 17:56 UTC, khorne3 commented
@mpaktiti Fixed issues you brought up, plus added another doc on Common SAML errors. I think it's ready for review.

2017-05-29 12:31 UTC, mpaktiti commented
@khorne3 I'm merging this. I have some thoughts though on whether some docs should be removed/merged from the index.

For example, these two seem to be about the same thing and they might be confusing listed in the index together:
https://auth0.com/docs/protocols/saml/saml-configuration/auth0-as-service-provider
https://auth0.com/docs/protocols/saml/saml-sp-generic

or

https://auth0.com/docs/protocols/saml/saml-configuration/auth0-as-identity-provider
https://auth0.com/docs/protocols/saml/saml-idp-generic

Can you review and clean up the [index](https://auth0.com/docs/protocols/saml) (and remove/merge docs if needed) as another task?

2017-05-29 12:32 UTC, merged