Use rules to restrict access to API scopes
auth0/docs pull request #4167
Opened 2017-05-17 21:29 UTC by khorne3

2017-05-17 21:47 UTC, cabralmartin requested changes

2017-05-17 21:47 UTC, cabralmartin commented on articles/api-auth/api-access-policies.md
> +By default, any user associated with an Auth0 client can request an API's scope(s). If you would like to restrict access to the API's scopes based on the user's role, you can do so via [rules](/rules
` If you would like to restrict access to the API's scopes based on the user's role,`

Not only user roles but any condition we can think of, i.e. we could restrict a certain client id or user id altogether, we could use location, etc

2017-05-17 21:47 UTC, cabralmartin commented on articles/api-auth/api-access-policies.md
> +   * if you have a default set in the Management Dashboard.
I'm not sure I understand this comment. Is this saying that `audience` will be empty if users define one in the Advanced Settings of the Management Dashboard?
I was under the impression that the `audience` param will be populated depending on wether or not it was sent as part of the query to `/authorize`.

2017-05-17 21:47 UTC, cabralmartin commented on articles/api-auth/api-access-policies.md
> +  audience = audience || (context.request && context.request.body && context.request.body.audience);
Silly question, would it be possible to merge these checks? Looks like dup code.

2017-05-17 21:47 UTC, cabralmartin commented on articles/api-auth/api-access-policies.md
> +You can easily modify the script above to check the `scopes`, `clients`, or other value.
Can we add an example for `client` showing how to 401 a specific client id that whats to consume a specific API?

2017-05-19 20:55 UTC, khorne3 commented
@cabralmartin Can you please (re)review? Thanks.

2017-05-23 14:00 UTC, cabralmartin commented on articles/api-auth/restrict-requests-for-scopes.md
> +  // default audience (leave the audience variable empty).
Have we tried this rule with default audiences to check this is indeed the behaviour? From reading the code this gives me the impression that we are going to 401 to that client id in cases where no audience is defined, which sounds like a bug.

2017-05-23 21:25 UTC, khorne3 commented on articles/api-auth/restrict-requests-for-scopes.md
> +  // default audience (leave the audience variable empty).
You're correct; just checked and that should've been ||. Regardless, I think it makes sense to do two code snippets.

2017-05-25 12:42 UTC, mpaktiti commented on articles/api-auth/index.html
> +---
@khorne3 What is this file? Added by mistake?

2017-05-25 12:44 UTC, mpaktiti commented on articles/api-auth/restrict-requests-for-scopes.md
> +  client_id = context.clientID;
@khorne3  Is there a point to this line? The `client_id` is not used anywhere in the script.

2017-05-25 17:11 UTC, khorne3 commented
@mpaktiti Fixed. Thanks!

2017-05-29 11:19 UTC, merged