Lock for Web versioning improvements and linting
auth0/docs pull request #4425
Opened 2017-06-13 13:51 UTC by jeffreylees

2017-08-18 10:42 UTC, mpaktiti commented on articles/libraries/lock/v10/selecting-the-connection-for-multiple-logins.md
> +When you initiate an authentication transaction with Auth0 you can optionally send a `connection` parameter. This value maps directly with any __connection__ defined in your dashboard.
@jeffreylees why remove the dashboard link?

2017-08-18 10:49 UTC, mpaktiti requested changes
Left some comments. I also saw some italics here and there, replace them with bold please.

2017-08-18 10:49 UTC, mpaktiti commented on articles/libraries/lock/v9/index.md
> +  * _**cdn {String}**_: Use as CDN base url. Defaults to `domain` if it doesn't equal `*.auth0.com`.
This doesn't look good, keep only the bold markdown ie `_**cdn {String}**_` -> `**cdn {String}**`

2017-08-18 10:49 UTC, mpaktiti commented on articles/libraries/lock/v9/selecting-the-connection-for-multiple-logins.md
> +https://${account.namespace}/authorize/?client_id=${account.clientId}&response_type=code&redirect_uri=${account.callback}&state=OPAQUE_VALUE&connection=YOUR_CONNECTION
Add some whitespace so this is displayed better:

```text
https://${account.namespace}/authorize/?  
client_id=${account.clientId}&
response_type=code&
redirect_uri=${account.callback}&
state=OPAQUE_VALUE&
connection=YOUR_CONNECTION
```

2017-08-18 10:49 UTC, mpaktiti commented on articles/libraries/lock/v9/selecting-the-connection-for-multiple-logins.md
>    auth0.show({connections: ['YOUR_CONNECTION']});
Add some formatting here:

```text
auth0.show({connections: ['YOUR_CONNECTION']});
```

2017-08-21 11:10 UTC, mpaktiti requested changes
Looks good Jeff 👍  Resolve the conflict please and we are good to go.

2017-08-21 12:00 UTC, jeffreylees commented
@mpaktiti done!

2017-08-21 13:15 UTC, merged