Add client grant deprecation notice to mobile passwordless
auth0/docs pull request #4455
Opened 2017-06-15 20:46 UTC by mauricioschneider

A few documents are missing warnings that passwordless for Mobile stops working for clients created after June 8th unless they're flagged to enable the corresponding client grant

2017-06-16 13:32 UTC, jeffreylees commented
Added a commit to fix titles, and some linting fixes in the two non `connections/passwordless` docs. Most of the `connections/passwordless` docs had linting disabled, which I left alone, because they're just a mess of includes and panels. I still changed the titles to be positioned correctly though, and added titles to the missing ones. @mpaktiti

2017-06-16 13:35 UTC, mauricioschneider commented
Thanks @jeffreylees, had my suspicions on my placement of the warnings above the titles.

2017-06-19 09:49 UTC, mpaktiti commented on articles/connections/passwordless/android.md
> +# Passwordless Authentication on Android
@jeffreylees This has 2 H1s, can you fix that?

https://auth0-docs-content-pr-4455.herokuapp.com/docs/connections/passwordless/android

2017-06-19 09:51 UTC, mpaktiti requested changes
@jeffreylees Some of the docs have duplicate headers. I stopped checking at articles/connections/passwordless/ios-email-objc.md so please user the review app to check and fix all of them.

2017-06-19 09:51 UTC, mpaktiti commented on articles/connections/passwordless/ios-email-objc.md
> +# Using Passwordless on iOS with Email (Objective C)
@jeffreylees Same here, 2 H1s

https://auth0-docs-content-pr-4455.herokuapp.com/docs/connections/passwordless/ios-email-objc

2017-06-19 10:54 UTC, jeffreylees commented
Got it, @mpaktiti. Sorry, one of those includes had an H1 in it (a generic H1). I've removed that and put headings in the docs so that the warnings in some of them can be below the headings, but above the included copy.

2017-06-19 14:31 UTC, mpaktiti approved these changes

2017-06-19 14:31 UTC, merged