[DO NOT MERGE] Added new lock events. Added analytics integrations
auth0/docs pull request #4505
Opened 2017-06-21 16:10 UTC by ntotten

- Adds new events for lock 10
- Added docs on facebook & google analytics integrations

2017-06-22 08:24 UTC, mpaktiti commented on articles/analytics/integrations/_usage.md
> +* Auth0 Lock show
@ntotten Do we have to repeat the "Auth0 Lock" part in every bullet?

2017-06-22 08:33 UTC, mpaktiti requested changes
Hey Nate, did some minor updates, this only needs one more update at the Google doc (as you can see in my comment there I can't edit this file with the github editor)

2017-06-22 08:33 UTC, mpaktiti commented on articles/analytics/integrations/google-analytics/index.md
> +> Notice: The script version above uses a placeholder version `X.Y.Z`. In order to determine the latest release view the [releases in github](https://github.com/auth0/auth0-analytics.js/releases/). F
@ntotten Can you change this to the format I used in the facebook doc?

```
::: note
The script version above uses a placeholder version `X.Y.Z`. In order to determine the latest release view the [releases in github](https://github.com/auth0/auth0-analytics.js/releases/). For example, to reference release 1.2.0 use `https://cdn.auth0.com/js/analytics/1.2.0/analytics.min.js`
:::
```

For some reason I can't edit this doc using the online editor, the editor closes as soon as it loads.

2017-06-23 12:32 UTC, mpaktiti approved these changes

2017-06-23 14:20 UTC, ntotten commented on articles/analytics/integrations/_usage.md
> +* Auth0 Lock show
Yeah, since its what actually shows up in the event logs.

2017-06-23 14:21 UTC, merged