Update doc on Step-Up/MFA
auth0/docs pull request #4552
Opened 2017-06-28 15:56 UTC by khorne3

2017-06-29 15:56 UTC, mpaktiti requested changes
The doc looks good Katie, left a couple of comments for some additional fixes

2017-06-29 15:56 UTC, mpaktiti commented on articles/tutorials/step-up-authentication.md
> +* Authentication Methods References `amr`: JSON array of strings listing the methods used to authenticate the current session. For example, the `amr` might indicate that the current session was authe
`amr` is looking very good, but I did not understand what `acr` is. Maybe explain it a bit more?

2017-06-29 15:56 UTC, mpaktiti commented on articles/tutorials/step-up-authentication.md
> +* `acr_values`: string specifying the `acr` values that have been user to process the request in order of preference. See `acr_values` under [Authentication Request](http://openid.net/specs/openid-co
`user` -> `used`?

2017-06-29 15:56 UTC, mpaktiti commented on articles/tutorials/step-up-authentication.md
> +To request that Auth0 require multifactor authentication for certain situations, add the `acr_values` field to the authentication request along with the `acr` level desired. For example, if you're us
Maybe rephrase `To request that Auth0 require multifactor authentication for certain situations` to something simpler like `To enable step-up-authentication`?

2017-06-29 21:02 UTC, khorne3 commented
@mpaktiti Ready for re-review. Thanks!

2017-06-30 11:18 UTC, mpaktiti approved these changes

2017-06-30 11:26 UTC, merged