Auth0.js migration guide additions
auth0/docs pull request #4677
Opened 2017-07-14 14:19 UTC by jeffreylees

2017-07-14 15:08 UTC, mpaktiti requested changes
Hey Jeff, left some comments.

2017-07-14 15:08 UTC, mpaktiti commented on articles/libraries/auth0js/v8/migration-guide.md
> +If you need to use [API Auth](/docs/api-auth) features, we recommend that you upgrade to [auth0.js v8](/docs/libraries/auth0js/v8).
Remove `/docs` from links: `/docs/api-auth` -> `/api-auth`

(there are more later in the doc)

2017-07-14 15:08 UTC, mpaktiti commented on articles/libraries/auth0js/v8/migration-guide.md
> +If you need to use [API Auth](/docs/api-auth) features, we recommend that you upgrade to [auth0.js v8](/docs/libraries/auth0js/v8).
Also I'd like to see some more context. `API Auth` doesn't really mean something. I get that you link to the doc, but you should add a sentence or two and then say for more information refer to API Authorization.

2017-07-14 15:08 UTC, mpaktiti commented on articles/libraries/auth0js/v8/migration-guide.md
> +### Use of API Auth and Metadata
I would add something about this paragraph in the first bullet earlier:

`Auth0.js v8 is tailored for usage with the Authentication API and for OIDC compliance. For more information, refer to [Use of API Auth and Metadata](#use-of-api-auth-and-metadata)`

Also, I think the this first sentence (`tailored for usage with the Authentication API and for OIDC compliance`) is kind of obscure. Maybe use more plain language and give more info? Sth like: with version 8 of the library, you can use our latest and more secure authentication pipeline, that complies with the OpenID Connect specification.

2017-07-14 15:08 UTC, mpaktiti commented on articles/libraries/auth0js/v8/migration-guide.md
> +If, however, your application is relying on being able to request metadata via [scopes](/docs/scopes), you have two choices:
I don't understand what `If, however, your application is relying on being able to request metadata via [scopes](/docs/scopes)` means. Also, the doc you linked, is versioned and the version this navigates is the OIDC-compliant (plus, it's broken due to the extra `/docs`.

2017-07-14 15:08 UTC, mpaktiti commented on articles/libraries/auth0js/v8/migration-guide.md
> +* Use v8 without using API Auth. Do not mark your client as OIDC Conformant, do not pass the `audience` parameter. For example, if using [authorize()](http://auth0.github.io/auth0.js/global.html#auth
- Same comment as earlier `API Auth` means nothing to most users.
- Remove italics from the last note.
- Why say `some of the methods mentioned here`? It's 4 methods in total, why not say which use the legacy RO grant? Also, most people will not know what this legacy RO grant is (or a grant in general). Add a link maybe?
- You say `For example, if using x, y, z, or w`. Syntactically it's not correct, you're missing the second part of the if clause. I would rephrase this entire bullet. 
- Why do you link outside this doc? Is this new http://auth0.github.io/auth0.js/global.html ? It's not that I don't like it (on the contrary, I always thought these docs should not be just a library reference) but why link outside our docs, if you have this info here? Also why not add a note panel at the beginning of this doc to link maybe to this external reference?

2017-07-14 15:08 UTC, mpaktiti commented on articles/libraries/auth0js/v8/migration-guide.md
> +Alternatively, you could also simply request the metadata in a different way, for example with a rule to add custom claims to either the returned `id_token` or `access_token` as described in the [cus
Use relative links.

2017-07-14 15:08 UTC, mpaktiti commented on articles/libraries/auth0js/v8/migration-guide.md
> +In [auth0.js v7](/libraries/auth0js/v7#refresh-token), the `renewIdToken` and `refreshToken` methods were used to renew tokens. In [auth0.js v8](/libraries/auth0js#using-renewauth-to-acquire-new-toke
- Remove `now` from `is now done`. 
- At the 1st sentence you say `renew` and at the 2nd `refresh`. I get that the meaning is the same but it's better to be consistent. 
- I'd add a short sentence at the beginning of this paragraph saying what "refreshing tokens" is

2017-07-17 11:55 UTC, jeffreylees commented
@mpaktiti thank you for the feedback - ugh, the links, must have been asleep at the wheel 🙊 

I've tried to re-word some things to make them more understandable. Also removed all the excess (probably unnecessary) specific method links, and instead added a panel noting where they can get more information (via our docs, or the generated ones). 

I'll take another pass over this later today, maybe, as well.

2017-07-19 11:39 UTC, mpaktiti commented
Looks good Jeff, thanks 👍  I fixed the panel (it's either `panel` or `note`) and added one more link towards the api-auth intro doc.

2017-07-19 11:43 UTC, merged