Expand definition of SAML bindings
auth0/docs pull request #4725
Opened 2017-07-24 19:40 UTC by khorne3

2017-07-24 20:04 UTC, mpaktiti requested changes
Hey Katie, the table is not formatted properly.

2017-07-24 20:04 UTC, mpaktiti commented on articles/protocols/saml/samlp.md
> +    | urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST | HTTP-POST |
The table looks like that:

![image](https://user-images.githubusercontent.com/11715799/28542250-2dded4c6-7081-11e7-971d-3733ade4118a.png)

2017-07-24 20:10 UTC, khorne3 commented
@mpaktiti I just learned that you can't indent tables, otherwise it looks like that. ☝️  :(

2017-07-25 23:15 UTC, mpaktiti requested changes
Hey Katie, I left some comments

2017-07-25 23:15 UTC, mpaktiti commented on articles/protocols/saml/samlp.md
> +    If dynamically setting the value isn't possible, then set as either `HTTP-Redirect` (default) or `HTTP-Post` if you selected this option in **Protocol Binding**
The matrix is OK now but the text underneath is not displayed correctly:

![image](https://user-images.githubusercontent.com/11715799/28597664-d68282f6-7164-11e7-9938-a927cac1b5b4.png)

2017-07-25 23:15 UTC, mpaktiti commented on articles/protocols/saml/samlp.md
> +| urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST     | HTTP-POST                  |
Since all these are values, format as code, i.e. `urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect`, `HTTP-POST`, etc

2017-07-26 18:51 UTC, khorne3 commented
@mpaktiti Fixed. Thanks!

2017-07-31 23:19 UTC, merged