AWS
auth0/docs pull request #4734
Opened 2017-07-26 20:40 UTC by khorne3

2017-08-08 11:43 UTC, mpaktiti requested changes
Hey Katie, the heroku app does not work. I can see this in the logs:

```
Error compiling document articles/integrations/aws-api-gateway-2/index.md: 
Couldn't resolve include ./_stepnav included from file /app/docs/articles/integrations/aws-api-gateway-2/index.md
```

2017-08-08 11:43 UTC, mpaktiti commented on articles/integrations/aws-api-gateway-2/index.md
> +description: blah blah
Maybe something a bit more descriptive? 😄

2017-08-08 14:54 UTC, khorne3 commented
@mpaktiti Whoops, sorry about that. I wanted to move all things API Gateway rewrite out and I missed 1-2 commits when cherry picking.

2017-08-09 12:11 UTC, mpaktiti requested changes
Hey Katie, some changes required. Thanks!

2017-08-09 12:11 UTC, mpaktiti commented on articles/integrations/aws/index.md
> +---
Good idea adding an index! Can you convert this to the `index.html` format though? It looks a bit better that way :)

2017-08-09 12:11 UTC, mpaktiti commented on articles/integrations/aws/index.md
> +---
And I would simplify the title to `Integrate Auth0 with Amazon Web Services (AWS)`

2017-08-09 12:11 UTC, mpaktiti commented on articles/integrations/aws/index.md
> + * [Perform SSO with the AWS Dashboard](/aws/sso)
The first two links are broken, you should either update them including the `/integrations` part of add url metadata at the docs.

2017-08-09 12:11 UTC, mpaktiti commented on articles/integrations/aws/sso.md
> +# Enable SSO to the AWS Console
Missing `description` and `toc` metadata

2017-08-09 12:11 UTC, mpaktiti commented on articles/integrations/aws/aws-api-setup.md
> +### Keep Reading
use `:: next steps`

2017-08-09 12:11 UTC, mpaktiti commented on articles/integrations/aws/aws-api-setup.md
> +---
Maybe it's me but I didn't understand the business case or how to test this configuration

2017-08-09 12:11 UTC, mpaktiti commented on articles/integrations/aws/tokens.md
> +![](/media/articles/integrations/aws/aws-sts.png)
Send the diagram to design

2017-08-09 12:11 UTC, mpaktiti commented on articles/integrations/aws/tokens.md
> +1. The web app authenticates its users via Social providers, such as Facebook, LinkedIn, or Twitter, or corporate credentials, such as Active Directory, Office365, or Salesforce.
maybe add some links to our individual identity provider docs (facebook, etc)

2017-08-09 12:11 UTC, mpaktiti commented
@khorne3 While you are at it add also an update feed entry

2017-08-10 14:03 UTC, merged