Improving HLP docs
auth0/docs pull request #4780
Opened 2017-08-07 13:56 UTC by jeffreylees

2017-08-16 14:02 UTC, mpaktiti requested changes
Hey Jeff, lest some comments. I would also like to see a sidebar menu item with some of the HLP docs.

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/index.md
> +Auth0's Hosted Login Page is the most secure way to easily authenticate users for your applications. The Hosted Login Page is easily customizable right from the [management dashboard](${manage_url}).
Use `dashboard` instead of `management dashboard`

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/index.md
> +If the incoming authentication request includes a `connection` parameter that uses an external identity provider (such as a social provider), the Hosted Login Page will not display. Instead, Auth0 wi
I would remove this paragraph and make this a warning. I'd also add a link to `identity provider` to our idp doc https://auth0.com/docs/identityproviders

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/index.md
> +When SSO is desired, a client should use the Hosted Login Page for logins rather than an embedded login solution. When a user logs in via the Hosted Login Page, a cookie will be created and stored. O
`the user may not ever be redirected` does not sound good. Why  not `the user will not be redirected`?

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/index.md
> +For more information about how SSO works, see the [SSO documentation](/sso).
Make this a note, since it's additional info

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/index.md
> +### Hosted Login vs Embedded Login
my 2c, I'd change this to `Why should I use this?`.  I would also push this further up, before the previous paragraph.

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/index.md
> +Security is the primary reason, followed by ease of setup. Cross-origin authentication is inherently more dangerous, and more likely to be vulnerable to man-in-the-middle attacks. Using the Hosted Lo
Maybe link to this? https://auth0.com/docs/security/common-threats

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/index.md
> +Currently, the Hosted Login Page is the _only_ way to use Passwordless authentication on Native platforms. So if your use case is a native iOS or Android application, for example, and you intend to i
Avoid using italics, design team does not like it much. Use bold instead.

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/index.md
> +Currently, the Hosted Login Page is the _only_ way to use Passwordless authentication on Native platforms. So if your use case is a native iOS or Android application, for example, and you intend to i
Also add a link to passwordless

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/index.md
> +In the [Auth0 Dashboard](${manage_url}), you can enable a custom Hosted Login Page by navigating to [Hosted Pages](${manage_url}/#/login_page) and enabling the **Customize Login Page** toggle.
try to be consistent, use only `[Dashboard](${manage_url})`. In this doc alone I saw `dashboard`, `auth0 dashboard` and `management dashboard`. It's cool for us but someone new to Auth0 might get confused.

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/index.md
> +- [Auth0.js v8](/hosted-pages/login/auth0js/v8) - Auth0.js is the SDK used for interacting with the Auth0 authentication API. Primarily, you would use the SDK if you need to build your own custom log
add link to the Authentication API

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/index.md
> +- [Auth0.js v8](/hosted-pages/login/auth0js/v8) - Auth0.js is the SDK used for interacting with the Auth0 authentication API. Primarily, you would use the SDK if you need to build your own custom log
also maybe link the `OIDC compliant transactions` to api-auth intro

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/index.md
> +- [Auth0.js v7](/hosted-pages/login/auth0js/v7) - Auth0.js is the SDK used for interacting with the Auth0 authentication API. Primarily, you would use the SDK if you need to build your own custom log
Do we want this here? I'm just checking since it's an outdated version we do not want to promote.

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/index.md
> +All changes to the page's appearance and/or behavior will apply to *all* users shown this login page, regardless of the client or connection. Remember that the Hosted Login Page customizations are pe
avoid italics

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/index.md
> +All changes to the page's appearance and/or behavior will apply to *all* users shown this login page, regardless of the client or connection. Remember that the Hosted Login Page customizations are pe
I think Eugenio mentioned at some point that there is an alternative (so you don't have to create different tenants if your client's need different HLPs) but I can't remember for sure. Unless you are 100% sure about this can you maybe cross check with someone?

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/index.md
> +### Query String Parameters
Shouldn't this be H4?

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/index.md
> +If you intend to pass any configuration parameters to the page from your client, you may need to become familiar with the `config` object. The `config` object contains the set of configuration values
Maybe refer to it consistently as `@@config@@`?

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/index.md
> +The below examples assume that you are using [Auth0.js](/libraries/auth0js/v8) to call the `authorize` endpoint from your application in order to show the Hosted Login Page.
Shouldn't these examples, since they are specific to auth0.js v8 be at that doc? https://auth0-docs-content-pr-4780.herokuapp.com/docs/hosted-pages/login/auth0js/v8

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/index.md
> +You can also pass a specific `redirect_uri` option to `authorize`, and access it within the Hosted Login Page editor by referring to `config.callbackURL`.
Maybe add a sentence at the beginning saying what the callback URL is?

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/index.md
> +All changes to the page's appearance and/or behavior will apply to *all* users shown this login page, regardless of the client or connection. Remember that the Hosted Login Page customizations are pe
If this is indeed correct, link to the last paragraph for details https://github.com/auth0/docs/pull/4780/files#diff-97c5fd061d9a868576e5b8d47fcc176dR113

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/auth0js/v8/index.md
> +Auth0.js is the current version of the SDK, and is the recommended version for projects that are able to use it. You can read the Reasons to Migrate and the API Auth sections of the [Auth0.js Migrati
Missing the version `Auth0.js is the current version`

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/auth0js/v8/index.md
> +Auth0.js is the current version of the SDK, and is the recommended version for projects that are able to use it. You can read the Reasons to Migrate and the API Auth sections of the [Auth0.js Migrati
The ` if you are uncertain.` at the end feels redundant

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/auth0js/v8/index.md
> +You can start out with a basic template that will provide you with a working, ready-to-use example of a custom UI using Auth0.js v8 in the Hosted Login Page. In the [dashboard](${manage_url}), go to
This paragraph feels like it needs some whitespace and some format changes (field names in bold, values in `code quotes` ie: "titled __Default Templates__. Here you can choose from `Lock`, `Lock Passwordless`, or `Custom UI`.")

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/auth0js/v8/index.md
> +You can start out with a basic template that will provide you with a working, ready-to-use example of a custom UI using Auth0.js v8 in the Hosted Login Page. In the [dashboard](${manage_url}), go to
Also, the last two sentences are just repeating what you have already said. Just tell them to choose `Custom UI` for this scenario.

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/auth0js/v8/index.md
> +
Missing link or note to passwordless for more info. I would add something here and remove it from Next Steps.

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/auth0js/v8/index.md
> +
In this scenario I should have selected `Custom UI` or `Passwordless Lock`

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/auth0js/v7/index.md
>  # Using Auth0.js v7 in the Hosted Login Page
Shouldn't we have a version-warning here?

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/lock-passwordless.md
> +Using Lock Passwordless in the Hosted Login Page is the easiest and most secure implementation of passwordless authentication that can be achieved. Additionally, the Hosted Login Page is the _only_ w
Is the final sentence true only for oidc-conformant clients or in either case?

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/lock-passwordless.md
> +Using Lock Passwordless in the Hosted Login Page is the easiest and most secure implementation of passwordless authentication that can be achieved. Additionally, the Hosted Login Page is the _only_ w
Avoid italics

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/lock-passwordless.md
> +Using Lock Passwordless in the Hosted Login Page is the easiest and most secure implementation of passwordless authentication that can be achieved. Additionally, the Hosted Login Page is the _only_ w
I would also add a note linking to another doc, for background info on Passwordless

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/lock-passwordless.md
> +## Lock Passwordless Template for the Hosted Login Page
I don't see the reason why this title is that long. Simplify. Set it to `Lock Passwordless Template`. The doc is for HLP, no reason to repeat it.

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/lock-passwordless.md
> +You can start out with a basic template that will provide you with a working, ready-to-use example of Lock Passwordless in the Hosted Login Page. In the [dashboard](${manage_url}), go to Hosted Pages
same comments as in the auth0.js v8 doc: add whitespace, update formatting for fields and values.

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/lock-passwordless.md
> +You can start out with a basic template that will provide you with a working, ready-to-use example of Lock Passwordless in the Hosted Login Page. In the [dashboard](${manage_url}), go to Hosted Pages
My 2c, I don't get the enthusiasm on the last sentence, I would switch to fullstop.

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/lock.md
> +If you want to change any of Lock's [configurable options](/libraries/lock/v10/customization), you can do so using the [Hosted Pages](${manage_url}/#/login_page) editor interface. These options can a
I would change 

`See the configuration documentation linked above for more details about how to configure Lock.` 

to 

`See the [configuration documentation](/libraries/lock/v10/customization) for details on how to customize Lock.`

2017-08-16 14:02 UTC, mpaktiti commented on articles/hosted-pages/login/lock.md
> +Are you looking for more information about Lock? Or are you ready to get started with your own Hosted Login Page?
My 2c, remove this sentence. Chances are someone will add one more link at some point and that sentence will feel outdated.

2017-08-17 11:10 UTC, jeffreylees commented on articles/hosted-pages/login/index.md
> +- [Auth0.js v7](/hosted-pages/login/auth0js/v7) - Auth0.js is the SDK used for interacting with the Auth0 authentication API. Primarily, you would use the SDK if you need to build your own custom log
Maybe we leave the doc, but don't reference it here as an option. I'm good with that.

2017-08-17 11:12 UTC, jeffreylees commented on articles/hosted-pages/login/index.md
> +All changes to the page's appearance and/or behavior will apply to *all* users shown this login page, regardless of the client or connection. Remember that the Hosted Login Page customizations are pe
By default, that's correct as far as I'm aware. There are workarounds that are described in the HLP index page, but nothing easier to implement yet. I think they were working on something in the dashboard to let you toggle different pages for different clients but unsure how that is going / if it is.

2017-08-17 11:12 UTC, jeffreylees commented on articles/hosted-pages/login/index.md
> +Currently, the Hosted Login Page is the _only_ way to use Passwordless authentication on Native platforms. So if your use case is a native iOS or Android application, for example, and you intend to i
The italics thing annoys me as I'm used to using them when syntactically appropriate in writing. Sorry haha

2017-08-17 11:18 UTC, jeffreylees commented on articles/hosted-pages/login/index.md
> +If you intend to pass any configuration parameters to the page from your client, you may need to become familiar with the `config` object. The `config` object contains the set of configuration values
I think I'd rather not change it from `config` unless that's what we're supposed to do (if that's the pattern in other places). In the HLP editor, the only place it's `@@config@@` is just before you save it off as `config` - it's used as a regular named variable throughout the page.

2017-08-17 11:21 UTC, jeffreylees commented on articles/hosted-pages/login/index.md
> +The below examples assume that you are using [Auth0.js](/libraries/auth0js/v8) to call the `authorize` endpoint from your application in order to show the Hosted Login Page.
That doc is for using Auth0.js in the HLP; these examples are you using Auth0.js in your application from which you're calling the HLP. I basically just wanted to show people that you can pass those parameters to the page. 

If you object to using Auth0.js here, I think I'd rather build the URL manually than move the examples elsewhere, as it's pertinent to getting config information from your application _to_ the hosted page no matter what technology you use _inside_ the page.

2017-08-17 11:45 UTC, jeffreylees commented
@mpaktiti anywhere I didn't respond I'm just implementing the change you asked for / recommended. Committing momentarily.

2017-08-18 13:07 UTC, mpaktiti approved these changes
Looks good Jeff 👍

2017-08-18 13:07 UTC, merged