AWS API Gateway
auth0/docs pull request #4783
Opened 2017-08-08 02:07 UTC by khorne3

2017-08-21 11:07 UTC, mpaktiti requested changes
Some minor changes required. Add also an entry for our update feed.

2017-08-21 11:07 UTC, mpaktiti commented on articles/integrations/aws-api-gateway/custom-authorizers/index.md
> +## Helpful Resources
You could use the `next-steps` element here instead of the list of bullets

2017-08-21 11:07 UTC, mpaktiti commented on articles/integrations/aws-api-gateway/custom-authorizers/index.md
> +1. Confirm that the OAuth 2.0 token has been passed via the `authorization` header of the request to access the API
is the `OAuth 2.0 token` an Auth0 access_token?

2017-08-21 11:07 UTC, mpaktiti commented on articles/integrations/aws-api-gateway/custom-authorizers/index.md
> +2. Verify the RS256 signature of the OAuth 2.0 token using a public key obtained via a JWKS endpoint
You could add some links to RS256 and JWKS

2017-08-21 11:07 UTC, mpaktiti commented on articles/integrations/aws-api-gateway/custom-authorizers/index.md
> +2. Verify the RS256 signature of the OAuth 2.0 token using a public key obtained via a JWKS endpoint
https://auth0.com/docs/apis#signing-algorithms

https://auth0.com/docs/jwks

2017-08-21 11:07 UTC, mpaktiti commented on articles/integrations/aws-api-gateway/custom-authorizers/index.md
> +3. Ensure the token has the required Issuer `iss` and Audience `aud` claims
I think we could add `not familiar with OAuth?` note that will link to our protocol/oauth2 doc

2017-08-21 11:07 UTC, mpaktiti commented on articles/integrations/aws-api-gateway/custom-authorizers/index.md
> +For a valid policy, API caches the returned policy, associating it with the incoming token and using it for the current and subsequent requests. You can configure the amount of time for which the pol
Use `300` format for values

2017-08-21 11:07 UTC, mpaktiti commented on articles/integrations/aws-api-gateway/custom-authorizers/part-1.md
> +In [Part 1](/integrations/aws-api-gateway/custom-authorizers/part-1) of the AWS API Gateway tutorial, we will show you how to import and manage an API using API Gateway. More specifically, we will:
Remove the link to the same doc

2017-08-21 11:07 UTC, mpaktiti commented on articles/integrations/aws-api-gateway/custom-authorizers/part-1.md
> +| Parameter | Value |
format param names (and table headers) as bold

2017-08-21 11:07 UTC, mpaktiti commented on articles/integrations/aws-api-gateway/custom-authorizers/part-2.md
> +
format param names (and table headers) as bold

2017-08-21 11:07 UTC, mpaktiti commented on articles/integrations/aws-api-gateway/custom-authorizers/part-2.md
> +JWKS_URI=https://auth0user.auth0.com/.well-known/jwks.json
maybe replace `https://auth0user.auth0.com` with `${account.namespace}`?

2017-08-21 11:07 UTC, mpaktiti commented on articles/integrations/aws-api-gateway/custom-authorizers/part-2.md
> +| Parameter | Value |
format param names (and table headers) as bold

2017-08-21 11:07 UTC, mpaktiti commented on articles/integrations/aws-api-gateway/custom-authorizers/part-2.md
> +| Parameter | Value |
format param names (and table headers) as bold

2017-08-21 11:07 UTC, mpaktiti commented on articles/integrations/aws-api-gateway/custom-authorizers/part-2.md
> +| Parameter | Value |
format param names (and table headers) as bold

2017-08-21 11:07 UTC, mpaktiti commented on articles/integrations/aws-api-gateway/custom-authorizers/part-2.md
> +| Role | `Choose an existing role` |
Is `Choose an existing role` an actual value or do you mean to say that the user should choose an existing role?

2017-08-21 11:07 UTC, mpaktiti commented on articles/integrations/aws-api-gateway/custom-authorizers/part-2.md
> +| - | - |
format param names (and table headers) as bold

2017-08-21 16:21 UTC, khorne3 commented on articles/integrations/aws-api-gateway/custom-authorizers/part-2.md
> +| Role | `Choose an existing role` |
Yep, that's the actual value, and then you choose the role in the next field.

2017-08-23 10:05 UTC, mpaktiti approved these changes
💯

2017-08-23 10:05 UTC, merged