Add prereqs section to grants tutorials and update API Identifier des…
auth0/docs pull request #4825
Opened 2017-08-15 17:27 UTC by khorne3

…criptions

2017-08-16 15:30 UTC, mpaktiti requested changes
Hey Katie, left some comments, let me know what you think

2017-08-16 15:30 UTC, mpaktiti commented on articles/api-auth/tutorials/authorization-code-grant-pkce.md
> +* Set the [Default Audience and/or Default Directory](/dashboard-account-settings#api-authorization-settings)
To my knowledge, the Default Directory is only relevant to the Password Grant

2017-08-16 15:30 UTC, mpaktiti commented on articles/api-auth/tutorials/authorization-code-grant.md
> +* Set the [Default Audience and/or Default Directory](/dashboard-account-settings#api-authorization-settings)
To my knowledge, the Default Directory is only relevant to the Password Grant

2017-08-16 15:30 UTC, mpaktiti commented on articles/api-auth/tutorials/client-credentials.md
> +* Set the [Default Audience and/or Default Directory](/dashboard-account-settings#api-authorization-settings)
To my knowledge, the Default Directory is only relevant to the Password Grant

2017-08-16 15:30 UTC, mpaktiti commented on articles/api-auth/tutorials/implicit-grant.md
> +* Set the [Default Audience and/or Default Directory](/dashboard-account-settings#api-authorization-settings)
To my knowledge, the Default Directory is only relevant to the Password Grant

2017-08-16 15:30 UTC, mpaktiti commented on articles/api-auth/tutorials/authorization-code-grant-pkce.md
> +* Set the [Default Audience and/or Default Directory](/dashboard-account-settings#api-authorization-settings)
I'm wondering whether this last bullet should be there (and all other docs in this PR). It's not actually a prerequisite, it's something that the users can do optionally. You could convert this panel to a paragraph and add a note saying that optionally they can set this and that.

2017-08-16 15:30 UTC, mpaktiti commented on articles/api-auth/tutorials/authorization-code-grant-pkce.md
> +* Set the Client's [Grant Type property](/clients/client-grant-types)
I'm not sure I get this first prerequisite. Yes, depending on the user's case, they might have to enable or disable grant types, but is it actually a prerequisite to do so? The only must-do that I see is create a client and an API.

2017-08-16 19:24 UTC, khorne3 commented on articles/api-auth/tutorials/authorization-code-grant-pkce.md
> +* Set the Client's [Grant Type property](/clients/client-grant-types)
I think the goal is to have all clients have a grant type. You're right in that it's not a must-do, so I changed it to a "check to see if..." kind of thing

2017-08-18 16:36 UTC, mpaktiti approved these changes
Looks good Katie 👍

2017-08-18 16:36 UTC, merged