Update Python Web QS 01 to flask-oauthlib
auth0/docs pull request #4835
Opened 2017-08-16 22:49 UTC by alexisluque

- Remove auth0.js and auth0-python to use Flask-oauthlib
- Using Python Six to provide Python 2 and Python 3 compatibility

2017-08-17 13:56 UTC, aaguiarz commented on articles/quickstart/webapp/python/01-login.md
> +You'll need to create a callback handler so Auth0 will redirect the user after he authenticate and grant the access. This handler exchanges the `code` we have obtained previously for an `access_token
Write it in gender-neutral way: "so Auth0 will redirect users after they authenticate and grant access"

2017-08-17 14:37 UTC, aaguiarz commented
Also, check the format here

https://auth0-docs-content-pr-4835.herokuapp.com/docs/quickstart/webapp/python#-note-the-callback-specified-must-match-the-url-specified-in-the-previous-step-

2017-09-05 01:59 UTC, aaguiarz requested changes
We need to add section that shows the HTML that triggers the login, that was covered in the Auth0.js step in the previous one.

2017-09-15 10:13 UTC, Annyv2 requested changes

2017-09-15 10:13 UTC, Annyv2 commented on articles/quickstart/webapp/python/01-login.md
> +This handler exchanges the `code` that Auth0 sends to the callback URL and exchange for an `access_token`
Remove `and exchange`

2017-09-15 10:13 UTC, Annyv2 commented on articles/quickstart/webapp/python/01-login.md
> +The `id_token` is a [JWT](/jwt) that contains the information of the user profile, to get the information from it you have to decode and validate its signature. After the user information is obtained
Please improve this sentence. There's a typo (then). Also please clarify that the id_token won't have all the user's profile, only OIDC conformant claims (unless you add something else to it from a rule) as explained here https://auth0.com/docs/api-auth/tutorials/adoption/scope-custom-claims

2017-09-15 10:13 UTC, Annyv2 commented on articles/quickstart/webapp/python/01-login.md
> +    idToken = resp['id_token']
Can we use id_token instead?

2017-09-15 10:13 UTC, Annyv2 commented on articles/quickstart/webapp/python/01-login.md
> +## Initialize Flask-OAuthlib
We should explain somewhere around the quickstart that the user is implementing the authorization code grant

2017-09-15 10:13 UTC, Annyv2 commented on articles/quickstart/webapp/python/01-login.md
> +Add a `/login` route that uses `Flask-OAuthlib` client instance to redirect the user to Auth0's hosted login page.
Please add a reference to the hosted login page documentation. Also, typo "That uses the `Flask-Oauthlib`"

2017-09-15 10:13 UTC, Annyv2 commented on articles/quickstart/webapp/python/01-login.md
> +The final destination URL (the `returnTo` value) needs to be in the list of `Allowed Logout URLs`.
Can we improve this sentence a bit? Since it's a note, you can put something like:

Please take into consideration that the return to URL needs to be in the list of `Allowed Logout URLs` in the settings section of the client as explained in [our documentation](https://auth0.com/docs/logout#redirect-users-after-logout)

2017-09-15 10:13 UTC, Annyv2 commented on articles/quickstart/webapp/python/01-login.md
> +Checkout [logout documentation](/logout) for more information.
To log the user out, you have to clear the data from the session and redirect to Auth0's logout endpoint. You can find more information about this in [our logout documentation](link to logout doc)

2017-09-21 03:00 UTC, merged