Adjusted docs related to Lock Passwordless.js [DO NOT MERGE]
auth0/docs pull request #4870
Opened 2017-08-22 20:15 UTC by aaguiarz

LockPasswordless.js and Lock.js were merged, so we can to adjust several samples and docs.

2017-08-23 21:11 UTC, luisrudge requested changes

2017-08-23 21:11 UTC, luisrudge commented on articles/api-auth/intro.md
> +Our new implementation only supports an [OIDC-conformant](/api-auth/tutorials/adoption) passwordless authentication mechanism using the Auth0-hosted login page.
is this correct? I can use pwdless on an embedded lock..

2017-08-23 21:11 UTC, luisrudge commented on articles/connections/passwordless/spa-email-code/v8/index.md
> +Once the user enters the code received by email, Lock will authenticate them trigger the on('authenticated') event where the `id_token` and profile will be available.
change to `trigger the 'authenticated' event`

2017-08-23 21:11 UTC, luisrudge commented on articles/connections/passwordless/spa-sms/v8/index.md
> +If the code is correct, the user will be authenticated. This will trigger the on('authenticated') Lock event where `id_token`, `refresh_token` can be accessed and stored. Then the user will be allowe
change to `trigger the 'authenticated' event`

2017-08-23 21:11 UTC, luisrudge commented on articles/dev-centers/java/index.md
> +- [Sample Project demonstrating Passwordless Authentication, Multifactor Authentication opt-in & account linking](https://github.com/auth0-samples/auth0-spring-mvc-passwordless-mfa-sample): Extends t
change to `in the _README_ `

2017-08-24 00:06 UTC, luisrudge approved these changes

2018-01-23 03:16 UTC, jeffreylees commented
@luisrudge I've updated this to remove merge conflicts, and also removed the `oidcconformant` uses from most places except Lock 10 specific documents. Can you give this a technical review to see if it's needing updating?

2018-01-23 15:37 UTC, luisrudge requested changes

2018-01-23 15:37 UTC, luisrudge commented on articles/connections/passwordless/regular-web-app-email-code/v8/index.md
> +      oidcConformant: true,                    // Forces an OIDC comformant flow
remove `oidcconformant`

2018-01-23 15:37 UTC, luisrudge commented on articles/connections/passwordless/regular-web-app-email-code/v8/index.md
> +          scope: 'openid email'                // Learn about scopes: https://auth0.com/docs/scopes
the new default is `openid profile email`. should we have scopes in the docs at all?

2018-01-23 15:37 UTC, luisrudge commented on articles/connections/passwordless/regular-web-app-email-link/v8/index.md
> +  function login() {
same: oidcconformant & scopes

2018-01-23 15:37 UTC, luisrudge commented on articles/connections/passwordless/regular-web-app-sms/v8/index.md
> +  function login() {
same: oidcconformant & scopes

2018-01-23 15:37 UTC, luisrudge commented on articles/connections/passwordless/spa-email-code/v8/index.md
> +    var lock = new Auth0LockPasswordless('${account.clientId}', '${account.namespace}', {
same: oidcconformant & scopes

2018-01-23 15:37 UTC, luisrudge commented on articles/connections/passwordless/spa-email-code/v8/index.md
> +Once the user enters the code received by email, Lock will trigger the `authenticated` event where the `id_token` and profile will be available.
I think we'll only expose the accessToken, right? Since we're not using responseType:id_token

2018-01-23 15:37 UTC, luisrudge commented on articles/connections/passwordless/spa-email-link/v8/index.md
> +     var lock = new Auth0LockPasswordless('${account.clientId}', '${account.namespace}', {
same: oidcconformant & scopes

2018-01-23 15:37 UTC, luisrudge commented on articles/connections/passwordless/spa-sms/v8/index.md
> +      var lock = new Auth0LockPasswordless('${account.clientId}', '${account.namespace}', {
same: oidcconformant & scopes

2018-01-23 15:37 UTC, luisrudge commented on articles/connections/passwordless/spa-sms/v8/index.md
> +If the code is correct, the user will be authenticated. This will trigger the `authenticated` event where `id_token`, `refresh_token` can be accessed and stored. Then the user will be allowed to cont
same: only accessToken?

2018-01-23 15:37 UTC, luisrudge commented on articles/libraries/lock/v10/index.md
> +First, you'll need to initialize a new `Auth0Lock` object, and provide it with your Auth0 client ID (the unique client ID for each Auth0 client app, which you can get from the [management dashboard](
we should put those changes in the lock@v11 docs. Also, oidcConformant goes away

2018-01-23 15:37 UTC, luisrudge commented on articles/libraries/lock/v10/index.md
> +  '${account.namespace}', { oidcConformant: true }
same: oidcconformant

2018-01-23 15:37 UTC, luisrudge commented on articles/link-accounts/user-initiated-linking.md
> +        oidcConformant: true,
same: oidcconformant

2018-01-23 23:42 UTC, luisrudge approved these changes

2018-01-23 23:50 UTC, luisrudge commented
@jeffreylees should we put a warning about the minimum lock@11 version that will support passwordless?

2018-01-24 00:44 UTC, jeffreylees commented
Yes, good thought

2018-01-24 13:14 UTC, luisrudge commented
Ok cool. You can use 11.2.0 as minimum (it might change until we release)

2018-01-30 14:59 UTC, jeffreylees commented
Updated with version number, also rebased and resolved conflicts.

2018-01-30 23:10 UTC, aaguiarz commented on articles/api-auth/tutorials/adoption/oidc-conformant.md
>        Support for OIDC-conformant passwordless authentication will be added in future releases.
This can be deleted, right? We are adding oidc-conformant pdlwess auth as part of this release

2018-02-02 20:40 UTC, merged