User impersonation copyedit and new images added
auth0/docs pull request #4895
Opened 2017-08-29 00:42 UTC by jeffreylees

2017-09-05 14:40 UTC, mpaktiti requested changes
Hey, I left some comments

2017-09-05 14:40 UTC, mpaktiti commented on articles/user-profile/user-impersonation.md
> +First, you have to generate a token that you can use to call the [Management APIv2](/api/management/v2), specifically the [Impersonation endpoint](/api/authentication/reference#impersonation). This t
The Impersonation endpoint is part of the Authentication API, not Management APIv2

2017-09-05 14:40 UTC, mpaktiti commented on articles/user-profile/user-impersonation.md
> +When impersonating a user in Dashboard, after clicking "Sign in as User" you will see a link to expand "Advanced Settings".
Can you revert this? Use bold for field/button/screen names.

2017-09-05 14:40 UTC, mpaktiti commented on articles/user-profile/user-impersonation.md
> +Impersonating a user using the [Dashboard](${manage_url}) will not return an [ID Token](/tokens/id-token) to your application by default. There are two ways to achieve this. You can alter the "Respon
Use bold for field names, code formatting for values, ie: You can alter the __Response Type__ setting in the impersonation menu's [Advanced Settings](#advanced-settings) from `Code` to `Token` (__Sign in as user__ > __Show Advanced Settings__)

2017-09-05 14:40 UTC, mpaktiti commented on articles/user-profile/user-impersonation.md
> +Navigate to the [Users](${manage_url}/#/users) page in the Management Dashboard and select the user you want to login as. Click on the "Sign in as User: and select the client you want to log into usi
Revert to bold since this is a field

2017-09-05 14:40 UTC, mpaktiti commented on articles/user-profile/user-impersonation.md
> +Any Rules that you've implemented will run when you impersonate a user, including any actions that update the user.
Add link to rules :)

2017-09-05 14:40 UTC, mpaktiti commented on articles/user-profile/user-impersonation.md
> +Impersonation functionality may be disabled by default for your tenant. To check, go to the [Users](${manage_url}/#/users) page in the Dashboard, select a user, and see if the "Sign in as User" butto
Revert to bold since this is a field

2017-09-06 00:20 UTC, jeffreylees commented
@mpaktiti I rewrote/rearranged a good portion of the sample section, as the wording made not a lot of sense to me. Can you take a glance at the changed parts and let me know what you think?

2017-09-06 11:29 UTC, mpaktiti approved these changes
Looks good Jeff! 👍

2017-09-06 11:29 UTC, merged