Add Django QS 01-login
auth0/docs pull request #4915
Opened 2017-08-30 13:52 UTC by alexisluque

2017-09-30 21:10 UTC, aaguiarz approved these changes

2017-10-02 15:46 UTC, jeffreylees requested changes
Just some quick copyedits

2017-10-02 15:46 UTC, jeffreylees commented on articles/quickstart/webapp/django/01-login.md
> +Add the following dependencies to your `requirements.txt` and run `pip install -r requirements.txt`
I might break this out:

> Add the following dependencies to your `requirements.txt`:


and then after the code block, follow it with:

> Once the dependencies are listed in `requirements.txt`, run the following command:

```
pip install -r requirements.txt
```

That way the section flows sequentially - add this stuff, then run this command. Rather than telling them "you'll need to run a command, but after you fill out the requirements".

2017-10-02 15:46 UTC, jeffreylees commented on articles/quickstart/webapp/django/01-login.md
> +## Create a Django project
Most of your H2s are capitalized, so keep the pattern (Create a Django Project)

2017-10-02 15:46 UTC, jeffreylees commented on articles/quickstart/webapp/django/01-login.md
> +Set the `SOCIAL_AUTH_AUTH0_SCOPE` variable with the scopes the application will request when authenticating. Check the [Scopes documentation](scopes/current) for more information.
Missing starting slash: `[Scopes documentation](/scopes/current)`

2017-10-02 15:46 UTC, jeffreylees commented on articles/quickstart/webapp/django/01-login.md
> +The `social_django` application defined in `INSTALLED_APPS` requires a database. Run the following command to create all the required databases for the applications defined in  `INSTALLED_APPS`:
Extra space before `INSTALLED_APPS` here:

> ...defined in `INSTALLED_APPS`

2017-10-02 15:46 UTC, jeffreylees commented on articles/quickstart/webapp/django/01-login.md
> +Up to now we configured `social_django`. The next step is to create an Authentication Backend that bridges `social_django` with Auth0.
Maybe reword: 

> The `social_django` application is now configured. The next step is to create an authentication backend that bridges `social_django` with Auth0.

2017-10-02 15:46 UTC, jeffreylees commented on articles/quickstart/webapp/django/01-login.md
> +Register the authentication backends in `settings.py`. Add the custom backend for `Auth0` and `ModelBackend` to users be able to login with username/password method.
Is this 

> to users be able to login

meant to be 

> for users to be able to login

or something else?

2017-10-02 15:46 UTC, jeffreylees commented on articles/quickstart/webapp/django/01-login.md
> +Add the following snippet to `dashboard.html` to display the [user information](https://auth0.com/docs/user-profile/normalized/oidc).
Use internal URL: `[user information](/user-profile/normalized/oidc)`

2017-10-02 15:46 UTC, jeffreylees commented on articles/quickstart/webapp/django/01-login.md
> +To logout a user, add a link to `/logout` URL in `dashboard.html`.
This sounds better written 

> To log a user out, add a link to `/logout` in `dashboard.html`.

2017-10-02 15:46 UTC, jeffreylees commented on articles/quickstart/webapp/django/01-login.md
> +Add mappins for the root folder, the dashboard folder and the authentication applications in `urls.py`.
"Mappings" typo and Oxford comma

> Add mappings for the root folder, the dashboard folder, and the authentication applications in `urls.py`.

2017-10-02 23:58 UTC, jeffreylees approved these changes

2017-10-03 21:08 UTC, merged