Update 01-authorization.md
auth0/docs pull request #4944
Opened 2017-09-04 21:27 UTC by alexisluque

2017-09-05 00:39 UTC, aaguiarz approved these changes

2017-09-05 10:30 UTC, Annyv2 requested changes

2017-09-05 10:30 UTC, Annyv2 commented on articles/quickstart/backend/python/01-authorization.md
> +your `requirements.txt`:
Remove newline

2017-09-05 10:30 UTC, Annyv2 commented on articles/quickstart/backend/python/01-authorization.md
>  from functools import wraps
Move to standard import section (like it's on the sample)

2017-09-05 10:30 UTC, Annyv2 commented on articles/quickstart/backend/python/01-authorization.md
> +
Remove trailing whitespace

2017-09-05 10:30 UTC, Annyv2 commented on articles/quickstart/backend/python/01-authorization.md
> +
Remove trailing whitespace

2017-09-05 10:30 UTC, Annyv2 commented on articles/quickstart/backend/python/01-authorization.md
>                               "description":
Remove 4 spaces (same comments as the ones posted on the sample)

2017-09-05 10:30 UTC, Annyv2 commented on articles/quickstart/backend/python/01-authorization.md
> +
Remove trailing whitespaces

2017-09-05 10:30 UTC, Annyv2 commented on articles/quickstart/backend/python/01-authorization.md
> +
Remove trailing whitespace

2017-09-05 10:30 UTC, Annyv2 commented on articles/quickstart/backend/python/01-authorization.md
> +    'Six 1.10.0 and up'
Six's latest version seems to be 1.10.0 so `and up` is not needed yet. Also, please use a lowercase format (`six` instead of `Six`)

2017-09-15 07:40 UTC, Annyv2 approved these changes

2017-09-15 18:58 UTC, merged