Add instructions on assigning an environment tag
auth0/docs pull request #5037
Opened 2017-09-21 23:45 UTC by erjohnson

Added instructions on how to assign an environment tag to Client Overview doc.

2017-09-22 10:24 UTC, mpaktiti requested changes
Left some comments for some minor changes. I would also update this doc https://auth0.com/docs/dev-lifecycle/setting-up-env and add a note saying how for each new tenant they create they have to specify also the environment.

2017-09-22 10:24 UTC, mpaktiti commented on articles/clients/index.md
> +To assign an environment tag to a tenant, go to the [Tenants](https://support.auth0.com/tenants/public) page on the [Auth0 Support Center](https://support.auth0.com/). Locate your tenant and click th
Use `${env.DOMAIN_URL_SUPPORT}` instead of `https://support.auth0.com/`

2017-09-22 10:24 UTC, mpaktiti commented on articles/clients/index.md
> +After creating a client, make sure to assign environment tags to your tenants to differentiate between development, staging, and production environments.
This is not a mandatory step each time you create a new client, so I would rephrase `make sure to assign environment tags to your tenants` to sth like make sure that your tenant has the proper environment set.

2017-09-22 10:24 UTC, mpaktiti commented on articles/clients/index.md
> +After creating a client, make sure to assign environment tags to your tenants to differentiate between development, staging, and production environments.
I would also add a note about setting up multiple environments and how the info can be found here https://auth0.com/docs/dev-lifecycle/setting-up-env

2017-09-24 21:03 UTC, erjohnson commented
I moved the how-to section to the Set Up Multiple Environments page, since it seems to fit more there. I can move it back if needed 😄

2017-09-25 09:28 UTC, mpaktiti requested changes
Some more small changes

2017-09-25 09:28 UTC, mpaktiti commented on articles/clients/index.md
> +### Check the Tenant Environment
This paragraph is too much now. Replace it with only a note like this one:

```
::: note
After you create your first client, set the environment for your tenant: development, staging, or production. For more information refer to [Set Up Multiple Environments](/dev-lifecycle/setting-up-env#environment-tags).
:::
```

2017-09-25 09:28 UTC, mpaktiti commented on articles/dev-lifecycle/setting-up-env.md
> +## Environment Tags
Rephrase to `Set the Environment` (the link will change, so update any links pointing here)

2017-09-25 09:28 UTC, mpaktiti commented on articles/dev-lifecycle/setting-up-env.md
> +To assign an environment tag to a tenant, go to the [Tenants](${env.DOMAIN_URL_SUPPORT}tenants/public) page on the [Auth0 Support Center](${env.DOMAIN_URL_SUPPORT}). Locate your tenant and click the
`${env.DOMAIN_URL_SUPPORT}tenants/public` should be `${env.DOMAIN_URL_SUPPORT}/tenants/public`

2017-09-25 09:28 UTC, mpaktiti commented on articles/dev-lifecycle/setting-up-env.md
> +To assign an environment tag to a tenant, go to the [Tenants](${env.DOMAIN_URL_SUPPORT}tenants/public) page on the [Auth0 Support Center](${env.DOMAIN_URL_SUPPORT}). Locate your tenant and click the
Also I would rephrase this to: `go to the [Auth0 Support Center > Tenants](${env.DOMAIN_URL_SUPPORT}/tenants/public).`

2017-09-25 09:28 UTC, mpaktiti commented on articles/dev-lifecycle/setting-up-env.md
> +Next, select the **Assign Environment Tag** option. Use the form to identify your tenant's environment as either **Development**, **Staging**, or **Production**.
Use bold for field names and code marking for values: `Development`, `Staging`, or `Production`

2017-09-25 09:28 UTC, mpaktiti commented on articles/dev-lifecycle/setting-up-env.md
> +If your tenant is mixed use, choose the higher environment. For example, a tenant used for both development and production should be set to **Production**.
`Production`

2017-09-26 15:08 UTC, merged

2017-09-26 15:08 UTC, mpaktiti commented
Looks good 👍