Update laravel backend API QS
auth0/docs pull request #5046
Opened 2017-09-25 19:37 UTC by cocojoe

Added comment to specify file to missing snippets
Fixed app binding values

2017-09-27 21:42 UTC, aaguiarz commented
I tried to run it, by adding the MyCustomUserRepository file and the bindings in AppServiceProvider.

When I hit the /api/private endpoint, I get:

"message": "Class 'App\\Repository\\User' not found",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
    "file": "/home/app/app/Repository/MyCustomUserRepository.php",
    "line": 27,

I'm using this script to call the API, if it helps

AUTH0_DOMAIN=..
AUTH0_AUDIENCE=..
AUTH0_CLIENT_ID=..
AUTH0_CLIENT_SECRET=..
API_ENDPOINT=http://localhost:8000/api/private 

ACCESS_TOKEN=$(curl --request POST --url https://$AUTH0_DOMAIN/oauth/token  -H 'content-type: application/json'  -H 'Accept: application/json' --data '{"client_id":"'"$AUTH0_CLIENT_ID"'", "client_secret":"'"$AUTH0_CLIENT_SECRET"'","audience":"'"$AUTH0_AUDIENCE"'","grant_type":"client_credentials"}' | jq -r ".access_token")

curl --url $API_ENDPOINT -H 'authorization: Bearer '$ACCESS_TOKEN -H 'content-type: application/json'  -H 'Accept: application/json'

2017-09-27 21:44 UTC, aaguiarz requested changes
Left a comment. I'm using the docker image FWIW

2017-09-28 08:28 UTC, cocojoe commented
Can you show me contents of your `MyCustomUserRepository.php` thx

2017-09-29 13:37 UTC, aaguiarz approved these changes

2017-09-29 13:37 UTC, merged