Update reference to correct sample
auth0/docs pull request #5150
Opened 2017-10-16 16:03 UTC by khorne3

2017-10-17 09:21 UTC, mpaktiti requested changes

2017-10-17 09:21 UTC, mpaktiti commented on articles/sso/current/index.md
> +Please see the [Auth0 OIDC SSO Sample](https://github.com/auth0-samples/oidc-sso-sample) repo for an example of how to implement OIDC-compliant SSO.
Forgot some markup:

![image](https://user-images.githubusercontent.com/11715799/31656828-7f22e4fc-b335-11e7-9fb8-99de2824cb66.png)

Keep in mind to always check the review app, especially when you are editing visual elements like notes and panels.

2017-10-17 09:21 UTC, mpaktiti commented on articles/sso/current/index.md
>  * [Client-Side SSO (Single Page Apps)](/sso/current/single-page-apps-sso)
You need to also update the text before the sample, since it still describes the old sample (uses the `getSSOData()` function, which is legacy)

2017-10-18 16:15 UTC, khorne3 commented
@mpaktiti  I pushed the commits, so it should work better now. :)

2017-10-19 08:58 UTC, mpaktiti approved these changes

2017-10-19 08:59 UTC, merged