Update react-native docs
auth0/docs pull request #5219
Opened 2017-10-31 16:31 UTC by paulioceano

Fix #4705

2017-11-02 09:38 UTC, cocojoe requested changes
In general please be consistent with the formatting in some cases it is `//comment` others `// comment` I prefer the space.

2017-11-02 09:38 UTC, cocojoe commented on articles/quickstart/native/react-native/_includes/_login.md
> +//android/app/src/main/java/com/auth0sample/MainActivity.java
This is not correct, the `MainActivity` is a sub section inside the `//android/app/src/main/AndroidManifest.xml`

2017-11-22 01:23 UTC, aaguiarz requested changes
@paulioceano check @cocojoe's comments

2017-12-28 10:24 UTC, cocojoe commented
@aaguiarz can this be assigned to the 3DI guys to complete?

2018-10-17 11:51 UTC, albertoperdomo commented
Requested changes have been addressed in PR #5749. Closing this one.

2018-10-17 11:51 UTC, closed without merging

2018-10-18 11:34 UTC, cocojoe commented
ok