Update User Search Options Doc
auth0/docs pull request #5279
Opened 2017-11-16 18:15 UTC by khorne3

2017-12-06 16:26 UTC, cabralmartin commented on articles/users/search.md
> +We do **not** recommend using the Users by ID endpoint for searches returning multiple users.
Remove (Redundant). Get by ID can only return one result.

2017-12-06 16:26 UTC, cabralmartin commented on articles/users/search.md
> +We do **not** recommend using the Users by Email endpoint for searches returning multiple users.
Same as above.

2017-12-06 16:26 UTC, cabralmartin commented on articles/users/search.md
> +Please **avoid**:
Lets remove this `Please avoid` section. If the product supports this it looks weird we ask the user to "avoid" using.

2017-12-07 09:31 UTC, mpaktiti requested changes
Looks good, left a couple of minor comments

2017-12-07 09:31 UTC, mpaktiti commented on articles/users/search.md
> +* Use an immediately consistent endpoint during authentication pipeline
I don't get this sentence. What's `during authentication pipeline`? You probably mean something like authentication transaction?

2017-12-07 09:31 UTC, mpaktiti commented on articles/users/search.md
> +Successful calls to the endpoint returns a JSON object similar to the following:
Typo: `Successful calls to the endpoint returns a JSON object`

2017-12-07 09:31 UTC, mpaktiti commented on articles/users/search.md
> +* User searches run during the authentication/authorization process
Here you use `authentication/authorization process`. It's clearer than `authentication pipeline`. I also think you could lose the `/authorization` and simplify more.

2017-12-07 09:31 UTC, mpaktiti commented on articles/users/search.md
> +| Actions requiring user search as part of the Authentication Pipeline | [Users by ID](#users-by-id) or [Users by Email](#users-by-email) |
Same comment on the `Authentication Pipeline`. Use a consistent term throughout the doc.

2017-12-08 09:46 UTC, merged