Replacing the term 'centralized login' with 'universal login'
auth0/docs pull request #5539
Opened 2018-01-04 02:55 UTC by jeffreylees

2018-01-09 16:47 UTC, aaguiarz commented on articles/guides/login/_includes/_customizing-login-page.md
"Customizing the Login Page"

2018-01-09 16:47 UTC, aaguiarz commented on articles/guides/login/centralized-vs-embedded.md
> +You can use **Auth0's Custom Domains** in order to persist the same domain across the universal login page and the app. This way the redirect to the HLP will be transparent to your users since the do
change "in order to persist the same domain across the universal login page" to "in order to persist the same domain across the login page"

change "HLP" to "login page"

2018-01-09 16:47 UTC, aaguiarz commented on articles/libraries/lock/v10/configuration.md
Maybe in places like this we can say "implementing universal [login](/hosted-pages/login)" instead of 'with a login page'.

2018-01-09 16:47 UTC, aaguiarz commented on articles/libraries/when-to-use-lock.md
> +Passwordless authentication from native mobile apps currently must use univeral login - there is no native passwordless option at this time.
typo, says "univeral"

2018-01-09 16:47 UTC, aaguiarz commented on articles/sso/current/index.md
>  :::
This is not accurate, the COA page does not help much in safely conduct SSO. However, there have been a lot of conversations regarding SSO in Embedded scenarios, we need to still iterate on finding the best way to communicate it.

2018-02-16 11:05 UTC, mpaktiti requested changes

2018-02-16 11:05 UTC, mpaktiti commented on articles/api-auth/passwordless.md
> +<<<<<<< HEAD
That doesn't look good. Conflict resolution went bad?

2018-02-16 11:05 UTC, mpaktiti commented on articles/guides/login/centralized-vs-embedded.md
> +<<<<<<< HEAD
same

2018-02-16 11:05 UTC, mpaktiti commented on articles/hosted-pages/login/lock.md
> +* [Get Started on Your Own Login Page](${manage_url}/#/login_page)
why use title-case here? `Get started on your own login page`

2018-02-16 11:05 UTC, mpaktiti commented on articles/libraries/auth0-android/index.md
> +First go to [Auth0 Dashboard](${manage_url}/#/clients) and go to your client's settings. Make sure you have in **Allowed Callback URLs** a URL with the following format:
`Dashboard`, that's what we are supposed to be using

2018-02-16 11:05 UTC, mpaktiti commented on articles/libraries/auth0-android/index.md
> +To ensure an Open ID Connect compliant response you must either set an `audience` using [withAudience](/libraries/auth0-android/configuration#withAudience) or enable the **OIDC Conformant** switch in
`here` at links is a no-no

2018-02-16 11:05 UTC, mpaktiti commented on articles/libraries/auth0-android/index.md
> +To ensure an Open ID Connect compliant response you must either set an `audience` using [withAudience](/libraries/auth0-android/configuration#withAudience) or enable the **OIDC Conformant** switch in
also this `Client / Settings / Advanced OAuth` should be `**Dashboard > Settings > Advanced > OAuth**`

2018-02-16 11:05 UTC, mpaktiti commented on articles/libraries/auth0js/v9/migration-guide.md
> +<<<<<<< HEAD
conflict resolution gone bad

2018-02-16 11:05 UTC, mpaktiti commented on articles/libraries/auth0js/v9/migration-guide.md
> +=======
conflict resolution gone bad

2018-02-16 11:05 UTC, mpaktiti commented on articles/libraries/auth0js/v9/migration-guide.md
> +>>>>>>> Replacing the term 'centralized login' with 'universal login'
conflict resolution gone bad

2018-02-16 11:05 UTC, mpaktiti commented on articles/libraries/lock/v11/migration-guide.md
> +<<<<<<< HEAD
conflict resolution gone bad

2018-02-16 11:05 UTC, mpaktiti commented on articles/quickstart/native/ios-swift/03-user-sessions.md
> +First, import the `Auth0` module to the file from which you wish to present the login page:
simplify: `to the file from which you wish to present the login page` --> `to the file that will present the login page`

2018-02-19 22:54 UTC, jeffreylees commented
Fixed merging issues, searched the whole repo for any remaining markers, also handled recent merge conflicts.

2018-02-22 16:20 UTC, merged