Database connection updates
auth0/docs pull request #5571
Opened 2018-01-10 17:13 UTC by erjohnson

2018-01-12 12:22 UTC, mpaktiti requested changes
This looks good 👍  left some comments for some improvements

2018-01-12 12:22 UTC, mpaktiti commented on articles/connections/database/custom-db.md
> +* The [Update Users using a Custom Database](/user-profile/customdb) article has information on updating user profile fields.
maybe rename this article also to `Update Users using your Database`?

2018-01-12 12:22 UTC, mpaktiti commented on articles/connections/database/custom-db.md
> +Create the required Login script to authenticate users. The Login script will run each time a user attempts to log in. You can write your own Login script or select a template from the **Templates**
The first sentence seems redundant `Create the required Login script to authenticate users.`

2018-01-12 12:22 UTC, mpaktiti commented on articles/connections/database/custom-db.md
> +Store the credentials required to connect to your database in the **Settings** section below the script editor. Parameters stored there are available in all of your scripts.
I would add a `You can` at the beginning of the sentence.

2018-01-12 12:22 UTC, mpaktiti commented on articles/connections/database/custom-db.md
>  ![](/media/articles/connections/database/mysql/db-connection-configurate.png)
add alt text please (same goes for all images)

2018-01-12 12:22 UTC, mpaktiti commented on articles/connections/database/custom-db.md
> +You can access parameter values using the `configuration` object in your database action scripts, for example: `configuration.PARAMETER_NAME`.
Maybe replace `PARAMETER_NAME` with the example of the screenshot below? `MYSQL_PASSWORD`

2018-01-12 12:22 UTC, mpaktiti commented on articles/connections/database/custom-db.md
> +Heads up! You can use this section to store values which are available in all scripts.
You kind of mention this earlier `Parameters stored there are available in all of your scripts.`

I would remove these two sentences and update the first two paragraphs to sth like `You can store parameters, like the credentials required to connect to your database, in the Settings section below the script editor. These will be available to all of your scripts and you can access them using the global configuration object.`. Then you can have the MYSQL_PASSWORD example. Note that the screenshot only shows 1 param (password) while the script has 2 (password, host). I'd align these two.

2018-01-12 12:22 UTC, mpaktiti commented on articles/connections/database/custom-db.md
>  To return an error, call the callback with an error as the first parameter:
I would start this paragraph with the `There are three different errors...` and after the bullets have this sentence (`To return an error, call the callback with an error as the first parameter`) and the example (`callback(new ValidationError('email-too-long', 'Email is too long.'));`

2018-01-12 12:22 UTC, mpaktiti commented on articles/connections/database/custom-db.md
>  If you add a `console.log` statement to the script you will be able to see the output here.
Maybe enhance this a bit? Something like `If you do not get the expected result, you can use console.log statements in your script and try the connection again. The output of these statements will be printed in this window`

2018-01-12 12:22 UTC, mpaktiti commented on articles/connections/database/custom-db.md
> +After you enabling the database connection, the Auth0 Login widget will automatically change its appearance to allow users to enter their `username` and `password`. Once entered, this data is passed
`after you enabling` does not make sense to me. maybe `after you enable`?

Also this section is applicable only if you use Lock. We should clarify this. Also, I don't get why we format the `username` and `password` as code.

2018-01-12 16:59 UTC, erjohnson commented on articles/connections/database/custom-db.md
> +* The [Update Users using a Custom Database](/user-profile/customdb) article has information on updating user profile fields.
Good idea

2018-01-16 11:38 UTC, merged

2018-02-08 23:37 UTC, erjohnson commented on articles/connections/database/custom-db.md
>  ---
test

2018-02-08 23:38 UTC, erjohnson commented on articles/connections/database/custom-db.md
> +In this tutorial you'll learn how to connect your user database to Auth0 and configure it as an identity provider.
test