Adding version warnings to any versioned doc w/ deprecated Lock/Auth0.js
auth0/docs pull request #5709
Opened 2018-02-08 20:17 UTC by jeffreylees

2018-02-09 13:44 UTC, mpaktiti requested changes
The review app does not work https://auth0-docs-content-pr-5709.herokuapp.com/

2018-02-09 13:45 UTC, jeffreylees commented
Of course it doesn't :grin:

Will look into it

2018-02-12 21:05 UTC, mpaktiti requested changes
Jeff, please list also all the review app URLs I should check. I know that it is troublesome but if you don't do it then I have to search and see what has been updated. Thanks.

2018-02-12 21:05 UTC, mpaktiti commented on articles/connections/passwordless/regular-web-app-email-code/v8/index.md
> +<%= include('../../../../_includes/_version_warning_auth0js') %>
`version-warning` can be used only under a version dropdown (that is, at the top of the page).
If the warning is in the middle of the doc you have to use a `warning`

2018-02-12 21:05 UTC, mpaktiti commented on articles/connections/passwordless/regular-web-app-email-code/v8/index.md
> +<%= include('../../../../_includes/_version_warning_auth0js') %>
This is not the only place so please go through all the files and double check

2018-02-13 03:17 UTC, jeffreylees commented
@mpaktiti 

I fixed the panels - all version pages have version-warnings in the appropriate places now.

I added the links to the connections/passwordless docs to the description.

Each versioned page underneath of Lock v9 and v10 are also included identically, but I assumed you didn't want another twenty or so links -  I can go through and list them if you need them though.

2018-02-13 16:20 UTC, mpaktiti requested changes
Hey, I left some comments. I didn't check all of the docs, so please make sure that any adjustments are applied everywhere.

2018-02-13 16:20 UTC, mpaktiti commented on articles/connections/passwordless/regular-web-app-email-link/v7/index.md
> +<%= include('../../../../_includes/_version_warning_auth0js' %>
The warning says that they should migrate to Auth0.js v9 asap, but [the snippet already uses v9](https://auth0-docs-content-pr-5709.herokuapp.com/docs/connections/passwordless/regular-web-app-email-link/v7#use-your-own-ui)

2018-02-13 16:20 UTC, mpaktiti commented on articles/connections/passwordless/regular-web-app-email-code/v7/index.md
> +<%= include('../../../../_includes/_version_warning_auth0js' %>
Script uses v9 already https://auth0-docs-content-pr-5709.herokuapp.com/docs/connections/passwordless/regular-web-app-email-code/v7#use-your-own-ui

2018-02-13 16:20 UTC, mpaktiti commented on articles/connections/passwordless/regular-web-app-email-link/v7/index.md
> +<%= include('../../../../_includes/_version_warning_auth0js' %>
I also think this is confusing one way or another. What if someone does not use the custom UI option and he sees this panel telling him to upgrade to Auth0.js v9? For mixed docs (those that include both Lock and Auth0.js) the message should be different (or it should be a `warning` under each respective title)

2018-02-13 16:20 UTC, mpaktiti commented on articles/connections/passwordless/regular-web-app-sms/v7/index.md
> +<%= include('../../../../_includes/_version_warning_auth0js' %>
script already uses v9 https://auth0-docs-content-pr-5709.herokuapp.com/docs/connections/passwordless/regular-web-app-sms/v7#use-your-own-ui (plus there is a Lock section before that)

2018-02-16 11:56 UTC, mpaktiti requested changes
Headers level mess up. Also, since we removed so many docs, can you please add an update feed entry? No need to mention the warnings you added on the other docs, but you should mention the versions that were removed.

2018-02-16 11:56 UTC, mpaktiti commented on articles/connections/passwordless/regular-web-app-email-code.md
> +<%= include('_setup-email') %>
this is H4, while the `Setup` is H2

2018-02-16 11:56 UTC, mpaktiti commented on articles/connections/passwordless/regular-web-app-email-code.md
> +<%= include('_setup-callback', {spa:false} )%>
same, goes from H2 to H4

2018-02-16 11:56 UTC, mpaktiti commented on articles/connections/passwordless/regular-web-app-email-link.md
> +<%= include('_setup-email') %>
goes from H2 to H4

2018-02-16 11:56 UTC, mpaktiti commented on articles/connections/passwordless/regular-web-app-email-link.md
> +<%= include('_setup-callback', {spa:false} ) %>
goes from H2 to H4

2018-02-16 11:56 UTC, mpaktiti commented on articles/connections/passwordless/regular-web-app-sms.md
> +<%= include('_setup-sms-twilio') %>
gos from H2 to H4

2018-02-16 11:56 UTC, mpaktiti commented on articles/connections/passwordless/regular-web-app-sms.md
> +<%= include('_setup-callback', {spa:false} ) %>
gos from H2 to H4

2018-02-16 11:56 UTC, mpaktiti commented on articles/connections/passwordless/spa-email-code.md
> +<%= include('_setup-email') %>
gos from H2 to H4

2018-02-16 11:56 UTC, mpaktiti commented on articles/connections/passwordless/spa-email-code.md
> +<%= include('_setup-cors') %>
gos from H2 to H4

2018-02-16 11:56 UTC, mpaktiti commented on articles/connections/passwordless/spa-email-link.md
> +<%= include('_setup-email') %>
goes from H2 to H4

2018-02-16 11:56 UTC, mpaktiti commented on articles/connections/passwordless/spa-email-link.md
> +<%= include('_setup-callback', {spa:true} ) %>
goes from H2 to H4

2018-02-16 11:56 UTC, mpaktiti commented on articles/connections/passwordless/spa-sms.md
> +<%= include('_setup-sms-twilio') %>
goes from H2 to H4

2018-02-16 11:56 UTC, mpaktiti commented on articles/connections/passwordless/spa-sms.md
> +<%= include('_setup-cors') %>
goes from H2 to H4

2018-02-22 15:10 UTC, merged