Rewriting and formatting
auth0/docs pull request #5804
Opened 2018-02-28 16:28 UTC by vatechnology

2018-03-05 23:44 UTC, joshcanhelp commented
@vatechnology - thank you for the feedback here. I left a few review comments and @mpaktiti will probably have another round once this is technically correct. 

I am, however, a little hesitant to update this at all. This is essentially a walk-through of all the logic that's already available in the plugin code:

https://github.com/auth0/wp-auth0

I'm wondering if there is much of an audience for someone who wants a technical walk-through but is not able to read the code. It seems like these scenarios could be found just by testing the current version. 

Interested to hear your perspective ... thanks again!

2018-04-16 12:23 UTC, mpaktiti commented
Hi @vatechnology ! Any news on this? Btw I'll add a `do-not-merge` label in this PR so it doesn't show up on my daily to-review list, when you address the comments Josh made please ping me so I can review. Thanks!

2018-04-16 14:34 UTC, joshcanhelp requested changes

2018-04-16 14:34 UTC, joshcanhelp commented on articles/cms/wordpress/how-does-it-work.md
> +###  Case 1: Login attempt by user who exists in Auth0 but not in WordPress
"Login attempt by a user ..."

2018-04-16 14:34 UTC, joshcanhelp commented on articles/cms/wordpress/how-does-it-work.md
> +#### Solution : Auth0 creates a new user profile on WordPress and logs the user in.
Auth0 doesn't create it, the plugin does based on a successful login/registration. I would also say "creates a new user in WordPress," profile might be confusing.

2018-04-16 14:34 UTC, joshcanhelp commented on articles/cms/wordpress/how-does-it-work.md
> +1. The user tries to login to your WordPress site using their login credentials.
This is a little confusing since they are actually logging into Auth0 once the plugin is active and configured.

2018-04-16 14:34 UTC, joshcanhelp commented on articles/cms/wordpress/how-does-it-work.md
> +3. Next the Auth0-WordPress plugin checks to see if there is a user in the WordPress database with credentials that match their Auth0 `user_id`. There are two possibilities here -
* Remove "Next"
* "Auth0-WordPress plugin" - formal name is "Login by Auth0," I think "the plugin" will suffice in this case
* "... to see if there is a user in the WordPress database with their Auth0 `user_id`"

2018-04-16 14:34 UTC, joshcanhelp commented on articles/cms/wordpress/how-does-it-work.md
> +# Auth0-WordPress Integration
"Auth0-WordPress" feels like a formal name, which, in this case, is incorrect. I would keep as-is.

2018-04-16 14:34 UTC, joshcanhelp commented on articles/cms/wordpress/how-does-it-work.md
> +3. Next the Auth0-WordPress plugin checks to see if there is a user in the WordPress database with credentials that match their Auth0 `user_id`. There are two possibilities here -
I am just now noticing that "Auth0-WordPress" is in the original text :)

2018-04-16 14:34 UTC, joshcanhelp commented on articles/cms/wordpress/how-does-it-work.md
> +   >(What happens if the email address does not match ? Does the user get notified that the user id is taken ?)
_"What happens if the email address does not match? Does the user get notified that the user id is taken?"_ - If the email does not match, then WordPress is updated with the Auth0 email address (we assume that Auth0 is the source of truth for identity once the plugin is running). The second sentence could probably be removed since it sounds like a condition of logging in.

2018-04-16 14:34 UTC, joshcanhelp commented on articles/cms/wordpress/how-does-it-work.md
> +#### Solution : Login successful if either 'user_id' or 'email'(w verification) match.
Login is successful if either the 'user_id' or 'email' (with verification) matches what comes from Auth0.

2018-04-16 14:34 UTC, joshcanhelp commented on articles/cms/wordpress/how-does-it-work.md
> +### Case 3: Login attempt by user who exists in Auth0 and a newly-created WordPress user.
I don't know that this third case is really all that helpful, it sounds a bit like one of the conditions of the first scenario. I know that's on us :)

Seems like the 4 scenarios are:

1. Not in WP, not in Auth0
2. In WP, not in Auth0
3. Not in WP, in Auth0
4. In WP, in Auth0

... and then data migration is a bit of an outlier.

2018-11-02 15:02 UTC, khorne3 commented
Closing due to inactivity. Would be happy to chat about picking up this work again if necessary.

2018-11-02 15:02 UTC, closed without merging