Migration custom domains
auth0/docs pull request #5849
Opened 2018-03-06 21:29 UTC by jeffreylees

2018-03-08 16:31 UTC, aaguiarz approved these changes

2018-03-09 10:36 UTC, mpaktiti requested changes

2018-03-09 10:36 UTC, mpaktiti commented on articles/libraries/_includes/_configure_custom_domain.md
> +### Configure Your Custom Domain
Change to `Configure your custom domain`

2018-03-09 10:36 UTC, mpaktiti commented on articles/libraries/_includes/_configure_custom_domain.md
> +Make sure that your application changes are made prior to setting up Custom Domains in your application, as the older versions of ${library} will not work with a custom domain set at initialization,
I really don't think we should capitalize `Custom Domain`.

2018-03-09 10:36 UTC, mpaktiti commented on articles/libraries/_includes/_configure_custom_domain.md
> +Set up your [Custom Domain](/custom-domains). Once the custom domain is set up, remember to make the following changes in your Lock instantiation:
Custom Domain -> custom domain

2018-03-09 10:36 UTC, mpaktiti commented on articles/libraries/_includes/_configure_custom_domain.md
> +Set up your [Custom Domain](/custom-domains). Once the custom domain is set up, remember to make the following changes in your Lock instantiation:
I would add this as a first step and remove the note before that.

1. Set up your [custom domain](/custom-domains). It is crucial that this step is completed first, otherwise you will get a `404` error since older versions of ${library} do not work with custom domains.

2018-03-09 10:36 UTC, mpaktiti commented on articles/libraries/_includes/_configure_custom_domain.md
> +	configurationBaseUrl: 'https://cdn.auth0.com'
This would look better with a double space instead of tab

2018-03-09 10:36 UTC, mpaktiti commented on articles/libraries/_includes/_configure_custom_domain.md
> +If you intend to use the Auth0.js `auth0.Management` to get user information or perform account linking operations (see the Auth0.js documentation on [user management](/libraries/auth0js/v9#user-mana
The text in the parenthesis should be a separate sentence at the end of the paragraph.

`See the Auth0.js documentation on [user management](/libraries/auth0js/v9#user-management) for more information on using the Management API in Auth0.js`

2018-03-09 10:36 UTC, mpaktiti commented on articles/custom-domains/index.md
> +If you use custom domains and intend to perform [management API actions with Auth0.js](/libraries/auth0js/v9#user-management), you will need to instantiate a new copy of `webAuth` using your Auth0 do
I don't think a note is needed here, you can have it as simple text (I've had complaints from design that we overuse them, which is true, and it beats the purpose - everything is calling for attention so none gets any).

I'd also start the sentence with stating the problem and then the workaround (sth like `Note that the Management API only accepts Auth0 domains. If you use [custom domains](/custom-domains) and intend to perform [Management API actions with Auth0.js](/libraries/auth0js/v9#user-management), you must instantiate a new copy of `webAuth` using your Auth0 domain.`)

2018-03-16 17:33 UTC, mpaktiti requested changes

2018-03-16 17:33 UTC, mpaktiti commented on articles/libraries/_includes/_configure_custom_domain.md
> +}
This needs a `;` at the end

2018-03-16 17:33 UTC, mpaktiti commented on articles/libraries/_includes/_configure_custom_domain.md
> +var lock = new Auth0Lock('your-client-id', 'login.northwind.com', options);
That's the first time we see `login.northwind.com` in the article, and it made me stop and think for a moment. Maybe replace it with sth like `login.your-domain.com`?
Also use client ID var.

2018-03-16 17:33 UTC, mpaktiti commented on articles/libraries/_includes/_configure_custom_domain.md
> +The CDN URL varies by region. For regions outside of the US, use `https://cdn.{region}.auth0.com`.
maybe add parenthesis at the end that clarifies the regions? sth like `use eu from Europe, au for Australia`

2018-03-16 17:51 UTC, merged