Restructure user search section
auth0/docs pull request #5900
Opened 2018-03-19 03:50 UTC by erjohnson

2018-03-20 18:15 UTC, siacomuzzi commented
please review/merge this too: https://github.com/auth0/api2/pull/2299

2018-03-28 11:34 UTC, mpaktiti requested changes
If I go to https://auth0-docs-content-pr-5900.herokuapp.com/docs/users/search (using the menu User Management > User Search) it throws an error.
(versioning bug, you need to add a specific version to the sidebar URL)

Also, this is under Articles without breadcrumbs
https://auth0-docs-content-pr-5900.herokuapp.com/docs/users/search/v3
and I use the versioning dropdown to go to v2, it is under APIs https://auth0-docs-content-pr-5900.herokuapp.com/docs/users/search/v2

Can you fix those and check the review app that all work ok? It should all be under Articles, with breadcrumbs, and working menus.

2018-04-04 16:17 UTC, erjohnson commented
In my local build, switching versions switches the sections from users management to api v2?

2018-04-05 17:16 UTC, mpaktiti commented
@erjohnson It does change versions but it also changes tabs (v3 under Articles, v2 under APIs). Probably because the v2 doc has still the metadata `section: apis`, if you remove it it should work.

2018-04-05 17:17 UTC, mpaktiti commented
@erjohnson One more thing, if I click on `Query Syntax` (articles sidebar menu: User Management > User Search > Query Syntax) I get a 404 
https://auth0-docs-content-pr-5900.herokuapp.com/docs/users/search/query-sytax

2018-04-10 14:55 UTC, mpaktiti commented on articles/users/search/v2/index.md
>  ---
Just a note that we do not have a version-warning panel here. Not sure if we want to that's why I'm not asking for the change.

2018-04-10 15:00 UTC, mpaktiti requested changes
Looks good Eric, just a couple of items to address and it's good to go.

2018-04-10 15:00 UTC, mpaktiti commented on articles/users/search/v3/index.md
> -
Can you add a next-steps element at the end of this doc, listing these two?
articles/users/search/v3/query-syntax.md
articles/users/search/v3/best-practices.md

Add it on its own section, like `Keep reading`

2018-04-10 15:00 UTC, mpaktiti commented on config/redirects.js
> +    to: '/users/search'
Since these two do not have the `v2` in the URL, they will redirect to the default one, which is v3. Is this intentional?

2018-04-11 09:05 UTC, mpaktiti commented on articles/users/search/v2/index.md
> +This document covers a previous version of user search. We recommend you use <a href="/users/search/v3">user search v3</a>.
@erjohnson For future reference, you don't have to use HTML within the UI elements, you can use Markdown and the result is the same. I'm going to fix these two for you and merge.

2018-04-11 09:13 UTC, mpaktiti approved these changes
Thanks for all the changes @erjohnson. This looks good so I'm gonna go ahead and merge. Two notes on some changes I pushed:
- In the version-warning panels for the v2 docs, you used HTML for the links. I replaced it with Markdown. This stand for all UI elements, you don't have to use HTML.
- I changed the titles for the articles at the next-steps section of v3 to sth more descriptive. Our titles are often obscure so using part of the article's description metadata is more clear.

2018-04-11 09:25 UTC, merged

2018-04-11 13:31 UTC, siacomuzzi commented
why `User Search Best Practices` is under `search engine v3` (`/users/search/v3/best-practices`)?

2018-04-11 15:18 UTC, siacomuzzi commented
also, why `/users/search/v2/query-syntax` and `/users/search/v3/best-practices` are hidden?

2018-04-11 15:31 UTC, siacomuzzi commented
![image](https://user-images.githubusercontent.com/178506/38626982-33df2b02-3d84-11e8-9a4a-585975768481.png)

is this OK? https://auth0.com/docs/users/search/v3#example-request

2018-04-11 17:33 UTC, siacomuzzi commented
please move `Searchable Fields` to the right place:

* `v2`: https://auth0.com/docs/users/search/v2#searchable-fields
* `v3`: https://auth0.com/docs/users/search/v3/query-syntax#searchable-fields

2018-04-11 17:40 UTC, siacomuzzi commented
same for "Search using ranges" section:

* `v2`: https://auth0.com/docs/users/search/v2#search-using-ranges
* `v3`: https://auth0.com/docs/users/search/v3/query-syntax#ranges

could you please review all documents (`/users/search/v2`, `/users/search/v3`, `/users/search/v2/query-syntax`, `/users/search/v3/query-syntax`)? Just to make sure we have all sections in the same place