Account linking updates
auth0/docs pull request #5930
Opened 2018-03-26 17:58 UTC by mpaktiti

Due to the [deprecation of ID Tokens as authentication credentials for the Mgmt API](https://auth0.com/docs/migrations#deprecating-the-usage-of-id-tokens-on-the-auth0-management-api), the account linking docs need to be updated. 

Some other changes are introduced to the processes as well.

### High-level description of the new processes:

**Admin account linking**
* Requires an admin token (`update:user`) scope
* Can send `user_id` in payload
* Can send `id_token` in payload

**End user account linking**
* Requires an end user token (`update:current_user`) scope
* CANNOT send `user_id` in payload
* Can send `id_token` in payload *BUT*:
  * The `id_token` needs to the signed with RS256
  * The `aud` claim in the `id_token` must identify the client, and be the same client that is the `azp` of the access token used to make the request

### PR changes summary
- [x] Remove article [Link Accounts using Authentication API (Deprecated)](https://auth0.com/docs/link-accounts/auth-api) since the Mandatory Opt-In date for this migration has long passed (`2017-03-01`). Adding a redirect to the main Account Linking doc
- [x] Update **Linking User Accounts** doc with new flows
- [x] Update **Linking User Accounts** doc with section on Auth0.js and how to use it for account linking
- [x] Update **Account Linking Using Server Side Code** doc: remove guidance for embedded Lock and advise for universal login instead, copyedits
- [x] Update **User Initiated Account Linking** doc: update title to **Account Linking Using Client Side Code** for consistency, update snippets with new flow, copyedits
- [x] Migration guide for Account Linking

### Review app
- [Linking User Accounts](https://auth0-docs-content-pr-5930.herokuapp.com/docs/link-accounts)
- [Account Linking Using Client Side Code](https://auth0-docs-content-pr-5930.herokuapp.com/docs/link-accounts/user-initiated-linking)
- [Account Linking Using Server Side Code](https://auth0-docs-content-pr-5930.herokuapp.com/docs/link-accounts/suggested-linking)
- [Migration Guide: Account Linking and ID Tokens](https://auth0-docs-content-pr-5930.herokuapp.com/docs/migrations/guides/account-linking)

2018-03-30 16:53 UTC, mpaktiti commented
@cabralmartin I'm still working on the migration guide but since this has been enabled for new customers by default, I thought we could decouple these two: have you review these updates, while I'm working on the migration guide on another PR.

2018-04-02 15:01 UTC, mpaktiti commented
@cabralmartin Migration guide added

2018-04-20 20:23 UTC, cabralmartin requested changes

2018-04-20 20:23 UTC, cabralmartin commented on articles/link-accounts/suggested-linking/index.md
> +To get a list of all of the user records with the same email address, your app calls the Management API's [Get Users By Email endpoint](/api/v2#!/users-by-email/) using a [Management API Access Token
💯

2018-04-20 20:23 UTC, cabralmartin commented on articles/migrations/guides/account-linking.md
> +The grace period for this migration starts on **March 31, 2018** and ends on **March 31, 2019**. From that day forward you will no longer be able to use ID Tokens to link or unlink accounts.
Dates we can remove until we have the calendar.

2018-04-20 20:23 UTC, cabralmartin commented on articles/migrations/guides/account-linking.md
> +This guide is part of the [Deprecating the usage of ID Tokens on the Auth0 Management API](/migrations#deprecating-the-usage-of-id-tokens-on-the-auth0-management-api) migration, and focuses on the [a
Nitpicking, we are deprecating the use of id_tokens in Authorization headers, not in the payload.

2018-04-20 20:23 UTC, cabralmartin commented on articles/migrations/guides/account-linking.md
> +## Summary of changes
💯

2018-04-20 20:23 UTC, cabralmartin commented on articles/migrations/guides/calling-api-with-idtokens.md
> +The grace period for this migration starts on **March 31, 2018** and ends on **March 31, 2019**. From that day forward you will no longer be able to use ID Tokens as credentials for the Management AP
We can leave dates out.

2018-04-20 20:23 UTC, cabralmartin commented on articles/migrations/guides/account-linking.md
> +      <td>You link user accounts with the <a href="/api/management/v2#!/Users/post_identities">Link a user account</a> endpoint of the Management API, you send an Access Token in the <code>Authorizat
Clarify, users won't be affected if the access token contains scope `update:users`. If not, they are affected.

2018-04-20 20:23 UTC, cabralmartin commented on articles/migrations/guides/account-linking.md
> +      <td>You link user accounts with the <a href="/auth0js#user-management">Auth0.js library</a>, and you use an Access Token to instantiate <code>auth0.Management</code></td>
Same as above.
access token + update:users + user_id in payload = OK
access token + update:current_user_* : user_id in payload = NOT OK

2018-05-10 08:39 UTC, mpaktiti commented on articles/migrations/guides/account-linking.md
> +      <td>You link user accounts with the <a href="/api/management/v2#!/Users/post_identities">Link a user account</a> endpoint of the Management API, you send an Access Token in the <code>Authorizat
@cabralmartin If I get this right, if you have an access token with `update:current_user_* ` scope
- it is not ok to send the user_id in payload
- it is ok to send the SECONDARY_ACCOUNT_ID_TOKEN in the payload
?

2018-05-10 12:46 UTC, cabralmartin commented on articles/migrations/guides/account-linking.md
> +      <td>You link user accounts with the <a href="/api/management/v2#!/Users/post_identities">Link a user account</a> endpoint of the Management API, you send an Access Token in the <code>Authorizat
Correct!

2018-05-11 15:57 UTC, merged