Minor spelling, punctuation, and consistency edits.
auth0/docs pull request #6007
Opened 2018-04-11 20:06 UTC by rkhoriander

2018-04-11 20:13 UTC, rkhoriander commented
https://auth0-docs-content-pr-6007.herokuapp.com/docs/tokens/access-token
https://auth0-docs-content-pr-6007.herokuapp.com/docs/connections/social/linkedin
https://auth0-docs-content-pr-6007.herokuapp.com/docs/identityproviders

2018-04-12 09:59 UTC, mpaktiti requested changes

2018-04-12 09:59 UTC, mpaktiti commented on articles/connections/social/linkedin.md
> +## 2. Create Your App
We use title case for first-level headings (Connect Your App to LinkedIn) and sentence case for subheads (Create your app). See https://github.com/auth0/docs/blob/master/STYLEGUIDE.md#formatting
We only capitalize stuff that are always capitalized, for example Lock.

I won't comment on every subhead in this PR so please go through them and undo these specific changes.

2018-04-12 09:59 UTC, mpaktiti commented on articles/connections/social/linkedin.md
> +## 5. Get Your **Client ID** and **Client Secret**
No bold in subheads, the `## 5. Get Your **Client ID** and **Client Secret**` should be `## 5. Get your Client ID and Client Secret`

2018-04-12 09:59 UTC, mpaktiti commented on articles/tokens/access-token.md
> +::: panel What is the Audience?
we don't capitalize audience

2018-04-12 09:59 UTC, mpaktiti commented on articles/tokens/access-token.md
> +:::panel Use RS256 for Multiple Audiences
no reason for capitalization, use sentence case at panels (except for things that are always capitalized, like Lock)

2018-04-12 10:00 UTC, mpaktiti commented
@rkhoriander I left some comments. Follow the same process as before, once you push the changes remove the `update-needed` label and this will pop in my daily review list. Thank you!

2018-04-13 11:50 UTC, mpaktiti approved these changes

2018-04-13 11:50 UTC, merged