state parameter updates
auth0/docs pull request #6151
Opened 2018-05-07 22:23 UTC by tamigoodall

2018-05-07 22:26 UTC, tamigoodall commented
My first one!!!

2018-05-09 09:32 UTC, mpaktiti requested changes
Tami, good work :) I left some comments, let me know if they are not clear or you want to discuss them.

2018-05-09 09:32 UTC, mpaktiti commented on articles/protocols/oauth2/oauth-state.md
> +::: Note
I deployed locally to test the doc (the heroku review app refuses to work) and this displays like that:

![image](https://user-images.githubusercontent.com/11715799/39806860-966a654c-5383-11e8-9544-d6bb1b34ac2a.png)

Looks like the `::: note` syntax is case sensitive. Change and see if it gets fixed? (spoiler alert: it does :P)

2018-05-09 09:32 UTC, mpaktiti commented on articles/protocols/oauth2/oauth-state.md
> +## How to use the `state` parameter
Can you remove please the code formatting from the header? It should be `## How to use the state parameter`

2018-05-09 09:32 UTC, mpaktiti commented on articles/protocols/oauth2/oauth-state.md
>  1. Before redirecting a request to the [IdP](/identityproviders), have the application generate a random string.
In step 2, the URL is broken. The correct is `/security/store-tokens#web-storage-local-storage-session-storage-`

2018-05-09 09:32 UTC, mpaktiti commented on articles/protocols/oauth2/oauth-state.md
>  The `state` parameter is an authentication parameter used to help mitigate [CSRF attacks](https://en.wikipedia.org/wiki/Cross-site_request_forgery).
I think this needs more info. The "is an authentication parameter" is a bit generic, we don't even say what's the protocol that's using it. Or how this parameter actually helps against CSFR.

Maybe you could also use this as input https://community.auth0.com/t/usage-of-the-oauth-state-parameter/8266 (but write it in a more understandable format)

2018-05-09 09:33 UTC, mpaktiti commented
@tamigoodall Once you are done with pushing the changes remove the `update-needed` label and this will pop right back to my to-review list. Thanks!

2018-05-09 14:22 UTC, tamigoodall commented on articles/protocols/oauth2/oauth-state.md
> +::: Note
Makes sense.

2018-05-29 20:55 UTC, tamigoodall reviewed
Incorporated all changes

2018-06-19 22:43 UTC, tamigoodall commented
@mpaktiti When I click **See review**, it doesn't do anything. I can't see the changes.

2018-06-19 22:46 UTC, tamigoodall commented
When I click **See review** next to your review, it jumps to the top of this page. Not sure what your change request is.

2018-07-02 10:06 UTC, mpaktiti commented
@tamigoodall Since the time you started working on this (apologies on the delay to merge) we were notified of a second use case. So I pushed some changes in this PR to incorporate these changes and restructure the headers a bit. I'll be merging within the day. Thanks!

2018-07-02 10:39 UTC, merged