Adding more custom domain supported items
auth0/docs pull request #6152
Opened 2018-05-08 15:11 UTC by jeffreylees

2018-05-09 08:42 UTC, mpaktiti requested changes

2018-05-09 08:42 UTC, mpaktiti commented on articles/custom-domains/index.md
> +* AD/LAP connections (with Kerberos support)
typo: AD/LAP
Also why not merge these two in one bullet? `AD/LDAP connections (with or without Kerberos support)`

2018-05-09 08:42 UTC, mpaktiti commented on articles/custom-domains/additional-configuration.md
> +## Configure Google Apps connections
This is all good but we must add this info also at the corresponding docs. For example, add this content at this doc https://auth0.com/docs/connections/enterprise/google-apps as an optional step if you are using custom domains.

2018-05-09 08:42 UTC, mpaktiti commented on articles/custom-domains/additional-configuration.md
> +
This doc https://auth0.com/docs/api-auth/tutorials/verify-access-token should also have this info

2018-05-09 08:42 UTC, mpaktiti commented on articles/custom-domains/additional-configuration.md
> +If you want to use your WS-Fed applications with your custom domain with Auth0 as the IDP, you must update your Service Provider with new Identity Provider metadata from Auth0 (You can obtain the met
this doc https://auth0.com/docs/integrations/configure-wsfed-application should also have this info

2018-05-09 08:42 UTC, mpaktiti commented on articles/custom-domains/additional-configuration.md
> +
https://auth0.com/docs/connections/enterprise/azure-active-directory/v2#5-configure-reply-urls

2018-05-09 08:42 UTC, mpaktiti commented on articles/custom-domains/additional-configuration.md
> +
https://auth0.com/docs/connections/enterprise/adfs

2018-05-09 08:42 UTC, mpaktiti commented on articles/custom-domains/additional-configuration.md
> +## Configure AD/LAP connections
typo: AD/LAP

2018-05-09 08:42 UTC, mpaktiti commented on articles/custom-domains/additional-configuration.md
> +In order to use AD/LAP connections with Kerberos support and custom domains, you will need to update the ticket endpoint to work with the custom domain. [As mentioned in the [Auth0 AD/LAP connector d
typo: AD/LAP

2018-05-09 08:42 UTC, mpaktiti commented on articles/custom-domains/additional-configuration.md
> +In order to use AD/LAP connections with Kerberos support and custom domains, you will need to update the ticket endpoint to work with the custom domain. [As mentioned in the [Auth0 AD/LAP connector d
fix: `[As mentioned in the [Auth0 AD/LAP connector documentation](/connector/modify#point-an-ad-ldap-connector-to-a-new-connection)`

2018-05-09 08:42 UTC, mpaktiti commented on articles/custom-domains/additional-configuration.md
> +In order to use AD/LAP connections with Kerberos support and custom domains, you will need to update the ticket endpoint to work with the custom domain. [As mentioned in the [Auth0 AD/LAP connector d
This talks only about Kerberos support but on the other doc me also mention without Kerberos support. Is the process different or the same?

2018-05-09 08:42 UTC, mpaktiti commented on articles/custom-domains/additional-configuration.md
> +In order to use AD/LAP connections with Kerberos support and custom domains, you will need to update the ticket endpoint to work with the custom domain. [As mentioned in the [Auth0 AD/LAP connector d
add this info also at this doc https://auth0.com/docs/connector/modify#point-an-ad-ldap-connector-to-a-new-connection

2018-05-09 13:31 UTC, jeffreylees commented
Thanks @mpaktiti I must have been tunnel visioned there.

Ready to check again, but also note that this PR will need to wait for @jhiner review which should be today/tomorrow I think.

2018-05-09 18:40 UTC, jhiner requested changes

2018-05-09 18:40 UTC, jhiner commented on articles/custom-domains/index.md
> +* WS-Fed clients (Auth0 as IDP aka WS-Fed Add-on)
I know I put this in the notes, but I think we shouldn't put "aka" like this. Maybe something cleaner / doc-friendly like "Auth0 as IDP using WS-Fed Add-on" ?

2018-05-10 13:13 UTC, mpaktiti approved these changes
LGTM

2018-05-10 16:09 UTC, merged