Custom DB Docs
auth0/docs pull request #6406
Opened 2018-07-17 17:08 UTC by khorne3

2018-07-19 12:30 UTC, mpaktiti requested changes
Hey Katie, left some comments, let me know if you wanna chat

2018-07-19 12:30 UTC, mpaktiti commented on articles/connections/database/custom-db/index.md
> +* You'll write your database action scripts in JavaScript. The scripts run in a [Webtask](https://webtask.io/) environment that supports JavaScript and [select Node.js libraries](https://tehsis.githu
The `canirequire` thingy was moved here https://auth0-extensions.github.io/canirequire/
There is a redirect in place from tehsis repo, but we might as well set the correct URL.

Also, marketing-wise I'm not sure if we still want to refer to webtasks as webtasks and not Extend. I think gblock mentioned sth to me some time ago, can you check with him?

2018-07-19 12:30 UTC, mpaktiti commented on articles/connections/database/custom-db/index.md
> +* [Update Users Using Your Database](/user-profile/customdb) has information on updating user profile fields.
I know you have put some links inline, but I did expect to see a what's next section at the end listing the rest of the docs

2018-07-19 12:30 UTC, mpaktiti commented on articles/connections/database/custom-db/create-db-connection.md
> +Create an Auth0 database connection
Missing header, check https://auth0-docs-content-pr-6406.herokuapp.com/docs/connections/database/custom-db/create-db-connection

2018-07-19 12:30 UTC, mpaktiti commented on articles/connections/database/custom-db/create-db-connection.md
> +The first thing you will do is create a database connection in Auth0:
Feels like we should have an intro here explaining what the doc is about. If someone lands her directly, and not through the index, they see this and might wonder what's this first thing is about.

2018-07-19 12:30 UTC, mpaktiti commented on articles/connections/database/custom-db/create-db-connection.md
> +## Step 2: Create database action scripts
Looks like there should be a header before that for `Step 1`, we can't start from 2

2018-07-19 12:30 UTC, mpaktiti commented on articles/connections/database/custom-db/create-db-connection.md
> +3. Added configuration parameters
what's the next logical step? do we want a next-steps section here or are we removing this notion?

2018-07-19 12:30 UTC, mpaktiti commented on articles/connections/database/custom-db/error-handling.md
> +In this article, we will show you how you can handle errors resulting from your custom database connection.
This article does not really say how to handle errors, all I can see is the different types of errors and how I can return one.

2018-07-19 12:30 UTC, mpaktiti commented on articles/connections/database/custom-db/lock.md
> +# Using Lock with Custom Databases
I'm wondering whether this is  doc that we should keep. It doesn't say much so my 2c is that we should either remove it or enhance it.

2018-07-19 12:30 UTC, mpaktiti commented on articles/connections/database/custom-db/lock.md
> +crews: crew-2
these crew-2 metadata were never used so we might as well remove them (there is not even a crew-2 in the company any longer). no need to do this as part of this PR but please add this in trello

2018-07-19 12:30 UTC, mpaktiti commented on articles/connections/database/custom-db/lock.md
> +<%= include('../../_quickstart-links.md') %>
I don't see the logical connection between this doc and the next steps listed here

2018-07-19 12:30 UTC, mpaktiti commented on articles/connections/database/custom-db/metadata.md
> +
what's this doc about? in which case should I read it?

how are the metadata relevant to the IP whitelisting that follows?

2018-07-19 12:30 UTC, mpaktiti commented on articles/connections/database/custom-db/templates/change-password.md
> +# Custom Database Script Templates: Change Password
this doc means that we should update it every time some script gets updated. are we sure we want to do that? did someone ask for it specifically? wouldn't it make more sense to have a revert button in the dashboard?

2018-07-19 12:30 UTC, mpaktiti commented on articles/connections/database/custom-db/templates/create.md
> +
same comment with `/custom-db/templates/change-password.md`

2018-07-19 12:30 UTC, mpaktiti commented on articles/connections/database/custom-db/templates/delete.md
> +# Custom Database Script Templates: Delete Users
same comment with `/custom-db/templates/change-password.md`

2018-07-19 12:30 UTC, mpaktiti commented on articles/connections/database/custom-db/templates/get-user.md
> +# Custom Database Script Templates: Get Users
same comment with `/custom-db/templates/change-password.md`

2018-07-19 12:30 UTC, mpaktiti commented on articles/connections/database/custom-db/templates/index.md
> +
same comment with `/custom-db/templates/change-password.md`

2018-07-19 12:30 UTC, mpaktiti commented on articles/connections/database/custom-db/templates/index.md
> +::: next-steps
When there are over 4-5 items this element looks bad I think. Consider replacing it with bullets https://auth0-docs-content-pr-6406.herokuapp.com/docs/connections/database/custom-db/templates

2018-07-19 12:30 UTC, mpaktiti commented on articles/connections/database/custom-db/templates/login.md
> +# Custom Database Script Templates: Login
same comment with `/custom-db/templates/change-password.md`

2018-07-19 12:30 UTC, mpaktiti commented on articles/connections/database/custom-db/templates/verify.md
> +# Custom Database Script Templates: Verify Users
same comment with `/custom-db/templates/change-password.md`

2018-07-19 12:30 UTC, mpaktiti commented on articles/connections/database/custom-db/troubleshoot.md
> +
this is a bit dry, it's missing an intro/scope of the doc

2018-07-19 15:26 UTC, khorne3 commented on articles/connections/database/custom-db/templates/change-password.md
> +# Custom Database Script Templates: Change Password
The answer to this is yes, there are issues with people losing out on the notes and things we populate in the dashboard. I agree w/ your revert suggestion, but what happens if the user wants to keep their script but also refer to the use notes we include in the text editor? For the time being, I understand we're creating a maintenance issue, but there are crucial items we don't want the customers to miss.

2018-07-19 15:49 UTC, khorne3 commented
Currently, the only outstanding item is whether we want to use Webtask or Extend.

2018-07-26 11:20 UTC, mpaktiti approved these changes

2018-07-26 11:20 UTC, merged