WIP: Add email authenticator tutorial
auth0/docs pull request #6466
Opened 2018-08-01 04:49 UTC by erjohnson

2018-08-22 20:42 UTC, cabralmartin requested changes

2018-08-22 20:42 UTC, cabralmartin commented on articles/multifactor-authentication/api/email.md
> +Start by enabling email authenticators with the [Management API](/api/management). To do this, make a `PUT` request to the [/api/v2/guardian/factors/email](/api/management/v2/#!/Guardian/put_factors_
Can we add the required scopes for the access token?

2018-08-22 20:42 UTC, cabralmartin commented on articles/multifactor-authentication/api/email.md
> +  "oob_code": "ata6daXAiOi..."
Is `oob_code` part of the actual response? What is its purpose?

2018-08-22 20:42 UTC, cabralmartin commented on articles/multifactor-authentication/api/email.md
> +
Can we add a p describing what happens next? ie. The users receives an email on their inbox ... grabs the code and puts it back into the app ... enrollment is completed.

2018-08-22 20:42 UTC, cabralmartin commented on articles/multifactor-authentication/api/email.md
> +
We should also add a note describing how the email template can be customized.

2018-08-22 20:42 UTC, cabralmartin commented on articles/multifactor-authentication/api/email.md
> +
Need to add an info or warning box here describing that email MFA only works with this API and is not supported as part of the hosted mfa page. This means that users enrolled for email can only use it as an authenticator with apps that consume the API and not with those that redirect the user to the hosted page.

2018-09-17 18:30 UTC, khorne3 submitted a review, later dismissed

2018-09-17 20:10 UTC, cabralmartin requested changes

2018-09-17 20:10 UTC, cabralmartin commented on articles/multifactor-authentication/api/email.md
> +Next the user should receive an email containing the code. Once they enter the code in your application, enrollment of the email authenticator will be complete.
> Once they enter the code in your application, enrollment of the email authenticator will be complete.

What does this mean? What is the application supposed to do with the code they get from the user?

2018-09-17 21:10 UTC, cabralmartin approved these changes

2018-09-17 21:20 UTC, merged