Call my api
auth0/docs pull request #6490
Opened 2018-08-06 17:11 UTC by khorne3

2018-08-06 18:43 UTC, tamigoodall submitted a review, later dismissed

2018-08-06 18:51 UTC, khorne3 commented
Whoops, forgot to tag this! Not quite done yet :)

2018-08-13 16:24 UTC, jeffreylees requested changes

2018-08-13 16:24 UTC, jeffreylees commented on articles/scopes/current/api-scopes.md
> +When you [create an API in Auth0](/apis), you'll need to define one scope for each API represented and action. For example, if you want to `read` and `delete` contact information, you would create tw
This sentence reads a little unclear `define one scope for each API represented and action`. Can it be rephrased?

2018-08-13 16:24 UTC, jeffreylees commented on articles/scopes/current/api-scopes.md
> +If you wanted to expand [our example](#example-asking-for-standard-claims) to include also the `read:contacts` permission, then you would using something like the following sample URL to initiate the
This link doesn't go anywhere?

2018-08-13 16:24 UTC, jeffreylees commented on articles/scopes/current/api-scopes.md
> +Note the differences between the two examples. In the latest, we want to get an Access Token, that will allow us to access the API, with the rights to do specific actions. To do so, we changed two pa
I think this ties in to the above missing example, can't note the difference if there aren't two.

2018-08-13 16:24 UTC, jeffreylees commented on articles/scopes/current/api-scopes.md
> +## Define Scopes Using the Dashboard
Sentence casing for H2s throughout

2018-08-13 16:24 UTC, jeffreylees commented on articles/scopes/current/api-scopes.md
> +This approach is discussed in more depth in some of our [Architecture Scenarios](/architecture-scenarios). Specifically, you can review the entire [Configure the Authorization Extension](/architectur
Configure the Authorization Extension link 404s

2018-08-13 16:24 UTC, jeffreylees commented on articles/scopes/current/oidc-scopes.md
> +* [Custom](#custom-claims)
This goes nowhere - does it need to be `(/scopes/current/custom-claims)` now?

2018-08-17 18:44 UTC, jeffreylees approved these changes

2018-08-17 18:45 UTC, merged