Fixed links to callback urls in Swift QSs
auth0/docs pull request #6513
Opened 2018-08-08 17:49 UTC by aaguiarz

2018-08-08 19:24 UTC, cocojoe requested changes

2018-08-08 19:24 UTC, cocojoe commented on articles/quickstart/native/ios-objc/02-custom-login-form.md
> +Please ensure you have configured your callback URL as show in [Configure Callback](/quickstart/native/ios-swift#configure-callback-urls).
~as show~ -> as demonstrated

Why take the developer to the swift tutorial, keep them in the ObjC one?

2018-08-08 20:37 UTC, albertoperdomo requested changes

2018-08-08 20:37 UTC, albertoperdomo commented on articles/quickstart/native/ios-objc/02-custom-login-form.md
> +Please ensure you have configured your callback URL as show in [Configure Callback](/quickstart/native/ios-swift#configure-callback-urls).
It's the Objective C tutorial, but we are pointing to the Swift tutorial.
Should it be `ios-objc` instead of `ios-swift` in the URL?

2018-08-08 20:37 UTC, albertoperdomo commented on articles/quickstart/native/ios-objc/_includes/_login_embedded.md
> +Please ensure you have configured your callback URL as demonstrated in [Configure Callback](/quickstart/native/ios-swift#configure-callback-urls).
Same as above?

It's the Objective C tutorial, but we are pointing to the Swift tutorial.
Should it be `ios-objc` instead of `ios-swift` in the URL?

2018-08-08 20:41 UTC, albertoperdomo approved these changes

2018-08-08 20:50 UTC, albertoperdomo commented
I deployed the branch to verify, but I think none of this is visible because the pages are not in the navigation or they are not present.

2018-08-16 20:22 UTC, albertoperdomo commented
Hello @cocojoe,
you requested some changes so I was wondering if this looks ok to you now. Thanks!

2018-08-17 07:42 UTC, cocojoe approved these changes
👍

2018-08-20 15:17 UTC, merged