Added deprecation warning
auth0/docs pull request #6734
Opened 2018-10-05 18:19 UTC by tamigoodall

Added deprecation warning

2018-10-10 14:56 UTC, jeffreylees requested changes
So, it looks like you've just added another warning above the existing one, when probably you're wanting to re-word or add to the existing warning, which says some of the same things?

2018-10-11 21:45 UTC, tamigoodall commented
I see that now. I spaced on the line above. I updated the include file.

2018-10-22 18:53 UTC, jeffreylees commented on articles/libraries/auth0-swift/passwordless.md
> +-<%= include('../../_includes/_native_passwordless_warning') %>
```suggestion
<%= include('../../_includes/_native_passwordless_warning') %>
```

2018-10-22 18:54 UTC, jeffreylees commented on articles/libraries/auth0-swift/passwordless.md
> +-<%= include('../../_includes/_native_passwordless_warning') %>
Just trying out this suggested change feature, which is new? Anyway, not sure if that hypen is a stray mark?

2018-10-23 16:40 UTC, tamigoodall commented
I accepted your change to remove the leading dash in that line. I think it worked.

2018-10-23 20:16 UTC, jeffreylees approved these changes

2018-10-23 20:21 UTC, merged