Added the file location for Cordova's QS
auth0/docs pull request #6832
Opened 2018-10-22 16:36 UTC by benlizar

To fix #4671 .

2018-10-27 19:35 UTC, albertoperdomo requested changes

2018-10-27 19:35 UTC, albertoperdomo commented on articles/quickstart/native/cordova/01-login.md
> +// ../src/index.js
Why `../src/index..js`and not `src/index.js`?

2018-10-27 19:35 UTC, albertoperdomo commented on snippets/native-platforms/cordova/use.md
> +// ../src/App.js
See above

2019-10-23 00:17 UTC, joshcanhelp commented
Obsoleted by #8400

2019-10-23 00:17 UTC, closed without merging