Chunked content
auth0/docs pull request #6980
Opened 2018-11-30 01:15 UTC by tamigoodall

Chunked content

2018-11-30 22:23 UTC, tamigoodall commented
Here's the link to the top level of the content in the review app: https://auth0-docs-content-pr-6980.herokuapp.com/docs/anomaly-detection/concepts/overview-anomaly-detection

2018-11-30 23:08 UTC, tamigoodall commented
I still think there might be a breadcrumb problem. Any help to figure it out would be appreciated.

2018-12-03 20:05 UTC, erjohnson commented
For the breadcrumbs, the pages in the section would have to children of the main anomaly detection page.

2018-12-04 18:54 UTC, tamigoodall commented
Fixed breadcrumb issue.

2018-12-05 20:27 UTC, jeffreylees requested changes
I didn't check every link - I might do a pass later - but here are a few comments!

2018-12-05 20:27 UTC, jeffreylees commented on articles/anomaly-detection/concepts/breached-passwords.md
> +When a user receives an email requesting that they change their password immediately, it is because their account could be the victim of a security breach. This may be the result of a compromise by a
`avaiable` -> `available`

2018-12-05 20:27 UTC, jeffreylees commented on articles/anomaly-detection/concepts/breached-passwords.md
> +Users typically can't prevent certain sites from security breaches, but there are some things they can do to help keep their accounts safe.
I'm unsure what this first portion means. Perhaps "Security breaches on web applications are usually out of the end-user's hands, but there are some things they can do to keep their accounts as safe as possible." ?

2018-12-05 20:27 UTC, jeffreylees commented on articles/anomaly-detection/concepts/breached-passwords.md
> +Emails in general are not very secure and re not a good way to communicate sensitive information. A trusted company/application would not ask for  information in this way. Make sure not to enter conf
`re` -> `are`

2018-12-05 20:27 UTC, jeffreylees commented on articles/anomaly-detection/concepts/breached-passwords.md
> +When one site has a breach of user data, if a user uses the same credentials elsewhere, information in other sites can also be accessed. There are many password tools available to help keep track of
Maybe a line or two of clarification here -- something like this: 

"...accessed. The only way to prevent this is by not reusing passwords for multiple sites. The problem is that remembering countless numbers of different passwords is frustrating and often impossible. One solution to this problem is the use of a password manager. There are many password managers available which can help users to use separate and secure passwords for each account, but at the same time not be responsible for remembering all of them."

2018-12-05 20:27 UTC, jeffreylees commented on articles/anomaly-detection/concepts/breached-passwords.md
> +The longer a password is, the harder it becomes to guess. Try to make passwords long and use a mix of special characters, numbers, and upper- and lowercase letters.
The longer a password is, the harder it becomes to be guessed via brute force methods. Many sites allow the use of pass-phrases (a phrase or sentence instead of just a complicated word). Try to make passwords long and use a mix of special characters, numbers, and upper- and lowercase letters.

2018-12-05 20:27 UTC, jeffreylees commented on articles/anomaly-detection/guides/set-anomaly-detection-preferences.md
> +![](/media/articles/anomaly-detection/anomaly-detection-overview.png)
Should put alt tags between the `[ ]` on this and the other images

2018-12-05 20:27 UTC, jeffreylees commented on articles/anomaly-detection/guides/customize-blocked-account-emails.md
> +## Keep reading
Most of the Keep Reading headings in these docs are missing the line return after before starting the reading list.

2018-12-05 20:27 UTC, jeffreylees commented on articles/anomaly-detection/references/brute-force-protection-triggers-actions.md
> +Auth0 emails the dashboard administrator(s) when this block is triggered. Within this email there's a link the owner can click on to clear the block.
Is this the only way to remove this particular block? I would've assumed the dashboard could be used too, rather than only an email link. Maybe this is a question for someone else / later, just curious.

2018-12-05 20:27 UTC, jeffreylees commented on articles/compliance/gdpr/features-aiding-compliance/protect-user-data.md
> +For more information, see [Brute Force Protection](/anomaly-detection/index#brute-force-protection).
Just a note, if the URL here (and the same comment for others in the PR) are to the index page, probably `/anomaly-detection#brute-force-protection` would work?

2018-12-10 18:46 UTC, tamigoodall commented on articles/anomaly-detection/concepts/breached-passwords.md
> +Users typically can't prevent certain sites from security breaches, but there are some things they can do to help keep their accounts safe.
I think it is meant to convey that end-users don't have much control over security breaches that occur at companies they have accounts with. For example, a breach at Uber wouldn't necessarily be preventable by an Uber user.

2018-12-10 18:48 UTC, tamigoodall commented on articles/anomaly-detection/concepts/breached-passwords.md
> +Users typically can't prevent certain sites from security breaches, but there are some things they can do to help keep their accounts safe.
I'll reword it to make it more clear.

2018-12-10 19:04 UTC, tamigoodall commented on articles/anomaly-detection/references/brute-force-protection-triggers-actions.md
> +Auth0 emails the dashboard administrator(s) when this block is triggered. Within this email there's a link the owner can click on to clear the block.
Good question. I'll ask around.

2018-12-10 20:24 UTC, jeffreylees approved these changes

2018-12-10 20:24 UTC, merged