monitoring-auth0-rework
auth0/docs pull request #7259
Opened 2019-02-15 00:53 UTC by tamigoodall

Broke up index and monitoring files into guides
Wrote new concept article

2019-02-18 19:07 UTC, khorne3 requested changes

2019-02-18 19:07 UTC, khorne3 commented on articles/connector/scom-monitoring.md
> +We also recommend setting up a _synthetic transaction_ to monitor end-to-end authentication. See [Monitor Auth0 Using SCOM](/monitoring/guide/monitor-using-SCOM) for more information.
broken link

2019-02-18 19:07 UTC, khorne3 commented on articles/monitoring/guides/check-status.md
> +Auth0 makes every effort to minimize outages, but if there is any disruption to service, it will appear on the status page. To support requirements for root cause analysis documentation after a disru
link to status page

Also, maybe

> Auth0 will conduct an internal review and publish the results when the analysis is complete

2019-02-18 19:07 UTC, khorne3 commented on articles/monitoring/guides/check-status.md
> +In addition, you may want to set up monitoring of any remote identity providers you use with your Auth0 connections. This will help you quickly isolate the source of the problem if one of them goes d
> You may want to set up monitoring of any remote identity providers you use with Auth0 so that you can quickly identify the problem if any become unavailable. You may also consider setting up synthetic transactions that test the login experience from end to end.

2019-02-18 19:07 UTC, khorne3 commented on articles/monitoring/guides/check-status.md
> +Last but not least your customers may have some of the same concerns, so you may want to document any monitoring pages or endpoints they can look at to help them troubleshoot and narrow down the loca
> We also recommend documenting your monitoring activities or endpoints so that your end users can troubleshoot issues they see.

2019-02-18 19:07 UTC, khorne3 commented on articles/monitoring/guides/check-status.md
> +You can see the status of a region or expand a region and see the status of individual services such as the authentication API or execution of custom code (used within custom DB connections and rules
> You can see the status of a region or expand a region and see the status of individual services supporting functionality such as the authentication API or execution of custom code (used within custom DB connections and rules).

2019-02-18 19:07 UTC, khorne3 commented on articles/monitoring/guides/check-status.md
> +* Subscribe to the Atom feed to get status updates that affect your tenant.
Add `The URL to use is as follows:`

2019-02-18 19:07 UTC, khorne3 commented on articles/monitoring/guides/monitor-applications.md
> +If you've extended Auth0 through [rules](/rules) or [a custom database connection](/connections/database/mysql), you can build a synthetic transaction that exercises these capabilities using the [Res
update the custom DB link to use `/connections/database/custom-db`

2019-02-18 19:07 UTC, khorne3 commented on articles/monitoring/guides/monitor-using-SCOM.md
> +
convert to a table

2019-02-18 19:07 UTC, khorne3 commented on articles/monitoring/guides/monitor-using-SCOM.md
> +   * **Test time-out**: 30 seconds
convert to a table

2019-02-18 19:07 UTC, khorne3 commented on articles/monitoring/guides/test-testall-endpoints.md
> +You can use the `/test` and `/testall` endpoints as a supplement to other monitoring.
Maybe

> to your other monitoring activities.

2019-02-18 19:07 UTC, khorne3 commented on articles/monitoring/guides/test-testall-endpoints.md
> +* **`/testall` endpoint**: Checks the status of the core Auth0 authentication service, as well as supporting services such as those for the [Dashboard](${manage_url}) and documentation.
table?

2019-02-18 19:07 UTC, khorne3 commented on articles/monitoring/guides/test-testall-endpoints.md
> +These endpoints are best for determining if everything is functioning not for determining if something is down. For example, even if they return a `500` response code, that doesn’t mean that there’s
> These endpoints are best for determining if everything is functioning, *not* for determining if something is unavailable. For example, an HTTP `500` response code doesn't necessarily mean there's a server failure.

2019-02-18 19:07 UTC, khorne3 commented on articles/monitoring/guides/track-leads-salesforce.md
> +description: Learn now to track new leads in Salesforce and augment user profiles with public information gathered from TowerData.
> Learn **how**

2019-02-18 19:07 UTC, khorne3 commented on articles/monitoring/guides/track-signups-salesforce.md
> +You can track new sign-ups in Salesforce with FullContact-Enriched User Profiles, and Send Auth0 Events to MixPanel.
remove comma

2019-02-18 20:16 UTC, tamigoodall commented on articles/monitoring/guides/check-status.md
> +Last but not least your customers may have some of the same concerns, so you may want to document any monitoring pages or endpoints they can look at to help them troubleshoot and narrow down the loca
Yup - I reworded this section and moved it to a different location highlighting the recommendation to provide their customers with monitoring capabilities.

2019-02-19 16:34 UTC, tamigoodall commented
Incorporated all changes from @khorne3 review.

2019-02-19 17:41 UTC, khorne3 approved these changes

2019-02-19 17:41 UTC, merged