Custom Domains
auth0/docs pull request #7634
Opened 2019-05-20 17:58 UTC by khorne3

2019-06-19 13:24 UTC, CriGoT commented
With regards to the requirements for the migration we could simplify to the following

```
- A new DNS domain dedicated to host the custom domains origins hostnames. This could a subdomain of your existing Auth0 Domain for example if your domain is *.auth.mydomain.com the new subdomain would be *.cd.auth.mydomain.com
- A wildcard public SSL certificate for the new DNS domain
- A layer 4 network load balancer. This could be the existing one used by your PSaaS deployment. **Note:** If you use a layer 7 load balancer you will need to add a new layer 4 load balancer.
- A DNS record pointing to the layer 4 load balancer
```

Not sure if that is enough, too little or too much.

2019-06-24 15:11 UTC, tamigoodall commented on articles/private-saas-deployment/custom-domain-migration.md
> +* A new DNS domain dedicated to the Custom Domain's origin server hostname. This could a subdomain of your existing Auth0 Domain (i.e., if your domain name is `*.auth.mydomain.com`, the new subdomain
This could **be** a subdomain of your

2019-06-24 15:12 UTC, tamigoodall commented on articles/private-saas-deployment/custom-domain-migration.md
> +* A wildcard public SSL certificate for the new DNS domain
A wildcard public SSL certificate for the new DNS domain**.**

2019-06-24 15:15 UTC, tamigoodall requested changes
Couple of typos.

2019-06-24 15:21 UTC, tamigoodall approved these changes

2019-06-24 15:22 UTC, khorne3 commented
@tehsis @sgmeyer Can you please review and approve if appropriate? Thank you!

2019-06-24 15:29 UTC, merged