add logout docs to Java Quickstart
auth0/docs pull request #7662
Opened 2019-05-23 19:31 UTC by jimmyjames

Addresses QS-124.

2019-05-23 19:42 UTC, damieng submitted a review, later dismissed

2019-05-23 19:43 UTC, lbalmaceda requested changes
Logout URLs need to be whitelisted in the dashboard. I think that should be part of the guidance as well

2019-05-23 19:53 UTC, jimmyjames commented
> Logout URLs need to be whitelisted in the dashboard. I think that should be part of the guidance as well

Yes, but it is brought in by the include `<%= include('../../../_includes/_logout_url') %>`, you can see [here](https://auth0.com/docs/quickstart/webapp/java#configure-logout-urls).

I notice that the deploy for this branch failed, is that something that should be investigated? When I go to the details it brings me to login to Heroku.

2019-05-24 00:58 UTC, jimmyjames commented
@lbalmaceda on closer look, while the included `_logout_url` snippet does include information about allowed logout URLs in general, there's no specific inclusion of what URL to specify in the specific context of this quick start.

I could add some info about this to the Logout section of the QS that was added in this PR, but since we already have a common logout include, I propose that we update `includes/_logout_url.md` to be parameterized and display the info, similar to how `_getting_started.md` does it. That way it is consistent and the info is contained in one common place.

Because `_logout_url` is used by many quickstarts, I think we can conditionally render a note until others are updated:

```
<% if (returnTo) { %>
  ::: note
  If you are following along with the sample project you downloaded from the top of this page, you should set the **Logout URL** to `${returnTo}`.
  :::
<% } %>
```

Then from this quickstart can do this, similar to how `_getting_started` is configured:

```
<%= include('../../../_includes/_logout_url', { returnTo: 'http://localhost:3000/login' }) %>
```

Thoughts?

2019-05-27 17:37 UTC, albertoperdomo commented
> could add some info about this to the Logout section of the QS that was added in this PR, but since we already have a common logout include, I propose that we update `includes/_logout_url.md` to be parameterized and display the info, similar to how `_getting_started.md` does it. That way it is consistent and the info is contained in one common place.

+1!

2019-05-27 18:55 UTC, lbalmaceda commented
@jimmyjames Yup! That will work for future QS and not break existing ones. Thanks

2019-05-28 18:16 UTC, lbalmaceda commented on articles/_includes/_logout_url.md
>  You can set the logout URL for your app in the **Allowed Logout URLs** field in your [Application Settings](${manage_url}/#/applications/${account.clientId}/settings). If you don't set a logout URL,
```suggestion
The logout URL for your app must be whitelisted in the **Allowed Logout URLs** field in your [Application Settings](${manage_url}/#/applications/${account.clientId}/settings). If this field is not set, the users will be unable to log out from the application and will get an error.
```

2019-05-28 18:16 UTC, lbalmaceda commented on articles/quickstart/webapp/java/_includes/_login.md
> +First, we clear the session by  calling `request.getSession().invalidate()`. We then construct the logout URL, being sure to include the `returnTo` query parameter, which is where the user will be re
```suggestion
First, we clear the session by calling `request.getSession().invalidate()`. We then construct the logout URL, being sure to include the `returnTo` query parameter, which is where the user will be redirected to after logging out. Finally, we redirect the response to our logout URL.
```

2019-05-28 18:16 UTC, lbalmaceda commented on articles/_includes/_logout_url.md
> +  If you are following along with the sample project you downloaded from the top of this page, you should set the **Logout URL** to `${returnTo}`.
```suggestion
  If you are following along with the sample project you downloaded from the top of this page, the logout URL you need to whitelist in the **Allowed Logout URLs** field is `${returnTo}`.
```

2019-05-28 18:50 UTC, lbalmaceda submitted a review, later dismissed

2019-05-28 19:12 UTC, lbalmaceda approved these changes
LGTM!

2019-05-28 20:27 UTC, merged