co-authentication updates
auth0/docs pull request #7730
Opened 2019-06-07 21:34 UTC by tamigoodall

Added warnings to index.md
Removed date in fingerprinting.md

2019-06-08 21:17 UTC, jeffreylees requested changes

2019-06-08 21:17 UTC, jeffreylees commented on articles/cross-origin-authentication/fingerprinting.md
> +Auth0 has announced a [vulnerability](https://auth0.com/blog/managing-and-mitigating-security-vulnerabilities-at-auth0/) in all versions of Lock (<11) and auth0.js (<9). We strongly recommend that al
```suggestion
Auth0 has announced a [vulnerability](https://auth0.com/blog/managing-and-mitigating-security-vulnerabilities-at-auth0/) in all versions of Lock (<11) and auth0.js (<9). We strongly recommend that all users of legacy versions migrate to the newest, most secure versions immediately. Support for conducting logins with a username and password with these versions is no longer supported, and in most cases, not possible.
```

2019-06-08 21:17 UTC, jeffreylees commented on articles/cross-origin-authentication/fingerprinting.md
> +Auth0 has announced a [vulnerability](https://auth0.com/blog/managing-and-mitigating-security-vulnerabilities-at-auth0/) in all versions of Lock (<11) and auth0.js (<9). We strongly recommend that al
(Deprecated is the wrong word to use since the endpoints are already end-of-life.)

2019-06-08 21:17 UTC, jeffreylees commented on articles/cross-origin-authentication/index.md
> +# Cross-origin Authentication
In APA and in our other writing afaik, hyphenation in Title Case is done with capitalization on the second word as well (Cross-Origin).

2019-06-08 21:17 UTC, jeffreylees commented on articles/cross-origin-authentication/index.md
> +Auth0 strongly recommends that authentication transactions be handled via [Universal Login](/hosted-pages/login). Doing so offers [the easiest and most secure way to authenticate users](guides/login/
I think it's probably no good to say "it's not secure, but we offer it". Probably better to just say it's not recommended and leave it there?

2019-06-10 16:29 UTC, tamigoodall commented on articles/cross-origin-authentication/index.md
> +Cross-origin authentication performed using deprecated versions of the [Lock](/libraries/lock) (< v11) and [Auth0.js](/libraries/auth0js) (< v9) libraries is [unsafe](https://auth0.com/blog/managing-
Delete paragraph

2019-06-10 17:15 UTC, jeffreylees approved these changes

2019-06-10 19:33 UTC, merged