Draft for SPA SDK
auth0/docs pull request #7785
Opened 2019-06-17 23:09 UTC by erjohnson

Basic outline for the SPA SDK docs section under Libraries.

2019-06-18 16:53 UTC, erjohnson commented on articles/libraries/auth0-spa-js/index.md
> +Auth0 SDK for Single Page Applications using the [Authorization Code Grant Flow with PKCE](/api-auth/tutorials/authorization-code-grant-pkce).
needs better intro

2019-06-18 16:54 UTC, luisrudge commented on articles/libraries/auth0-spa-js/index.md
> +<script src="https://cdn.auth0.com/js/auth0-spa-js/1.0.0-beta.2/auth0-spa-js.production.js"></script>
let's use 1.0.0 from the get go, so we don't forget about it later 😬

2019-06-24 17:01 UTC, luisrudge approved these changes

2019-06-24 17:17 UTC, luisrudge commented on articles/libraries/auth0-spa-js/index.md
> +      Authorization: `Bearer ACCESS_TOKEN`
```suggestion
      Authorization: `Bearer ${accessToken}`
```

2019-06-24 17:20 UTC, luisrudge requested changes

2019-06-24 17:20 UTC, luisrudge commented on articles/libraries/auth0-spa-js/index.md
> +      Authorization: `Bearer ACCESS_TOKEN`
```suggestion
      Authorization: `Bearer ${accessToken}`
```

2019-06-24 17:20 UTC, luisrudge commented on articles/libraries/auth0-spa-js/index.md
> +          Authorization: `Bearer ACCESS_TOKEN`
```suggestion
      Authorization: `Bearer ${accessToken}`
```

2019-06-24 17:20 UTC, luisrudge commented on articles/libraries/auth0-spa-js/index.md
> +JQuery is used in the following examples.
```suggestion
jQuery is used in the following examples.
```

2019-06-24 17:20 UTC, luisrudge commented on articles/libraries/auth0-spa-js/index.md
> +    redirect_uri: 'http://localhost:3000/callback.html'
there's no redirect_uri in `loginWithPopup `

2019-06-24 17:26 UTC, erjohnson commented on articles/libraries/auth0-spa-js/index.md
> +      Authorization: `Bearer ACCESS_TOKEN`
using {$accessToken} gives us a build error

2019-06-24 17:34 UTC, luisrudge approved these changes

2019-06-24 17:39 UTC, merged