B2b architecture phase 1
auth0/docs pull request #7798
Opened 2019-06-19 17:23 UTC by tamigoodall

2019-06-19 19:13 UTC, mostekcm commented on articles/architecture-scenarios/_includes/_architecture/_introduction.md
> +If your customers' organization supports the use of mutliple IDPs, then you should create separate Auth0 tenants for that organization; see [Tenant provision for complex organizations](#tenant-provis
```suggestion
If your customers' organization supports the use of mutliple IDPs, then you can create separate Auth0 tenants for that organization; see [Tenant provision for complex organizations](#tenant-provision-for-complex-organizations) for further details. This allows you to keep the rest of your setup much simpler by maintaining a one-to-one connection relationship between your organization and all your customer organizations within your main tenant. 
```

2019-06-19 19:14 UTC, mostekcm commented on articles/architecture-scenarios/implementation/b2b/b2b-architecture.md
> +If both of these situations are the case, then you should create separate Auth0 tenants for each customer that needs it. This allows you to have a separate custom domain for them and to easily custom
```suggestion
If both of these situations are the case, then you can create separate Auth0 tenants for each customer that needs it. This allows you to have a separate custom domain for them and to easily customize their login experience, including Home Realm Discovery on their login page. 
```

2019-06-19 19:15 UTC, mostekcm commented on articles/architecture-scenarios/implementation/b2b/b2b-architecture.md
> +To help you with planning your implementation, we've put together some [planning guidance]((https://drive.google.com/a/auth0.com/file/d/17XVLT3kU7vG49Ix9afJV0pAI9ev4oRUL/view?usp=sharing)) that detai
I have a planning include now.  Will have to remember to migrate to it so we get the right URL after that gets merged.

2019-06-19 19:15 UTC, mostekcm requested changes
See individual comments for change requests

2019-06-19 19:23 UTC, merged

2019-06-21 15:24 UTC, PeterGFernandez commented on articles/architecture-scenarios/_includes/_architecture/_introduction.md
> +If your customers' organization supports the use of mutliple IDPs, then you should create separate Auth0 tenants for that organization; see [Tenant provision for complex organizations](#tenant-provis
Aligned with the suggestion in PR 7801

```suggestion
If your customers' organization supports the use of mutliple IDPs, then we recommend that you create separate Auth0 tenants for that organization; see [Tenant provision for complex organizations](#tenant-provision-for-complex-organizations) for further details. This allows you to keep the rest of your setup much simpler by maintaining a one-to-one connection relationship between your organization and all your customer organizations within your main tenant. 
```

2019-06-21 15:28 UTC, tamigoodall commented on articles/architecture-scenarios/_includes/_architecture/_introduction.md
> +If your customers' organization supports the use of mutliple IDPs, then you should create separate Auth0 tenants for that organization; see [Tenant provision for complex organizations](#tenant-provis
Added to PR 7818