Use react router history.push
auth0/docs pull request #8151
Opened 2019-08-26 18:01 UTC by luisrudge

Following our sample PR: https://github.com/auth0-samples/auth0-react-samples/pull/154

2019-08-27 18:17 UTC, lbalmaceda requested changes

2019-08-27 18:17 UTC, lbalmaceda commented on articles/quickstart/spa/react/_includes/_centralized_login.md
> +<%= include('../../\_includes/\_login_preamble', { library: 'React' }) %>
rollback this line change

2019-08-27 18:17 UTC, lbalmaceda commented on articles/quickstart/spa/react/_includes/_centralized_login.md
> +<%= include('../../\_includes/\_silent-auth-social-idp') %>
rollback this line change

2019-08-27 18:21 UTC, luisrudge commented on articles/quickstart/spa/react/_includes/_centralized_login.md
> +<%= include('../../\_includes/\_login_preamble', { library: 'React' }) %>
done

2019-08-27 18:21 UTC, luisrudge commented on articles/quickstart/spa/react/_includes/_centralized_login.md
> +<%= include('../../\_includes/\_silent-auth-social-idp') %>
done

2019-10-21 22:44 UTC, joshcanhelp commented
@luisrudge - Looks like this one fell off the radar. I requested review from @lbalmaceda again but need to rebase.

2019-10-22 21:33 UTC, lbalmaceda submitted a review, later dismissed
Fix the conflicts @luisrudge

2019-10-29 01:21 UTC, luisrudge commented
done

2019-10-29 20:53 UTC, lbalmaceda approved these changes

2019-11-18 19:35 UTC, merged