Add info on how to access the raw id_token
auth0/docs pull request #8152
Opened 2019-08-26 18:03 UTC by luisrudge

2019-08-26 18:52 UTC, lbalmaceda requested changes

2019-08-26 18:52 UTC, lbalmaceda commented on articles/libraries/auth0-spa-js/index.md
> +  // if you need the raw id_token, you can access it
Please remove the rest of the changes and only keep this. It seems your code formatting tool is refactoring everything else.

2019-09-18 17:23 UTC, lbalmaceda commented
@luisrudge see my comment above. Build is broken.

2019-10-08 20:11 UTC, luisrudge commented on articles/libraries/auth0-spa-js/index.md
> +  // if you need the raw id_token, you can access it
fixed in https://github.com/auth0/docs/pull/8345

2019-10-08 20:11 UTC, luisrudge commented
fixed in https://github.com/auth0/docs/pull/8345

2019-10-08 20:11 UTC, closed without merging