Removed SDK installation instructions from React quickstart intro
auth0/docs pull request #8285
Opened 2019-09-30 10:25 UTC by stevehobbsdev

These have proven to be confusing for the customer, as they are generic
and don't relate to the quickstart tutorial at all. One of the main
pieces of feedback is that they see the import statement but they don't
know which file to put it in.

Installation of the library is repeated further down the tutorial in
context, and more detailed instructions are included as part of the
README on GitHub.

In doing this I also reworded the "Install dependencies" section to call out why the libraries are being installed, for a bit more impact.

- Also removed the "Authenticating with Auth0" include as it's not hugely
required knowledge for the new SDK and just adds fluff.
- Also changes "checkpoint" notes to proper panels

2019-09-30 14:53 UTC, joshcanhelp requested changes
Few small updates ... otherwise, great improvement! Should we map this over to the other quickstarts that use this section?

2019-09-30 14:53 UTC, joshcanhelp commented on articles/quickstart/spa/react/_includes/_centralized_login.md
> +At this point, you should be able to go through a complete authentication cycle, logging in and loggin out. Start the application from the terminal using `yarn start` and browse to http://localhost:3
```suggestion
At this point, you should be able to go through the complete authentication flow: logging in and logging out. Start the application from the terminal using `yarn start` and browse to [localhost:3000](http://localhost:3000) (if the application does not open automatically). From there, clicking the **Log in** button should redirect you to the Auth0 login page where you will be given the opportunity to log in.
```

2019-09-30 15:57 UTC, stevehobbsdev commented
@joshcanhelp I think that might be worth doing. It's only the Angular one left that uses this, I've already removed it from the new Vue one.

2019-10-01 00:13 UTC, joshcanhelp approved these changes

2019-10-01 09:02 UTC, merged