Added note about parental consent
auth0/docs pull request #8403
Opened 2019-10-23 18:17 UTC by tamigoodall

Added note

2019-10-23 22:39 UTC, rkhoriander requested changes
This file is also changed in this PR, but isn't showing your new include:
/compliance/gdpr/features-aiding-compliance/user-consent/track-consent-with-lock

2019-10-24 18:27 UTC, tamigoodall commented
I see the new include in that link here: https://docs-content-staging-pr-8403.herokuapp.com/docs/compliance/gdpr/features-aiding-compliance/user-consent/track-consent-with-lock - near the bottom.

2019-10-24 20:19 UTC, rkhoriander commented
Bizarre. I see it now. I wonder if I got caught between builds. Anyway, looks good!

2019-10-24 20:19 UTC, rkhoriander approved these changes

2019-10-24 20:22 UTC, merged