Added a small section to verify token signature algorithm to SPA quickstarts
auth0/docs pull request #8593
Opened 2019-12-20 15:56 UTC by stevehobbsdev

This PR adds a small section to explain how to verify the signature algorithm settings for your Auth0 client. We felt this was needed since the new SPA JS (which the majority of the SPA quickstarts use) only support RS256, but a few legacy applications or incorrectly-configured default apps were breaking because they had their settings inadvertly set to HS256. This new section hopefully clarifies how they can check this setting for themselves.

![image](https://user-images.githubusercontent.com/766403/71266756-f3008c80-2340-11ea-8ec8-17d659b3ad88.png)

2019-12-20 20:57 UTC, joshcanhelp requested changes
A few updates here.

2019-12-20 20:57 UTC, joshcanhelp commented on articles/_includes/_token_signature.md
> +Json Web Tokens should be signed using the RS256 signing algorithm where possible, as [it provides enchanced security over HS256](https://auth0.com/docs/tokens/concepts/signing-algorithms#our-recomme
```suggestion
JSON Web Tokens (JWTs) should be signed using the RS256 signing algorithm where possible, as it provides [enhanced security over HS256](https://auth0.com/docs/tokens/concepts/signing-algorithms#our-recommendation).
```

2019-12-20 20:57 UTC, joshcanhelp commented on articles/_includes/_token_signature.md
> +This setting is the default, but if you are [running into errors](https://auth0.com/docs/errors/libraries/auth0-js/invalid-token#parsing-an-hs256-signed-id-token-without-an-access-token) you can veri
```suggestion
RS256 is the default, but if you are [running into errors](https://auth0.com/docs/errors/libraries/auth0-js/invalid-token#parsing-an-hs256-signed-id-token-without-an-access-token) you can verify your settings by clicking on **Show Advanced Settings** at the bottom of your Auth0 Application settings screen in the dashboard. Click the **OAuth** tab to show the signature algorithm configuration. **JsonWebToken Signature Algorithm** should be set to **RS256**, and the **OIDC Conformant** setting should be enabled.
```

2020-01-07 14:48 UTC, lbalmaceda approved these changes

2020-01-07 17:29 UTC, joshcanhelp approved these changes

2020-01-08 20:16 UTC, merged