Update express quickstart
auth0/docs pull request #8946
Opened 2020-04-23 04:43 UTC by davidpatrick

We are removing the secure localhost setup.  There were concerns with generating a root local authority and the complexity this adds to the quickstart.

The reason why we have the secure local guidance there is because of same site flags coming from Chrome for localhost.  However, they have announced that they will delay the roll out of same site here https://www.chromium.org/updates/same-site

With the delay in rollout, this gives us time to improve the secure localhost guidance, or change the quickstart to use authcode+pkce to avoid having to use secure localhost for a quickstart.

2020-04-23 12:23 UTC, adamjmcgrath requested changes
You'll also need to change the `baseURL` to `http`

2020-04-23 22:07 UTC, davidpatrick commented
Thanks @adamjmcgrath 😅

2020-04-24 16:27 UTC, adamjmcgrath approved these changes

2020-04-24 16:27 UTC, merged

2020-04-24 19:42 UTC, pdillon commented
Late nit comment: should usage of `appSessionSecret` be changed to `appSession.secret` or something similar to reflect the config change?