Remove legacy OIDC behavior paragraph
auth0/docs pull request #9012
Opened 2020-05-08 14:36 UTC by lbalmaceda

2020-05-08 14:39 UTC, Widcket requested changes

2020-05-08 14:39 UTC, Widcket commented on articles/libraries/auth0-android/index.md
Remove extra whitespace

2020-05-08 23:03 UTC, krismb approved these changes

2020-05-08 23:05 UTC, krismb submitted a review, later dismissed

2020-05-11 19:16 UTC, Widcket approved these changes

2020-05-11 19:16 UTC, merged