Chore: break social connections into snippets
auth0/docs pull request #9335
Opened 2020-08-05 19:28 UTC by faroceann

## References
https://auth0team.atlassian.net/browse/DXEC-163

## Script used
`articles/connections/parse.script.js`

```javascript
const fs = require("fs");
const path = require("path");

const getInclude = (include) => {
  const text = fs.readFileSync(path.join(__dirname, include), {
    encoding: "UTF8",
  });
  return text;
};

const splitter = (name, string) => {
  let prev;
  let curSection = [];
  let sections = [];
  let heading = [];
  const closing = "---";
  let reachedClose = false;
  let reachedOpen = false;
  const newDoc = [];
  string.split("\n").forEach((line, i) => {
    if (line === closing && !reachedOpen) {
      newDoc.push(line + "\n");
      reachedOpen = true;
      return;
    }
    if (line === closing && reachedOpen) {
      newDoc.push(line + "\n");
      reachedClose = true;
      return;
    }
    if (!reachedClose) {
      newDoc.push(line + "\n");
      return;
    }
    if (line.includes("<%= include('../_quickstart-links.md') %>")) {
      newDoc.push(line + "\n");
      return;
    }
    if (line.includes("<%= include(")) {
      console.warn("Include encountered: ", line);
      let includePath = line.split("'")[1].replace("../", "");
      if (!includePath.endsWith(".md")) {
        includePath += ".md";
      }
      const include = getInclude(includePath);
      curSection.push(include);
      return;
    }
    if (line.includes("## ") || line.includes("# ") || line.includes("### ")) {
      if (curSection.join("")) {
        sections.push(curSection.join(""));
      }
      curSection = [];
      newDoc.push(`<%= include('../../../snippets/${name}/${sections.length}') %> \n`);
    } else {
      heading = [];
    }
    if (heading.length) {
      //         curSection = curSection.concat(heading)
    }
    curSection.push(line + '\n');
    prev = line;
  });
  return { newDoc, sections };
};

const connections = fs.readdirSync(path.join(__dirname, "./social"));

connections.forEach((manifestPath) => {
  if (manifestPath.includes("github")) {
    return;
  }
  console.log(manifestPath);
  const manifest = fs.readFileSync(
    path.join(__dirname, "social", manifestPath),
    { encoding: "UTF8" }
  );
  const name = manifestPath.replace(".md", "")
  const split = splitter(name, manifest);
  fs.mkdirSync(path.join(__dirname, "..", "..", "snippets", "social", name));
  split.sections.forEach((section, i) => {
    fs.writeFileSync(
      path.join(__dirname, "..", "..", "snippets", "social", name, i + ".md"),
      section
    );
  });
  fs.writeFileSync(path.join(__dirname, "social", name + ".md"), split.newDoc.join(''));
  console.log(split);
});
```

2020-08-05 21:56 UTC, joshcanhelp requested changes
Nice work on this, love that you wrote a script ... I probably would have copy/pasted like a caveman 😆 

In general, I would suggest leaving out anything that's not going to be used from the API. Also flagged a few of the deprecated/removed ones which, at thing point, probably should be deleted (cc @rkhoriander).

2020-08-05 21:56 UTC, joshcanhelp commented on articles/connections/social/devkeys.md
> -
I don't think this one needs to be converted 🤔

2020-08-05 21:56 UTC, joshcanhelp commented on articles/connections/social/instagram.md
> -# Connect Apps to Instagram
This one is deprecated so we won't have a guide for it.

2020-08-05 21:56 UTC, joshcanhelp commented on articles/connections/social/oauth2.md
> -# Connect Apps to Generic OAuth2 Authorization Servers
This is for a custom connection and is for the extension so probably another one to omit

2020-08-05 21:56 UTC, joshcanhelp commented on articles/connections/social/reprompt-permissions.md
> -
Can probably leave this one out also

2020-08-05 21:56 UTC, joshcanhelp commented on articles/connections/social/soundcloud.md
> -
This one is deprecated so we won't have a guide for it.

2020-08-07 16:37 UTC, faroceann commented on articles/connections/social/devkeys.md
> -
@joshcanhelp do you think it should be removed, or reverted?

2020-08-07 16:43 UTC, faroceann commented on articles/connections/social/devkeys.md
> -
Going to opt for reverting all of the deprecated/ unneeded conversions

2020-08-07 18:24 UTC, joshcanhelp submitted a review, later dismissed
🙌  🙌  🙌

2020-08-11 17:16 UTC, erjohnson approved these changes

2020-08-11 17:17 UTC, merged