Update the RN QS for the SDK v2.9.0
auth0/docs pull request #9768
Opened 2021-06-22 17:42 UTC by Widcket

This PR updates the React Native QS to match the new integration instructions for Android (since the SDK `v2.9.0` release).
SDK release PR: https://github.com/auth0/react-native-auth0

**DO NOT MERGE UNTIL RELEASE IS OUT**

2021-06-23 07:56 UTC, lbalmaceda approved these changes

2021-06-23 10:25 UTC, lbalmaceda requested changes, later dismissed
The [sample app](https://github.com/auth0-samples/auth0-react-native-sample/) would also need an update, right?

2021-06-23 10:25 UTC, lbalmaceda commented on articles/quickstart/native/react-native/00-login.md
> +        manifestPlaceholders = [auth0Domain: "${account.namespace}", auth0Scheme: "${applicationId}"]
I think these need to be escaped for the build to complete successfully. See the previous line for reference https://github.com/auth0/docs/pull/9768/files#diff-0a0acd30f658f139c1feac53f542219f8c9441c8de17fd5d27981439ae022d09L93.

2021-06-23 17:28 UTC, Widcket commented
> The [sample app](https://github.com/auth0-samples/auth0-react-native-sample/) would also need an update, right?

Yes, I'll update it next.

2021-06-23 18:23 UTC, adamjmcgrath approved these changes

2021-06-24 12:02 UTC, cocojoe approved these changes

2021-06-24 12:30 UTC, cristiandouce approved these changes

2021-06-24 12:42 UTC, merged