Add okta as oidc idp draft
auth0/docs pull request #9805
Opened 2021-07-13 17:29 UTC by erjohnson

2021-07-14 19:43 UTC, aaguiarz requested changes
Added a few comments

2021-07-14 19:43 UTC, aaguiarz commented on articles/connections/enterprise/okta.md
> +To be configurable through the Auth0 Dashboard, the OpenID Connect (OIDC) Identity Provider (IdP) needs to support [OIDC Discovery](https://openid.net/specs/openid-connect-discovery-1_0.html). Otherw
OKTA supports this, so we don't need the warning

2021-07-14 19:43 UTC, aaguiarz commented on articles/connections/enterprise/okta.md
> +| **Issuer URL** | URL where Auth0 can find the **OpenID Provider Configuration Document**, which should be available in the `/.well-known/openid-configuration` endpoint. You can enter the base URL o
We should give an example with how it would look with OKTA, eg. we don't need to say "which should be available" because we know where it is.

2021-07-14 19:43 UTC, aaguiarz commented on articles/connections/enterprise/okta.md
> +| **Client ID** | Unique identifier for your registered Azure AD application. Enter the saved value of the **Client ID** for the app you registered with the OIDC Identity Provider. |
It says "Azure AD application".

2021-07-14 19:43 UTC, aaguiarz commented on articles/connections/enterprise/okta.md
> +### Create an enterprise connection using the Management API
Maybe we can omit that section, and link to the OIDC one?

2021-07-14 19:43 UTC, aaguiarz commented on articles/connections/enterprise/okta.md
> +## Federate with Auth0
This part should be removed

2021-08-02 17:25 UTC, tamigoodall submitted a review, later dismissed

2021-08-25 19:28 UTC, rkhoriander approved these changes

2021-08-25 19:35 UTC, closed without merging