[SDK-2856] Update QS for Go webapp
auth0/docs pull request #9898
Opened 2021-10-18 11:41 UTC by sergiught

### Ticket: https://auth0team.atlassian.net/browse/SDK-2856

## Description

In this PR we are updating our Go Web App QS to reflect the changes introduced with https://github.com/auth0-samples/auth0-golang-web-app/pull/39

2021-10-18 12:24 UTC, stevehobbsdev requested changes
Looks good, I added a few comments and suggestions. Not all of it is blocking. Feel free to ping if you have any questions.

2021-10-18 12:24 UTC, stevehobbsdev commented on articles/quickstart/webapp/golang/01-login.md
> +configuration and fill in the environment variables:
Consider more concise, action-orientated language for quickstarts. Sentences elsewhere in the same doc have more of a bias towards this.

Also, a suggestion for the end that rids the apostophe and makes it a bit easier to read/say.

```suggestion
Create a `.env` file within the root of the project directory to store the app configuration, and fill in the environment variables:
```

2021-10-18 12:24 UTC, stevehobbsdev commented on articles/quickstart/webapp/golang/01-login.md
> +### Download Dependencies
Typically for 2nd/3rd level headings, use a sentence-case format in line with the [writing guide](https://github.com/auth0/docs/blob/master/STYLEGUIDE.md#formatting).

I would have a scan over all the other headings in the doc and ensure the formatting aligns.

2021-10-18 12:24 UTC, stevehobbsdev commented on articles/quickstart/webapp/golang/01-login.md
> +Let's start by adding a `go.mod` file listing all the dependencies we will be using.
See my later comment around conciseness. Also, be wary of using 'we', and favour 'you'. Or better, write it out (see [voice](https://github.com/auth0/docs/blob/master/STYLEGUIDE.md#voice) in the style guide.

Something like:

```suggestion
Start by adding a `go.mod` file to list all the dependencies to be used.
```

2021-10-18 12:24 UTC, stevehobbsdev commented on articles/quickstart/webapp/golang/01-login.md
> +:::
Think this needs some punctuation as it took a few reads to understand

```suggestion
::: note
To load the environment variables from the `.env` file, you can use [github.com/joho/godotenv](https://github.com/joho/godotenv).
:::
```

2021-10-18 12:24 UTC, stevehobbsdev commented on articles/quickstart/webapp/golang/01-login.md
> +an instance of our `Authenticator` to the method, so it can be used within the `login` and `callback` handlers.
```suggestion
an instance of `Authenticator` to the method, so it can be used within the `login` and `callback` handlers. 
```

2021-10-18 12:24 UTC, stevehobbsdev commented on articles/quickstart/webapp/golang/01-login.md
> +application at our callback route, `/callback` that will be handled in the following `Handler` function:
Suggestion for conciseness:

```suggestion
Once users have authenticated using Auth0's Universal Login Page, they'll return to the app at the `/callback` route that will be handled in the following `Handler` function:
```

2021-10-18 12:24 UTC, stevehobbsdev commented on articles/quickstart/webapp/golang/01-login.md
> +To log the user out, you have to clear the data from the session and redirect the user to the Auth0 logout endpoint.
```suggestion
To log the user out, clear the data from the session and redirect the user to the Auth0 logout endpoint. 
```

2021-10-18 12:24 UTC, stevehobbsdev commented on articles/quickstart/webapp/golang/01-login.md
> +or not based on if the `profile` is in the session:
Consider making this one line rather than split across two.

```suggestion
Create a middleware that will check if the user is authenticated or not based on the `profile` session key.
```

Not sure if I've referred to what "profile" is here (is it a session key?) but nevertheless, I think referring to it as a "thing" like this reads better; I'm sure you can use the right terminology here.

2021-10-18 12:24 UTC, stevehobbsdev commented on articles/quickstart/webapp/golang/01-login.md
> +Finally, we can set up this middleware for any route that needs authentication:
```suggestion
Finally, set up this middleware for any route that needs authentication:
```

I think it also might need some instruction here. As in, how is the setup done? Something like:

```suggestion
Finally, set up this middleware for any route that needs authentication by adding it to the router.
```

2021-10-18 12:57 UTC, sergiughf commented
Really appreciate the review @stevehobbsdev ! 🙇🏻  I've addressed everything in https://github.com/auth0/docs/commit/c6d43624eeeab24f43bc84795f535075f946205d

2021-10-18 12:59 UTC, sergiught commented on articles/quickstart/webapp/golang/01-login.md
> +or not based on if the `profile` is in the session:
Yes indeed, it's a session key:) Thank you! I updated this in https://github.com/auth0/docs/commit/c6d43624eeeab24f43bc84795f535075f946205d

2021-10-18 13:20 UTC, stevehobbsdev submitted a review, later dismissed

2021-10-19 01:41 UTC, Widcket commented on articles/quickstart/webapp/golang/01-login.md
> +::: note
Not sure about the need for this note, as `godotenv` is already included as a dependency in the `go.mod` and is used in `main.go`.

2021-10-19 01:50 UTC, Widcket commented on articles/quickstart/webapp/golang/01-login.md
> +			ctx.String(http.StatusUnauthorized, "Failed to convert an authorization code into a token.")
Maybe keep the 'exchange' terminology (like it is in the comment at line 332) instead of using 'convert'?

2021-10-19 01:57 UTC, Widcket submitted a review, later dismissed
Looks good. Just left a couple of non-blocking comments.

2021-10-19 03:27 UTC, sergiught commented on articles/quickstart/webapp/golang/01-login.md
> +::: note
Removed in https://github.com/auth0/docs/pull/9898/commits/05615d4b3160ffc1aacae020d272098f81dc2d0a

2021-10-19 03:27 UTC, sergiught commented on articles/quickstart/webapp/golang/01-login.md
> +			ctx.String(http.StatusUnauthorized, "Failed to convert an authorization code into a token.")
Reworded in https://github.com/auth0/docs/pull/9898/commits/05615d4b3160ffc1aacae020d272098f81dc2d0a

2021-10-19 03:37 UTC, Widcket approved these changes
LGTM

2021-10-19 08:08 UTC, merged